### ISSUE TITLE
Allow indenting preprocessor macros?

### ISSUE THREAD

**Issue by matthijskooijman** [stm32duino/Arduino_Core_STM32#1006]
While developing #997, I wrote some complicated and nested preprocessor statements. I originally tried making them clearer by applying indents, but that was not allowed by the astyle checks, so I removed them again. Now I wonder, should this astyle rule maybe be changed to allow (even if not require) indenting preprocessor directives?

e.g. consider:

```C
#if defined(USBD_ATTACH_PIN)
#define USBD_PULLUP_CONTROL_PINNAME digitalPinToPinName(USBD_ATTACH_PIN)
#define USBD_DETACH_LEVEL !(USBD_ATTACH_LEVEL)
#elif defined(USBD_DETACH_PIN)
#define USBD_DETACH_PINNAME digitalPinToPinName(USBD_DETACH_PIN)
#define USBD_ATTACH_LEVEL !(USBD_DETACH_LEVEL)
#elif !USBD_HAVE_INTERNAL_PULLUPS
/* When no USB attach and detach pins were defined, and the USB module
 * also does not have any builtin pullups, assume there is a fixed
 * external pullup and apply the D+ trick. */
#if defined(USE_USB_HS_IN_FS)
#define USBD_PULLUP_CONTROL_PINNAME USB_OTG_HS_DP
#elif defined(USB_OTG_FS)
#define USBD_PULLUP_CONTROL_PINNAME USB_OTG_FS_DP
#else /* USB */
#define USBD_PULLUP_CONTROL_PINNAME  USB_DP
#endif
/* Detach by writing LOW, but leave floating instead of writing
 * HIGH to attach. */
#define USBD_DETACH_LEVEL LOW
#define USBD_PULLUP_CONTROL_FLOATING
#endif /* !defined(USBD_ATTACH_PINNAME) && !USBD_HAVE_INTERNAL_PULLUPS */
```

vs:

```C
#if defined(USBD_ATTACH_PIN)
    #define USBD_PULLUP_CONTROL_PINNAME digitalPinToPinName(USBD_ATTACH_PIN)
    #define USBD_DETACH_LEVEL !(USBD_ATTACH_LEVEL)
#elif defined(USBD_DETACH_PIN)
    #define USBD_DETACH_PINNAME digitalPinToPinName(USBD_DETACH_PIN)
    #define USBD_ATTACH_LEVEL !(USBD_DETACH_LEVEL)
#elif !USBD_HAVE_INTERNAL_PULLUPS
    /* When no USB attach and detach pins were defined, and the USB module
     * also does not have any builtin pullups, assume there is a fixed
     * external pullup and apply the D+ trick. */
    #if defined(USE_USB_HS_IN_FS)
        #define USBD_PULLUP_CONTROL_PINNAME USB_OTG_HS_DP
    #elif defined(USB_OTG_FS)
        #define USBD_PULLUP_CONTROL_PINNAME USB_OTG_FS_DP
    #else /* USB */
        #define USBD_PULLUP_CONTROL_PINNAME  USB_DP
    #endif
    /* Detach by writing LOW, but leave floating instead of writing
     * HIGH to attach. */
    #define USBD_DETACH_LEVEL LOW
    #define USBD_PULLUP_CONTROL_FLOATING
#endif /* !defined(USBD_ATTACH_PINNAME) && !USBD_HAVE_INTERNAL_PULLUPS */
```

The latter is IMHO a *lot* more readable.

**Comment by matthijskooijman** [comment]
Pressed submit too soon, updated first post with my actual issue description.

**Comment by fpistm** [comment]
Why not.
I've based the astyle rules on Arduino one.

**Comment by matthijskooijman** [comment]
I had a look at the astyle docs, the [http://astyle.sourceforge.net/astyle.html#_indent-preproc-block](indent-preproc-block) option manages this. There seems to be no option to allow, but not require this indentation (but I think this is how astyle works with all options), so enabling this would mean a lot of files need to be updated (but again, astyle automates this).

I just created #1007 to see what this would do.

**Comment by matthijskooijman** [comment]
Hm, a related question: It seems that the github astyle check uses https://github.com/stm32duino/actions/tree/master/astyle-check which duplicates both the checking script as well as the astyle configs from the CI subdirectory in this repo. Why does the check not just run the script from this repo, so any changes to that are automatically applied?

**Comment by fpistm** [comment]
> Why does the check not just run the script from this repo, so any changes to that are automatically applied?

First goal is to have an action not dependent to the core. I did not find any "official" action for astyle that's why I've made my own one.
Moreover it is possible to specify a custom astyle-definition.

**Comment by fpistm** [comment]
I've fixed that with https://github.com/stm32duino/Arduino_Core_STM32/commit/5f5fa6f89763195f80c7b44a3ebc37ce760b54b2

I've relaunched the actions on #1007

**Comment by fpistm** [comment]
Thanks @matthijskooijman 
#1007 merged.
