### ISSUE TITLE
How many different pins can be used with tone at one time?

### ISSUE THREAD

**Issue by AlexandreRouma** [stm32duino/Arduino_Core_STM32#1012]
Hi, I'm currently writing a small MIDI controller using a bluepill board and I was wondering how many different tones could be played at once and on what pins?

Cheers

**Comment by ABOSTM** [comment]
Hi @AlexandreRouma ,
It is preferable to ask such question to the forum: https://www.stm32duino.com/
Only 1 tone at a time. Any pin can be used.

**Comment by AlexandreRouma** [comment]
Thanks for the info!
I solved it by making my own tone command that uses the 4 available timers to have 4 available tone channels

Cheers

**Comment by fpistm** [comment]
Do not hesitate to share with the community, here on better on the forum https://www.stm32duino.com 😉
