### ISSUE TITLE
Built-in library Servo issue

### ISSUE THREAD

**Issue by fpistm** [stm32duino/Arduino_Core_STM32#102]
Built-in library Servo does not work properly for all series.
It is not enough generic and need to be corrected.

**Comment by fprwi6labs** [comment]
[PR](https://github.com/arduino-libraries/Servo/pull/10) done on official library. 
It fixed the pulse width error.

**Comment by fpistm** [comment]
Merged in the core. Servo lib could be removed when PR on official Servo library will be merged.
