### ISSUE TITLE
Ola, onde encontrar o arquivo C8T6_64K.bin para usar no STM 32

### ISSUE THREAD

**Issue by Franciscodariosouzalima** [stm32duino/Arduino_Core_STM32#1020]

**Comment by fpistm** [comment]
Hi @Franciscodariosouzalima 

Please use english for request.
Don't know which C8T6_64K.bin you talk about.

**Comment by Franciscodariosouzalima** [comment]
E pra usar a USB da placa STM 32 da robotdyn 
https://github.com/stm32duino/Arduino_Core_STM32
preciso fazer o bootloader e necessita desse arquivo C8T6_64K.bin

**Comment by fpistm** [comment]
Please use english.
We do not mage robotdyn bootloader, this file is not part of the STM32 core.

**Comment by Franciscodariosouzalima** [comment]
thank!

**Comment by Franciscodariosouzalima** [comment]
> Oi @Franciscodariosouzalima
> 
> Por favor, use inglês para solicitação.
> Não sei de qual C8T6_64K.bin você fala.

obrigado, vou ver com o vendedor
