### ISSUE TITLE
analogWrite(PIN, value); is 8bit by default instead of 12-bit by default

### ISSUE THREAD

**Issue by HamidSaffari** [stm32duino/Arduino_Core_STM32#1022]
Hi.
I just realized analogWrite(PIN, value); is 8bit by default instead of 12-bit by default.
I attach an LED on PB6 pin and when I change the output PWM value (duty-Cycle) from 0 to 4095 on this pin, LED gets darker and brighter about 8-times in between.
now how could I change it?

**Comment by HamidSaffari** [comment]
on the roger-clark core we have the same issue with analogWrite.
only pwmWrite(PIN, value) on his core works right.

**Comment by fpistm** [comment]
8 bits is the default. There is no issue. 
Use analogWriteResolution: https://www.arduino.cc/reference/en/language/functions/zero-due-mkr-family/analogwriteresolution/
Please use the forum https://www.stm32duino.com for this kind of question. This is the primary support way.

**Comment by HamidSaffari** [comment]
Thank you very much.
Because you said here:
https://github.com/stm32duino/Arduino_Core_STM32/issues/790#issuecomment-557863004
that default is 12-bit so I thought so.

Just two other question please:
1. How can we set the PWM resolution to 16 ?
2. How can we get output from special DAC output pins ?

**Comment by fpistm** [comment]
@HamidSaffari 
as the #790 said this is a bug which is resolved thanks #814 ...


> Just two other question please:
> 
> 1. How can we set the PWM resolution to 16 ?
> 2. How can we get output from special DAC output pins ?

As said issue is not for support, please use the forum.
Moreover, the 1st question is already answered, use the `analogWriteResolution`
For the 2nd, if the pins used with analogWrite as DAC capabilities, then the DAC will be used.
