### ISSUE TITLE
Incorrect link https://stm32duino.com on https://github.com/stm32duino

### ISSUE THREAD

**Issue by lnlp** [stm32duino/Arduino_Core_STM32#1024]
Not directly related to this repository but to its parent account.
On the account page there is no option for feedback so I put this into this repository issue.

On top of the https://github.com/stm32duino account page the following link is listed:
https://stm32duino.com

That link is invalid however. The correct URL is:
https://www.stm32duino.com

**Comment by fpistm** [comment]
Thanks @lnlp 
This is fixed.
