### ISSUE TITLE
Nucleo F091RC  pc0,pc1  Serial not working

### ISSUE THREAD

**Issue by MINI-Qiang** [stm32duino/Arduino_Core_STM32#1025]
**Expected behavior**
test code
```cpp
HardwareSerial Serial6(PC1, PC0);
void setup() 
{
  Serial6.begin(9600);
}
void loop()
{
  Serial6.println("abc");
  delay(1);
}
```
pc0 print  “abc”

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Arduino IDE version: [e.g. 1.8.8]
 - STM32 core version: [e.g. 1.8.0]
 - Tools menu settings if not the default: [e.g. Newlib Standard, No Serial]
 - Upload method: [e.g. STLink]

**Board (please complete the following information):**
 - Name: [e.g. Nucleo F091RC]

**Additional context**
just PC0 PC1 Serial6 not working， Other serial ports normal

**Comment by fpistm** [comment]
Hi @MINI-Qiang 
there is no issue.
This is linked to the PeripheralPins.c configuration of the Nucleo F091RC.

https://github.com/stm32duino/Arduino_Core_STM32/blob/930184beec61f03d84b85dafc9167145d84ec974/variants/NUCLEO_F091RC/PeripheralPins.c#L166-L167

As you can see PC0 is set to use USART7.

As array are weak, you can override it at sketch level:
```
const PinMap PinMap_UART_TX[] = {
  {PC_0,  USART6,  STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF2_USART6)}, // A5
  {NC,    NP,    0}
};
```
