### ISSUE TITLE
AnalogRead() for PC3 stucked of STM32F103RCT6

### ISSUE THREAD

**Issue by meitao605** [stm32duino/Arduino_Core_STM32#1028]
Version: STM32 Core 1.8.0
Arduino Verison: 1.8.12
UploadMethod: ST_LINK

Chip：STM32F103RCT6

code:
-------------------------------------------------------
HardwareSerial Uart1(PA10,PA9);
int fold_current;

void setup() {
  pinMode(PC3,INPUT_ANALOG);
  Uart1.begin(9600);
}

void loop()
 {
  fold_current = analogRead(PC3);
  Uart1.println(fold_current);
  delay(100);
}
--------------------------------------------------------------------
After Upload this code, it will stuck and nothing print out from the Uart1.
but works fine and print out the value for other pins, simple replace the PC3 to other pins will work.

the pins i have tried:

PC1
PC2
PC4
PC5
PA1

Hardware: 2 different boards with STM32F103RCT6.  one is my self-made boards. another is the AlienTEK develop Boards. which can be found www.alientek.com( MiniSTM32F103 )

I tried to check the pin-Map, it seems OK.

**Comment by fpistm** [comment]
PC3 relies on ADC3.
This is a known and fixed issue, see #910.
You also open a topic on the forum and this is good, no need to open an issue while you don't have an answer. Moreover, if you searched before to the forum you would found the answer and the fix.
