### ISSUE TITLE
Error while adding library

### ISSUE THREAD

**Issue by RSDhanu** [stm32duino/Arduino_Core_STM32#1033]
Hii,
While adding https://github.com/stm32duino/Arduino_Core_STM32.git ,this library in my arduino ide getting "Specified folder/zip file does not contain a valid library" error.
How to solve this problem? any one please help me.

**Comment by stas2z** [comment]
0. Use https://www.stm32duino.com/ board for such questions
1. It's not a library, it's a CORE
How to install core: https://github.com/stm32duino/wiki/wiki/Getting-Started

**Comment by fpistm** [comment]
@stas2z well answered.
