### ISSUE TITLE
Timer driven interrupts

### ISSUE THREAD

**Issue by Adminius** [stm32duino/Arduino_Core_STM32#104]
Hey,
is something like this 
https://github.com/rogerclarkmelbourne/Arduino_STM32/blob/master/STM32F1/libraries/A_STM32_Examples/examples/Maple/TimerInterrupts/TimerInterrupts.ino#L35
planned for this core?

**Comment by fpistm** [comment]
Hi @Adminius,
it should be fine. 
I though to extend Timer but I do not know when.
Any contribution are welcome. ;)
Currently next major steps planned for this core are the Low power management for Lx series and ADC modes which will be extended.

**Comment by Adminius** [comment]
Ok thx, @fpistm . i can wait. I will also try to adopt it, but i'm not sure whether I can manage it :( 
Low power sounds good 👍, but BluePill support is more impotant (at least for me)...

**Comment by fpistm** [comment]
I know I'm always working on BP integration...

**Comment by fpistm** [comment]
Will be covered by #146
