### ISSUE TITLE
Hardware crypto accelerated support

### ISSUE THREAD

**Issue by hockeymikey** [stm32duino/Arduino_Core_STM32#1045]
So the STM32 F756ZG has hardware crypto acceleration. #963 #1014 reference that this isn't supported in Arduino. I'd like a greater explanation on this and the possibility if it can be supported in the F756ZG and like wise boards.

**Comment by fpistm** [comment]
Hi,
well it is simply not supported. I don't see what tell more. There is no dedicated code at the high API level (Arduino library, API,...) to support this feature in the STM32 core. For issue you referenced, it is simply mentioned this is the same board except the x5x have the hardware crypto available, so the board (MCU) are the same.
Anyway as the HAL/LL are available, it can be used by enabling `HAL_CRYP_MODULE_ENABLED` and then you can use all HAL/LL API.
