### ISSUE TITLE
forcing PlatformIO to use the latest Arduino_Core_STM32 in ststm32 platform

### ISSUE THREAD

**Issue by hamed-ta** [stm32duino/Arduino_Core_STM32#1050]
Hi,

is there any way to force PlatformIO to use the latest Arduino_Core_STM32 as the core of ststm32 platform, as you can see so as to being able to compile TFT_eSPI library for STM32F103RC the core STM32 lib should be compile by the latest Arduino_Core_STM32 but when I use ststm32 platform in PlatformIO it seems that it uses another or olde STM32 core, so it doesn't compile,

is the any way to add it manually to the project ?

here is my configs

```
[env:genericSTM32F103RC]
platform = https://github.com/platformio/platform-ststm32.git
board = genericSTM32F103RC
#board = bluepill_f103c6
board_build.mcu = stm32f103rct6
framework = arduino
upload_protocol = stlink
board_build.f_cpu = 72000000L

build_flags =
  -Os
  -DCORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_DEBUG
  -DUSER_SETUP_LOADED=1
  -DST7789_DRIVER=1
  -DTFT_WIDTH=240
  -DTFT_HEIGHT=240
  -DTFT_CS=-1
  -DTFT_DC=PA2
  -DTFT_RST=PA3
  -DLOAD_GLCD=1
  -DSPI_FREQUENCY=32000000
  -DSTM32=1
```

**Comment by fpistm** [comment]
Hi @hamed-ta ,
You should open an issue the PIO GitHub STM32, only Arduino IDE is supported here.
