### ISSUE TITLE
[New Variant]

### ISSUE THREAD

**Issue by hamed-ta** [stm32duino/Arduino_Core_STM32#1051]
Hi, 

it's a request to support of STM32F103RC&E MCUs, which now I can see only they are supported in maple core in PIO.

I use them in my custom board designs so how should I do that ?

for example 

 - MINI STM32
 - https://stm32-base.org/boards/STM32F103RCT6-STM32-Mini-V2.0.html

**Comment by fpistm** [comment]
This is already done thanks:
https://github.com/stm32duino/Arduino_Core_STM32/pull/615
