### ISSUE TITLE
Compatibility with Visual Micro?

### ISSUE THREAD

**Issue by deskl0** [stm32duino/Arduino_Core_STM32#1075]
Hi, I'm using Visual Micro plugin on Visual Studio 2019 Community. Recently I get stm32duino core upgraded from 1.8.0 to 1.9.0. However, I found that I can't compile any project by Visual micro but the native Arduino IDE. When I try to compile .ino file by visual micro, I always get an error from arm compiler. 
`arm-none-eabi-g++*: error: C:\Users\Rambo Rambo\AppData\Local\Temp\VMBuilds\blyatman_edp\STM32_GenF1\Debug\build_opt.h: No such file or directory`
But it works perfectly when I using the 1.8.0 version...
Any possible solutions or hints?

**Comment by fpistm** [comment]
Hi @deskl0 
I never used VS 2019 community.
I guess issue come from this #965 anyway I could not help on this as only Arduino IDE is supported. I guess you have to add yourself a prebuild to generate the build_opt.h or simply remove its usage in the platform.txt.

Please for this kind of question/support request use the forum: https://www.stm32duino.com
