### ISSUE TITLE
1.9 changes signature of HardwareTimer.attachInterrupt

### ISSUE THREAD

**Issue by ArminJo** [stm32duino/Arduino_Core_STM32#1079]
**Describe the bug**
In Version 1.8 there is
```
void attachInterrupt(void (*handler)(HardwareTimer *));
```
in 1.9 it changed to
```
using callback_function_t = std::function<void(void)>;
void attachInterrupt(callback_function_t callback);
```
I use it in an IR library but now I get the Issue
https://github.com/ukw100/IRMP/issues/6

1. Can you provide the old function again, to avoid crashing all 3.party libraries using this feature?
2. Do you have a **release version** defined for helping on **conditional compiling**?

**Comment by stas2z** [comment]
https://github.com/stm32duino/Arduino_Core_STM32/blob/master/cores/arduino/stm32/stm32_def.h#L6-L22

**Comment by ArminJo** [comment]
Thanks
