### ISSUE TITLE
stm32l4xx(NUCLEO_L432KC) i2c can not work

### ISSUE THREAD

**Issue by sinozhou** [stm32duino/Arduino_Core_STM32#1086]
**Describe the bug**
For variant NUCLEO_L432KC on release 1.9.0, try the i2cdetect sketch. It can not work. 

**To Reproduce**
1.Compile the i2cdetect.ino.
2. connect the i2c rtc board sd3078(i2c address is 0x32).
3.connect serial line.
4. it can not detect the sd3078 device.

**Desktop (please complete the following information):**
 - OS: Linux
 - Arduino IDE version: 1.8.12
 - STM32 core version: 1.9.0
 - Upload method: STLink

**Board (please complete the following information):**
 - Name:NUCLEO_L432KC

**Additional context**
The same i2cdetect sketch worked well in variant Mapple_mini(Stm32f103 mcu).

**Comment by fpistm** [comment]
Hi @sinozhou 
the I2Scanner works on Nucleo L432KC and STM32 Core v1.9.0, I've retested...
Did you wire a pull up resistor on each I2C line?
