### ISSUE TITLE
STM32f103c8t blue pill flash size

### ISSUE THREAD

**Issue by hasikp1** [stm32duino/Arduino_Core_STM32#1089]
I have stm32f103 bluepill boards with me and I have both stlink utility and cube programmer installed. STlink utility is showing 64kb flash size and cube programmer is showing 128kb flah size. What is the correct size?
 
![stmflash1](https://user-images.githubusercontent.com/48294216/83607176-62d59d00-a598-11ea-81c8-eb09c741227e.PNG)

![stmflash2](https://user-images.githubusercontent.com/48294216/83607216-7254e600-a598-11ea-81c0-7a7aa6597d25.PNG)

**Comment by fpistm** [comment]
Hard to tell some BP with C8 have in fact 128Kb like a CB.
That's why several STM32 cores provide BP support with 128k and 64k.

Please for this kind of questions use the forum: https://www.stm32duino.com
