### ISSUE TITLE
[New Variant]Stm32f373_BluePill

### ISSUE THREAD

**Issue by nopnop2002** [stm32duino/Arduino_Core_STM32#1096]
**Board description**
 - Name: Stm32f373_BluePill
 - Link to all relevant information:
   * Where this hardware can be purchased
https://www.aliexpress.com/item/4000906442860.html?spm=a2g0o.cart.0.0.6ad03c00B43N6c&mp=1

**Comment by fpistm** [comment]
Hi @nopnop2002 
added to the new variant request list #722

**Comment by nopnop2002** [comment]
Thank you.
