### ISSUE TITLE
Using LTDC library?

### ISSUE THREAD

**Issue by jremington** [stm32duino/Arduino_Core_STM32#1100]
I have the STM32F746G Discovery board, and would like to use the TFT display.
I followed the instructions to add this core and board manager to Arduino 1.8.12, then added the LTDC library folder to the local Arduino sketches directory.

Compilation of the library example Mandelbrot fails as follows:
`Arduino: 1.8.12 (Windows 10), Board: "Discovery, STM32F746G-DISCOVERY, Mass Storage, Enabled (generic 'Serial'), None, Low/Full Speed, Smallest (-Os default), Newlib Nano (default)"

In file included from C:\Users\Jim\Desktop\Arduino\libraries\LTDC\src/LTDC_F746_Discovery.h:6,
                 from C:\Users\Jim\Desktop\Arduino\Mandelbrot\Mandelbrot.ino:10:
C:\Users\Jim\Desktop\Arduino\libraries\LTDC\src/LTDC.h:97:9: error: 'LTDC_HandleTypeDef' does not name a type; did you mean 'RTC_HandleTypeDef'?
   97 |         LTDC_HandleTypeDef  hLtdcHandler;
      |         ^~~~~~~~~~~~~~~~~~
      |         RTC_HandleTypeDef
C:\Users\Jim\Desktop\Arduino\libraries\LTDC\src/LTDC.h: In member function 'void LTDCClass<W, H>::begin(uint16_t*)':
C:\Users\Jim\Desktop\Arduino\libraries\LTDC\src/LTDC.h:105:5: error: 'hLtdcHandler' was not declared in this scope`

What do I need to do to satisfy this dependency?

**Comment by fpistm** [comment]
Hi @jremington 

For this kind of request pleas use the forum: https://www.stm32duino.com

The error is simply that the LTDC HAL module is not enabled by default.
In my branch I've enabled it in the variant:
https://github.com/fpistm/Arduino_Core_STM32/commit/62a306275720a48e8833fb1eb83b549e50630e5a#diff-6ba5daa261970b3ca8185ad8825d4e14R93

So I guess you did not fetch all my branch. So probably some update if the variant are not present.
