### ISSUE TITLE
Can i install the Arduino_Core_STM32 manually?

### ISSUE THREAD

**Issue by Liangkerui** [stm32duino/Arduino_Core_STM32#1105]
I have troubles of downloading the core by Arduino IDE online.I followed all the steps but i failed downloading. So i want install the the core manually.Is it possible?

**Comment by fpistm** [comment]
Hi, 
it is always possible but I will not details it. The best way is to understand why you are not able to install it thanks the boards manager? Proxy issue ?....
Please give more input else we will not be able to help on this.

**Comment by fpistm** [comment]
Hi, 

I close this as no feedback and mainly because this kind of support should be on the forum:
https://www.stm32duino.com
