### ISSUE TITLE
Wrong VCO

### ISSUE THREAD

**Issue by afewyards** [stm32duino/Arduino_Core_STM32#1109]
It's noted as double the max hz. Once I duplicated this board and adjusted those values I got a working chip. 
Is this double for a reason and could it be possible to have variables there so we can overwrite them if we wish?

https://github.com/stm32duino/Arduino_Core_STM32/blob/b12a55485250076e872fa286a925d6b3ae8d3016/variants/Generic_F4x7Vx/variant.cpp#L180

max hz is 168 [specs](https://www.st.com/en/microcontrollers-microprocessors/stm32f407vg.html)

thanks in advance

**Comment by fpistm** [comment]
Hi @afewyards 
Right the CPU max speed is 168 MHz but the PLLN is not the CPU speed.
![image](https://user-images.githubusercontent.com/20641798/86338189-4fc6f300-bc52-11ea-8a42-7f452c9f9a51.png)

If you have an issue maybe the clock used is not the same than the default. For example here it is for a 8 MHz HSE.
So the config is correct.
If the default `SystemClock_Config` does not match your needs you can simply redefine it as it is a weaked function.
Simply define the new one in your sketch:

```
extern "C" void SystemClock_Config(void){
...
}
```
You can also redefine some default clock value if needed:
* https://github.com/stm32duino/wiki/wiki/HAL-configuration#other-hal-configuration

using `hal_conf_extra.h` or  `build_opt.h`:
* https://github.com/stm32duino/wiki/wiki/HAL-configuration#core-version--150-1
* https://github.com/stm32duino/wiki/wiki/Customize-build-options-using-build_opt.h

**Comment by afewyards** [comment]
thanks a million!
