### ISSUE TITLE
Can't find RTCClock.h

### ISSUE THREAD

**Issue by Lightwell-bg** [stm32duino/Arduino_Core_STM32#1121]
I use onbvoard RTS (board = genericSTM32F103C8)
In new version 7 I get error
**src\config.h:6:10: fatal error: RTClock.h: No such file or directory**

In previos version (6.1.1) all work OK

**Comment by fpistm** [comment]
Hi @Lightwell-bg 
This core does not have this file.
I guess you used Roger's core (libMaple):
https://github.com/rogerclarkmelbourne/Arduino_STM32/blob/master/STM32F1/libraries/RTClock/src/RTClock.h

Moreover It seems you used PIO. So check with PIO support why it works before and not now. Probably they change the default core used by default.
