### ISSUE TITLE
UART Serial2, Serial3 not defined for STM32F103C8T6

### ISSUE THREAD

**Issue by arun912-ux** [stm32duino/Arduino_Core_STM32#1127]
For Blue Pill. in Arduino IDE 
UART 1 -> Serial1 -> PA9, PA10 is working 
UART 2 -> Serial2 -> PA2, PA3 is not working. 
UART 1 -> Serial3 -> PB10, PB11 is not working 
IDE is showing error as "Serial2/Serial3 is undefined" 

Can't use UART2, UART3 in Arduino IDE. 
Any help. 
Thanks in advance.

**Comment by jandrassy** [comment]
https://github.com/stm32duino/wiki/wiki/API#hardwareserial
