### ISSUE TITLE
RHF76 052 wrong MCU?

### ISSUE THREAD

**Issue by toogooda** [stm32duino/Arduino_Core_STM32#1128]
The RHF76 052 seems to use the L052 mcu hence the name but variant is setup with L051.
It's out a mistake or effectively identical?

**Comment by fpistm** [comment]
Hi @toogooda 
You are right it is confusing

**Comment by sabas1080** [comment]
at the time the documentation was not good and what existed mentioned that it was STM32L051C8T6, but there may be variants with different chips, the documentation of those chips was bad
