### ISSUE TITLE
Debugging program causes exception at InitVariant()

### ISSUE THREAD

**Issue by Bambofy** [stm32duino/Arduino_Core_STM32#1136]
When debugging an STM32Duino project using VisualMicro and the openocd debugger (Open On-Chip Debugger 0.10.0+dev-01058-g853a05287 (2020-02-13-16:41)) an exception is raised in main.cpp at InitVariant().

However, building and uploading without the debugger the exception is not raised.

**Notes**
If i put a breakpoint on the InitVariant() function and step over it, the program then continues as normal?

**Steps**
1. Build an arduino program
2. upload and attach a debugger to STM32 L452RE

**Excepected**
Program should run without an exception begin raised in the main.cpp.

**Screenshots**
![devenv_hnfwSiEYyr](https://user-images.githubusercontent.com/1304898/89283015-55926880-d644-11ea-92a5-f27e7132a221.png)

> 
> **OpenOCD output**
> openocd: Open On-Chip Debugger 0.10.0+dev-01058-g853a05287 (2020-02-13-16:41)
> openocd: Licensed under GNU GPL v2
> openocd: For bug reports, read
> openocd: 	http://openocd.org/doc/doxygen/bugs.html
> openocd: debug_level: 2
> openocd: 
> =thread-group-added,id="i1"
> GNU gdb (GNU Tools for Arm Embedded Processors 7-2017-q4-major) 8.0.50.20171128-git
> Copyright (C) 2017 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
> and "show warranty" for details.
> This GDB was configured as "--host=i686-w64-mingw32 --target=arm-none-eabi".
> Type "show configuration" for configuration details.
> For bug reporting instructions, please see:
> <http://www.gnu.org/software/gdb/bugs/>.
> Find the GDB manual and other documentation resources online at:
> <http://www.gnu.org/software/gdb/documentation/>.
> For help, type "help".
> Type "apropos word" to search for commands related to "word".
> =cmd-param-changed,param="pagination",value="off"
> Reset_Handler () at C:\Users\Richa\AppData\Local\arduino15\packages\STM32\hardware\stm32\1.9.0\system/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates/gcc\startup_stm32l452xx.s:63
> 63	  ldr   sp, =_estack    /* Set stack pointer */
> Note: automatically using hardware breakpoints for read-only addresses.
> 
> Breakpoint 1, main () at C:\Users\Richa\AppData\Local\arduino15\packages\STM32\hardware\stm32\1.9.0\cores\arduino\main.cpp:50
> 50	  initVariant();
> 
> 
> Kill the program being debugged? (y or n) [answered Y; input not from terminal]
> The program '' has exited with code 0 (0x0).
> 

More in-depth openOCD output follows:

> Warn : Interface already configured, ignoring
> Error: already specified hl_layout stlink
> Info : The selected transport took over low-level target control. The results might differ compared to plain JTAG/SWD
> srst_only separate srst_nogate srst_open_drain connect_deassert_srst
> 
> Info : clock speed 500 kHz
> Info : STLINK V2J35M26 (API v2) VID:PID 0483:374B
> Info : Target voltage: 5.953968
> Info : stm32l4x.cpu: hardware has 6 breakpoints, 4 watchpoints
> Info : Listening on port 3333 for gdb connections
> Info : Unable to match requested speed 500 kHz, using 480 kHz
> Info : Unable to match requested speed 500 kHz, using 480 kHz
> target halted due to debug-request, current mode: Thread 
> xPSR: 0x01000000 pc: 0x0801c8f0 msp: 0x20028000
> Info : Listening on port 6666 for tcl connections
> Info : Listening on port 4444 for telnet connections
> Info : accepting 'gdb' connection on tcp/3333
> Info : device idcode = 0x20016462 (STM32L45/L46xx - Rev: Y)
> Info : flash size = 512kbytes
> Info : flash mode : single-bank
> Info : dropped 'gdb' connection

**Desktop (please complete the following information):**
 - Windows
 - VisualMicro
 - STM32Duino 1.9.0
 - STLink on board 2.1 debugger (external programmer)

**Board (please complete the following information):**
 - Nucleo L452RE
 - Nucleo l452RE-P (as an external debugger)

**Comment by fpistm** [comment]
Hi @Bambofy 

Unfortunately the debug is not supported here only the core build and upload with Arduino IDE is supported.
This kind of request should be opened in the IDE section of the forum to get support and fairly depends of your environment (open ocd configuration and version, board configuration (single or dual bank?, options bytes,...)
