### ISSUE TITLE
[New Variant] Please add BlackPill F401CE

### ISSUE THREAD

**Issue by pawelsky** [stm32duino/Arduino_Core_STM32#1143]
**Board description (please complete the following information):**
 - Name: BlackPill F401CE
 - Link to all relevant information: https://github.com/WeActTC/MiniF4-STM32F4x1

If is pretty much the same as existing BlackPill F401CC, but has bigger RAM (96kb) and flash (512kB). Clock is the same.

Here is a board definition
```
# BlackPill F401CE
# https://github.com/WeActTC/MiniF4-STM32F4x1
GenF4.menu.pnum.BLACKPILL_F401CE=BlackPill F401CE
GenF4.menu.pnum.BLACKPILL_F401CE.upload.maximum_size=524288
GenF4.menu.pnum.BLACKPILL_F401CE.upload.maximum_data_size=98304
GenF4.menu.pnum.BLACKPILL_F401CE.build.board=BLACKPILL_F401CE
GenF4.menu.pnum.BLACKPILL_F401CE.build.product_line=STM32F401xE
GenF4.menu.pnum.BLACKPILL_F401CE.build.variant=Generic_F401Cx

```

I believe changes in GenericF401Cx/PeripherialPins.c and GenericF401Cx/variant.h will be needed in the couple of ifdefs where ARDUINO_BLACKPILL_F401CC is mentioned.
https://github.com/stm32duino/Arduino_Core_STM32/blob/59dda5c138badcb0a17a24f7a30fa81dececa0d7/variants/Generic_F401Cx/PeripheralPins.c#L219
https://github.com/stm32duino/Arduino_Core_STM32/blob/59dda5c138badcb0a17a24f7a30fa81dececa0d7/variants/Generic_F401Cx/variant.h#L74
https://github.com/stm32duino/Arduino_Core_STM32/blob/59dda5c138badcb0a17a24f7a30fa81dececa0d7/variants/Generic_F401Cx/variant.h#L112

**Comment by fpistm** [comment]
Added to [New Variant] request list #722
