### ISSUE TITLE
Support for MCUDev DevEBox STM32H7XX_M board (STM32H750VBT6)

### ISSUE THREAD

**Issue by observator-x** [stm32duino/Arduino_Core_STM32#1145]
- Name: MCUDev DevEBox STM32H7XX_M
 - Link to all relevant information:
  https://github.com/mcauser/MCUDEV_DEVEBOX_H7XX_M

MCUDev STM32H7XX_M mini dev boards.

There are two versions with different STM32H7 chips:

STM32H750VBT6 - 128K flash
STM32H743VIT6 - 2048K flash

Markings: DevEBox STM32H7XX_M Ver:V2.0 SN:1907

**Comment by fpistm** [comment]
Added to the [New Variant] request list #722.

**Comment by Hedda** [comment]
Please note that there looks to be two variants of MCUDev DevEBox STM32H7XX_M boards with different chips / flash memory.

MCUDev DevEBox STM32H7XX_M with STM32H750VBT6 (128KB flash memory & 1024KB SRAM)

MCUDev DevEBox STM32H7XX_M with STM32H743VIT6 (2048KB flash memory & 1024KB SRAM)

https://www.cnx-software.com/2021/01/23/devebox-stm32h7-development-boards-are-made-for-factory-automation/

http://myosuploads3.banggood.com/products/20200410/20200410041012H750VI-.rar
http://myosuploads3.banggood.com/products/20200410/20200410034233H743VI-.rar

https://github.com/elzoughby/STM32H7xx-Startup

**Comment by ag88** [comment]
note that the variant made for WeAct MiniSTM32H743VITX would likely work for MCUDev DevEBox STM32H743VIT6
https://github.com/stm32duino/Arduino_Core_STM32/pull/1552
As it uses 25 Mhz HSE crystal same on both boards.
However, do note that the symbols LED_BUILTIN and USER_BTN are different between the 2 boards.
To use the WeAct variannt for MCUDev DevEBox STM32H743VIT6, avoid using the 2 symbols or re-define them in your arduino sketch. you could also simply clone the WeActH743VITX variant file and make mods locally e.g. make a new variant if you prefer.
