### ISSUE TITLE
[STM32F070]

### ISSUE THREAD

**Issue by alberiolima** [stm32duino/Arduino_Core_STM32#1146]
I tested it on the stm32F070 using the "STM32F030 DEMO BOARD", replacing the STM32F030F4P6 with an STM32F070F6P6. Apparently it works normally!

# DEMO_F070F6 board
GenF0.menu.pnum.DEMO_F070F6=STM32F070F6 Demo board
GenF0.menu.pnum.DEMO_F070F6.upload.maximum_data_size=6144
GenF0.menu.pnum.DEMO_F070F6.upload.maximum_size=32768
GenF0.menu.pnum.DEMO_F070F6.build.board=DEMO_F070F6
GenF0.menu.pnum.DEMO_F070F6.build.product_line=STM32F070x6
GenF0.menu.pnum.DEMO_F070F6.build.variant=DEMO_F030F4
![P_20200818_211935](https://user-images.githubusercontent.com/7103789/90578793-8e7d2200-e19a-11ea-9cd9-390fae5dd2b2.jpg)

**Comment by alberiolima** [comment]
now i will check pins and serial ports to modify "variants"

**Comment by fpistm** [comment]
Hi, thanks for the info.
I'm currently working to ease generic series/boards addition.

**Comment by fpistm** [comment]
Added to the new variant request list #722
