### ISSUE TITLE
[New Variant] add support for Nucleo64 STM32G070

### ISSUE THREAD

**Issue by AliBigdeli** [stm32duino/Arduino_Core_STM32#1147]
I have no idea why this board is not supported while in the main site clearly refrenced to being supported by arduino

 - Name: Nucleo64 STM32G070
 - Link to all relevant information:
   * Documentations : https://www.st.com/resource/en/user_manual/dm00452640-stm32-nucleo64-boards-with-stm32g07xrb-mcus-stmicroelectronics.pdf
   * Schematics :https://www.manualslib.com/manual/1529028/St-Stm32-Nucleo-64.html?page=11
   * Where this hardware can be purchased :https://www.st.com/en/evaluation-tools/nucleo-g070rb.html#:~:text=The%20STM32%20Nucleo%2D64%20boards,provided%20by%20the%20STM32%20microcontroller.

**Comment by fpistm** [comment]
Hi,

don't know which site you talk about. Only the Nucleo G071RB exists not the G070 one.

**Comment by fpistm** [comment]
Added to the new variant request list #722

**Comment by fpistm** [comment]
Implemented by #1745
