### ISSUE TITLE
[QUESTION] Assign SerialUSB to DEBUG_UART

### ISSUE THREAD

**Issue by rollback91** [stm32duino/Arduino_Core_STM32#1157]
Hello, as for the title, I would like to know if there was a way to assign the SerialUSB as the DEBUG_UART.

Thank you

**Comment by fpistm** [comment]
Hello @rollback91 
No, DEBUG_UART is linked to U(S)ART peripheral not USB and used by HardwareSerial class.
Goal is to be able to dump directly to the U(S)ART without any interrupt.

**Comment by rollback91** [comment]
Thanks for the reply @fpistm!
So, is it on the roadmap? If so,  are you able to estimate roughly when it should be available?

Thank you again! :)

**Comment by fpistm** [comment]
No this is not in the roadmap.

**Comment by rollback91** [comment]
Thanks again! closing the ticket!
