### ISSUE TITLE
Support for UART RX/TX level inversion on F3/F7 platforms

### ISSUE THREAD

**Issue by pawelsky** [stm32duino/Arduino_Core_STM32#1160]
Please add API in HardwareSerial class to enable/disable RX/TX level inversion for platforms that support it (e.g. F3 or F7)

This can be done e.g. by adding a inverse_logic parameter to the constructor (similarily to SoftwareSerial), and based on that configuring the AdvancedInit member of the UART_AdvFeatureInitTypeDef struct in uart_init function in the uart.c wrapper to something like:
```
    huart->AdvancedInit.AdvFeatureInit = UART_ADVFEATURE_TXINVERT_INIT | UART_ADVFEATURE_RXINVERT_INIT;
    huart->AdvancedInit.TxPinLevelInvert = UART_ADVFEATURE_TXINV_ENABLE;
    huart->AdvancedInit.RxPinLevelInvert = UART_ADVFEATURE_RXINV_ENABLE;
```

**Comment by babipsylon** [comment]
How to (un)invert on current firmware bf 4.16?

**Comment by fpistm** [comment]
Added to [U(S)ART] request list #1418
