### ISSUE TITLE
Print/Stream API is old. availableForWrite is missing

### ISSUE THREAD

**Issue by jandrassy** [stm32duino/Arduino_Core_STM32#1170]
this should be applied
https://github.com/arduino/ArduinoCore-API/pull/104

or this
https://github.com/arduino/ArduinoCore-samd/pull/254

**Comment by fpistm** [comment]
Hi @jandrassy 

Thanks for the API update.

Could you submit a PR for this ?

Thanks

**Comment by jandrassy** [comment]
> Hi @jandrassy
> 
> Thanks for the API update.
> 
> Could you submit a PR for this ?
> 
> Thanks

sorry, no. it is too much work. (I created this issue in 3 other cores too)
