### ISSUE TITLE
hardwareTimer updated function

### ISSUE THREAD

**Issue by mayurharge** [stm32duino/Arduino_Core_STM32#1185]
Hello,
This is more of a question than an issue.

I am using hardware timer code from example sketch [Link](https://github.com/stm32duino/STM32Examples/blob/master/examples/Peripherals/HardwareTimer/Timebase_callback/Timebase_callback.ino)
facing problem while initialisation of timer here `MyTim->attachInterrupt(Update_IT_callback);`
here in the core, this function is required `void Update_IT_callback ( HardwareTimer*) `as suggested by this error message `invalid conversion from 'void (*)()' to 'void (*)(HardwareTimer*)`

changing `void Update_IT_callback ( void) ` to `void Update_IT_callback ( HardwareTimer*)`  is solving my issue.

but please let em know that this fix is done in a proper way to avoid further issues in my code?
also please update the example code for better understanding of new function

thanks.

**Comment by fpistm** [comment]
Hi @mayurharge 

There is no issue with the example.
Since core version 1.9.0 this is the correct API:
https://github.com/stm32duino/Arduino_Core_STM32/pull/892
and the updated example:
https://github.com/stm32duino/STM32Examples/pull/23
