### ISSUE TITLE
Problems with linking DMA2D HAL Lib

### ISSUE THREAD

**Issue by tejonbiker** [stm32duino/Arduino_Core_STM32#1217]
Hi to all, I was playing with stm32duino with F7 device, everything was fine, until I try to optimize some graphics routines using ART Aceleration DMA2D, Actually HAL have some routines to deal with DMA2D but I'm not able to compile due to linking problems.

Looks like the compiler use the following sequence:

Look for the following object file:
"C:\\Users\\81589\\AppData\\Local\\Temp\\arduino_build_844262\\libraries\\SrcWrapper\\HAL\\stm32yyxx_hal_dma2d.c.o"

The source code of "stm32yyxx_hal_dma2d.c.o" is:
![image](https://user-images.githubusercontent.com/4304633/97068700-a48ad280-158f-11eb-93c2-d37812df01a1.png)

I think the problem is: the target of the object file is incorrect, I think recompile the file for F7 target will fix the problem, but I don't know how I can modify and run the compiler enviroment in Arduino and STM32Duino, any advice is welcome. 

To reproduce only try to compile the following sketch
(Select the board NucleoF767ZI with default settings, paste the following sketch) :
```
#include "stm32f7xx_hal_dma2d.h"
void setup() {
    DMA2D_HandleTypeDef hdma2d;
    HAL_DMA2D_Init(&hdma2d);
}
void loop() {}
```
Clic on build and the compiler will show a linking problem.

The expected behavior is compile without linking problems. 

![image](https://user-images.githubusercontent.com/4304633/97068252-a5ba0080-158b-11eb-9d13-f82c1c138ae5.png)

 - OS: Win 10, Home Edition, 64 bit. 
 - Arduino IDE version: 1.8.13
 - STM32 core version: 1.9.0
 - Upload method: STLink

**Board:
 - Name: Nucleo F767ZI

Thanks in advance.

**Comment by fpistm** [comment]
Hi @tejonbiker 

in fact you don't need to include the stm32f7xx_hal_dma2d.h it is automatically included.
You main issue is that the HAL DMA2D is not enabled, you have to enable it:
https://github.com/stm32duino/wiki/wiki/HAL-configuration#hal-modules-configuration

So simply add an `hal_conf_extra.h` with `#define HAL_DMA2D_MODULE_ENABLED` and this will build without any issue.
