### ISSUE TITLE
I2C needs to be reworked to use IT mode

### ISSUE THREAD

**Issue by fprwi6labs** [stm32duino/Arduino_Core_STM32#123]
The I2C layer needs some patches (twi.c in core):

- IRQHandler name do not match for F0 & L0
- ER_IRQn needs to be attached for all boards (except F0 & L0)
- Errors need to be taken account in master_read & master_write
- Error Callback must be reviewed to work in slave & master mode
- Other (to see)?

**Comment by fpistm** [comment]
Buffer size could be reviewed to avoid #120

**Comment by fpistm** [comment]
FYI: I've revert the commit which introduce I2C IT: 
https://github.com/stm32duino/Arduino_Core_STM32/commit/625fe2df7e67611fef9bf3e5a89a3265be7920c4

Let's reintroduced this thanks this issue solving.
