### ISSUE TITLE
Change program address 

### ISSUE THREAD

**Issue by thinhx2** [stm32duino/Arduino_Core_STM32#1239]
Hi , default program address of stm32f103 bluepill is 0x08000000, how i can change program address to 0x08001000? Thank mate

**Comment by fpistm** [comment]
Hi @thinhx2 
for question and support please use the forum: https:www.stm32duino.com

The flash offset is manage thanks the `VECT_TAB_OFFSET` definition.
For example for the BP it is defined if you select an upload method using a bootloader:
https://github.com/stm32duino/Arduino_Core_STM32/blob/caa8a28b281d14f91fbdda3744160fb5d40ca419/boards.txt#L1180-L1181
And the linker script use the value to define the `LD_FLASH_OFFSET={build.flash_offset}`
https://github.com/stm32duino/Arduino_Core_STM32/blob/caa8a28b281d14f91fbdda3744160fb5d40ca419/platform.txt#L41
https://github.com/stm32duino/Arduino_Core_STM32/blob/caa8a28b281d14f91fbdda3744160fb5d40ca419/variants/PILL_F103XX/ldscript.ld#L64
