### ISSUE TITLE
Nucleo 144 F722ZE

### ISSUE THREAD

**Issue by eloquentarduino** [stm32duino/Arduino_Core_STM32#1259]
- Name: Nucleo 144 STM32F722ZE
 - https://www.st.com/resource/en/user_manual/dm00244518-stm32-nucleo144-boards-mb1137-stmicroelectronics.pdf

I tried following the tutorial, but I cannot make it work on the pin mapping part.

**Comment by fpistm** [comment]
Hi @eloquentarduino 
Added to [New Variant] request list #722
