### ISSUE TITLE
NUCLEO-F413ZH

### ISSUE THREAD

**Issue by nmaas87** [stm32duino/Arduino_Core_STM32#1262]
Could you please add this board and also the "naked" STM32F413ZHT3?
Thank you :)

 - Name: NUCLEO-F413ZH
 - Link to all relevant information: https://www.st.com/en/evaluation-tools/nucleo-f413zh.html
   * Documentations: https://www.st.com/resource/en/user_manual/dm00244518-stm32-nucleo144-boards-mb1137-stmicroelectronics.pdf
   * Schematics: https://www.st.com/resource/en/schematic_pack/nucleo_144pins_sch.zip
   * Where this hardware can be purchased: RS Direct

**Comment by fpistm** [comment]
Added to [New Variant] request list #722
Thanks
