### ISSUE TITLE
serial error 

### ISSUE THREAD

**Issue by prashanthchinnu** [stm32duino/Arduino_Core_STM32#1264]
hi we are using serial2 for gsm communication we are getting compilation error let me know the solution asap

**Comment by fpistm** [comment]
Hi @prashanthchinnu 
claiming that a serial do not work is not an issue.
without more information we can't help as described in the GH issue template.
Which core version? Which Arduino IDE version? And mainly which board, configuration and sketch?

So I close this issue.
