### ISSUE TITLE
[New Variant] STM32H743VIT6 (and STM32H750VBT6)

### ISSUE THREAD

**Issue by rtek1000** [stm32duino/Arduino_Core_STM32#1266]
All info here: https://github.com/mcauser/MCUDEV_DEVEBOX_H7XX_M

![STM32H7XX_M](https://user-images.githubusercontent.com/8660811/102692283-1fb7e000-41f1-11eb-86ca-61d8be7eb335.jpg)

**Comment by rtek1000** [comment]
USD $23.00

https://pt.aliexpress.com/item/1005001543610862.html?spm=a2g0s.9042311.0.0.7edfb90aBErHQq

**Comment by rtek1000** [comment]
Note: Attention!!! Someone looking to use the STM32H7 for pins and high frequency output: The STM32H7 did only 20MHz (PA0) under the 480MHz clock. While the STM32F407VGT6 did 33MHz under the 168MHz clock.

**Comment by fpistm** [comment]
Added to the [New Variant] request list #722.

**Comment by ag88** [comment]
note that the variant made for WeAct MiniSTM32H743VITX would likely work for MCUDev DevEBox STM32H743VIT6
https://github.com/stm32duino/Arduino_Core_STM32/pull/1552
As it uses 25 Mhz HSE crystal same on both boards.
However, do note that the symbols LED_BUILTIN and USER_BTN are different between the 2 boards.
To use the WeAct variannt for MCUDev DevEBox STM32H743VIT6, avoid using the 2 symbols or re-define them in your arduino sketch. you could also simply clone the WeActH743VITX variant file and make mods locally e.g. make a new variant if you prefer.
