### ISSUE TITLE
SPI in transmit only mode

### ISSUE THREAD

**Issue by bluexp1** [stm32duino/Arduino_Core_STM32#1270]
Hi,
Is there a way I can use SPI in transmit only mode and use MISO pin for another functionality?

**Comment by fpistm** [comment]
Hi @bluexp1 
Happy new year.
I never tested. The SPI library is not designed for this as it initialize all SPI pins.
An other solution can be to emulate SPI by bitbanging.

Please, for such question use the forum: https://www.stm32duino.com
