### ISSUE TITLE
 error downloading  when using Board manager

### ISSUE THREAD

**Issue by bignest** [stm32duino/Arduino_Core_STM32#1275]
"error downloading https://github.com/stm32duino/BoardManagerFiles/raw/master/STM32/package_stm_index.json "
I am sure that the links to other boards can be used, such as esp8266 or esp32.
Everything was working before, but oneday all the STM32 boards were gone in the board manager , I was sure I had not upgraded the arduino IDE.
I tried a variety of methods, including proxy, changing the network. My classmate also had exactly the same problem. I think it is really a troublesome problem.

**Comment by fpistm** [comment]
Hi @bignest 
Unfortunately, I have no clue for you.
This relies on Arduino IDE and your network.
You should ask support to your ICT, probably they update the network config or change something else.
