### ISSUE TITLE
[New Variant] STM32F407ZGT6 - BIGTREETECH BTT SKR PRO V1.2

### ISSUE THREAD

**Issue by MetallianFR68** [stm32duino/Arduino_Core_STM32#1284]
**Board description (please complete the following information):**
 - Name: BIGTREETECH BTT SKR PRO V1.2
 - Link to all relevant information:
   * Documentations : https://github.com/bigtreetech/BIGTREETECH-SKR-PRO-V1.1/tree/master/SKR-PRO-V1.2/manual
   * Schematics : https://github.com/bigtreetech/BIGTREETECH-SKR-PRO-V1.1/tree/master/SKR-PRO-V1.2/Schematic
   * Where this hardware can be purchased : https://www.bigtree-tech.com/

Sorry I tried to do it myself but I didn't succeed

This board definition seems to be compatible with V1.1 and V1.2 of the board
https://github.com/bigtreetech/BIGTREETECH-SKR-PRO-V1.1/blob/master/firmware/SKR%20ProV1.1-Marlin_v2.0-Demo/buildroot/share/PlatformIO/boards/BigTree_SKR_Pro.json

They have a variant definition here :
https://github.com/bigtreetech/BIGTREETECH-SKR-PRO-V1.1/tree/master/firmware/SKR%20ProV1.1-Marlin_v2.0-Demo/buildroot/share/PlatformIO/variants/BIGTREE_SKR_PRO_1v1

**Comment by fpistm** [comment]
Hi @MetallianFR68 
I've added it to the [New Variant] request list #722
