### ISSUE TITLE
STM32L072CZ change CPU Frequency

### ISSUE THREAD

**Issue by fosses** [stm32duino/Arduino_Core_STM32#1299]
Hello, i am working in Low energy project with a Dragino LSN50v2 (STM32L072CZ + LoRa). I want to change the CPU frequency to 16 or 4 MHz to save energy while the CPU is running bot i don't find the way to do this. I am using the Arduino IDE 1.8.13 and de Arduino_Core_STM32 1.9.0 and the library "STM32 Low Power".

Regards

**Comment by fpistm** [comment]
Hi @fosses 
You already opened an issue on STM32Examples.
Please avoid duplicates issue moreover for such kind of request (support, question), use the forum: http://www.stm32duino.com
You would find several example how to do this:
https://www.stm32duino.com/viewtopic.php?p=4489#p4489
Thanks in advance.
