### ISSUE TITLE
Default servo angle on attach

### ISSUE THREAD

**Issue by Pararera** [stm32duino/Arduino_Core_STM32#1301]
Add parameter `angle` to function `attach`. `angle` parameter sets the angle of servo after attach.
This should work better than 

`Servo.attach();
Servo.write(defaultAngle);` 

Thanks

**Comment by fpistm** [comment]
Servo library follows the official Arduino Servo library API.
I don't think it will "work better", as the code is optimized by the toolchain. 
I let @ABOSTM comment on this.
