### ISSUE TITLE
variants/NUCLEO_F767ZI/variant.h seems incomplete

### ISSUE THREAD

**Issue by ZinggJM** [stm32duino/Arduino_Core_STM32#1302]
I get compile error when I try to use the pin name PD10 (e.g. in a list of FSMC data pins).
The Nucleo-144 STM32F767ZIT6 144 PINS has many more pins than available as names (#define) in variant.h
The Nucleo-144 STM32F746ZGT6 144 PINS seems to have these pins in variant.h (Morpho Pins).

**Comment by fpistm** [comment]
Hi @ZinggJM 
yes the variant has been added like this. This is not an issue.
Anyway I'm currently reworking the variant and all the pins will be available. See #1091
