### ISSUE TITLE
STM32WB55C BLE

### ISSUE THREAD

**Issue by Kamik18** [stm32duino/Arduino_Core_STM32#1305]
**Is your feature request/improvement related to a problem? Please describe.**
It is specified on the project home page that the P-Nucleo-WB55RG does not have BLE support.

**Describe the solution you'd like**
I would like to see Bluetooth or BLE library for the P-NUCLEO-WB55.

**Comment by fpistm** [comment]
Hi @Kamik18 
BLE will be supported in the next core release 2.0.0 and the next release of the STM32duinoBLE.
https://github.com/stm32duino/STM32duinoBLE/pull/17
