### ISSUE TITLE
STM32F1 UART TX idles after every byte

### ISSUE THREAD

**Issue by jlpoltrack** [stm32duino/Arduino_Core_STM32#1309]
**Describe the bug**
When using UART1 on STM32F1, TX seem to idle after every byte sent.  Don't expect this idle period. 

**To Reproduce**
Source from Arduino IDE:

```
void setup() {
  Serial.begin(1000000);
}

void loop() {
  Serial1.printf("Test");
  Serial1.flush();
  delay(100);
}
```

Screenshot from Scope:
[
![Capture_2021_02_24_18_50_39](https://user-images.githubusercontent.com/41841496/109084341-9ed80180-76d5-11eb-973c-b1fad6710af9.png)
](url)

**Expected behavior**
Expect to see continuous output from TX, such as:

![Capture_2021_02_24_19_02_24](https://user-images.githubusercontent.com/41841496/109084411-be6f2a00-76d5-11eb-8cab-899d02e9b2f2.png)

**Screenshots**
Screenshots above

**Desktop (please complete the following information):**
 - OS: Win 10
 - Arduino IDE version: 1.8.13
 - STM32 core version: 1.9.0
 - Tools menu settings if not the default: Default
 - Upload method: Serial

**Board (please complete the following information):**
 - Name: STM32F103C Blue Pill

**Comment by ABOSTM** [comment]
Hi @jlpoltrack,
As I understand, there is no real issue, you just don't get the full performances.
I don't consider this behavior has a bug, it works the way it has been implemented:
Current implementation send each bytes one by one, even if a multi character string is provided as argument.
And the consequence is that there is interrupt and CPU activity between each bytes (to prepare and send the next bytes).

Nevertheless, I agree that it is not really optimized.
This is why I propose a slightly different implementation in PR #1313

**Comment by jlpoltrack** [comment]
@ABOSTM 
Thanks for the response and explaining the current implementation.  As I didn't see this mentioned in the API documentation, thought I had something wrong with my setup.  I noticed when I saw a regression in packet size at higher UART speeds.  
I look forward to trying out the new implementation in the future.
