### ISSUE TITLE
[New Variant]

### ISSUE THREAD

**Issue by meold** [stm32duino/Arduino_Core_STM32#1314]
**Board description (please complete the following information):**
 - Name: STM32F411VET6
 - Link to all relevant information:
   https://www.st.com/en/microcontrollers-microprocessors/stm32f411ve.html
   https://www.tme.eu/Document/f397bb46203066b42d23d579456a2dc4/STM32F411CEU6.pdf

**Comment by fpistm** [comment]
Added to the [New Variant] request list #722
