### ISSUE TITLE
New version of Arduino-CLI does not accept pde file

### ISSUE THREAD

**Issue by SebCanet** [stm32duino/Arduino_Core_STM32#1319]
Hi,
using the last 0.16.1 version of arduino-cli, I have a debug information explaining that no more pde file are compatible. And some example still contain pde file.
So maybe you need to clean old example.
Regards.

**Comment by fpistm** [comment]
Hi @SebCanet 
in fact examples with pde extension comes from Arduino libraries.
Anyway I guess it could be changed to ino.

**Comment by SebCanet** [comment]
Yes, you're right. Sorry, in fact it's not a bug but information.
Thanks.

**Comment by fpistm** [comment]
We will update as stated below so I kept this issue opened to track 😉
