### ISSUE TITLE
STMLowpower doesn't work when compiled on Windows10 but does on Linux

### ISSUE THREAD

**Issue by haimiko** [stm32duino/Arduino_Core_STM32#1329]
Compiling the following deepsleep example, from STM32LowPower, on Windows 10 doesn't work but does on Linux.

For some reason when compiling on Win10, STM32 doesn't go to sleep but does when compiled on Ubuntu 20.04 LTS.  Logical conclusion is something with the toolchain.

```
/*
  TimedWakeup

  This sketch demonstrates the usage of Internal Interrupts to wakeup a chip
  in deep sleep mode.

  In this sketch, the internal RTC will wake up the processor every second.

  This example code is in the public domain.
*/

#include "STM32LowPower.h"

void setup() {
  pinMode(LED_BUILTIN, OUTPUT);
  // Configure low power
  LowPower.begin();
}

void loop() {
  digitalWrite(LED_BUILTIN, HIGH);
  LowPower.deepSleep(1000);
  digitalWrite(LED_BUILTIN, LOW);
  LowPower.deepSleep(1000);
}

```

**Comment by fpistm** [comment]
Hi @haimiko 
Please avoid to pen several issue in different repo for the same issue:
https://github.com/stm32duino/STM32LowPower/issues/53
