### ISSUE TITLE
Error: bad instruction `jmp 0x0000

### ISSUE THREAD

**Issue by whoim2** [stm32duino/Arduino_Core_STM32#1334]
AppData\Local\Temp\cciSyE3d.s:1449: Error: bad instruction `jmp 0x0000

bluepill (stm32f103cb) with maple bootloader 2.0
sketch: https://pastebin.com/pkH5PbSn

**Comment by fpistm** [comment]
Hi @whoim2 
what do you expect with this issue ?
I'm not aware of file named `cciSyE3d.s`  in this repo.
So if you do not explain more your issue as explained in the GitHub template it will be closed.

> **Please, before reporting any issue**
> - Make sure you are using the latest Arduino_Core_STM32 version.
>   https://github.com/stm32duino/Arduino_Core_STM32/releases/latest
> - Make sure the issue is not already reported/fixed on GitHub or discussed on the [stm32duino forum](http://stm32duino.com)
> - Submit a GitHub issue only for reporting a problem related to the [Arduino_Core_STM32](https://github.com/stm32duino/Arduino_Core_STM32).
> - **Avoid** to submit a GitHub issue for project troubleshooting.
>  
> Any questions/feedback/suggestions should be discussed on the [stm32duino forum](http://stm32duino.com):
>   * questions on the [STM32 Core](http://stm32duino.com/viewforum.php?f=35)
>   * bugs/enhancements on the [STM core: Bugs and enhancements](http://stm32duino.com/viewforum.php?f=38)
> 
> When reporting any issue, please try to provide all relevant information:
> 
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **To Reproduce**
> Complete source code which can be used to reproduce the issue. Please try to be as generic as possible (no extra code, extra hardware,...)
> 
> Steps to reproduce the behavior:
> 1. Plug
> 2. Press USER_BTN
> 3. See error
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
>  - OS: [e.g. Windows]
>  - Arduino IDE version: [e.g. 1.8.8]
>  - STM32 core version: [e.g. 1.4.0]
>  - Tools menu settings if not the default: [e.g. Newlib Standard, No Serial]
>  - Upload method: [e.g. STLink]
> 
> **Board (please complete the following information):**
>  - Name: [e.g. Nucleo F429ZI]
>  - Hardware Revision: [e.g. Rev B]
>  - Extra hardware used if any: [e.g. X-Nucleo IKS01A1]
> 
> **Additional context**
> Add any other context about the problem here.
