### ISSUE TITLE
Support communication LAN8720

### ISSUE THREAD

**Issue by Ddh012345dhD** [stm32duino/Arduino_Core_STM32#1346]
![image](https://user-images.githubusercontent.com/54657357/113023145-8c0e8c00-91af-11eb-8e45-6ac42e81617f.png)
How to fix this error?Help me!

**Comment by fpistm** [comment]
Hi @Ddh012345dhD 
Issue is not for support request. You can try to get some help on the forum.
Moreover, asking help by just providing a screenshot is probably not the best way to get help and by adding a tag which is not dedicated for this.  Your screenshot does not show the error message...
The GitHub issue template is quite detailed to at least take time to provide the requested information.

> **Please, before reporting any issue**
> - Make sure you are using the latest Arduino_Core_STM32 version.
>   https://github.com/stm32duino/Arduino_Core_STM32/releases/latest
> - Make sure the issue is not already reported/fixed on GitHub or discussed on the [stm32duino forum](http://stm32duino.com)
> - Submit a GitHub issue only for reporting a problem related to the [Arduino_Core_STM32](https://github.com/stm32duino/Arduino_Core_STM32).
> - **Avoid** to submit a GitHub issue for project troubleshooting.
>  
> Any questions/feedback/suggestions should be discussed on the [stm32duino forum](http://stm32duino.com):
>   * questions on the [STM32 Core](http://stm32duino.com/viewforum.php?f=35)
>   * bugs/enhancements on the [STM core: Bugs and enhancements](http://stm32duino.com/viewforum.php?f=38)
> 
> When reporting any issue, please try to provide all relevant information:
> 
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **To Reproduce**
> Complete source code which can be used to reproduce the issue. Please try to be as generic as possible (no extra code, extra hardware,...)
> 
> Steps to reproduce the behavior:
> 1. Plug
> 2. Press USER_BTN
> 3. See error
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
>  - OS: [e.g. Windows]
>  - Arduino IDE version: [e.g. 1.8.8]
>  - STM32 core version: [e.g. 1.4.0]
>  - Tools menu settings if not the default: [e.g. Newlib Standard, No Serial]
>  - Upload method: [e.g. STLink]
> 
> **Board (please complete the following information):**
>  - Name: [e.g. Nucleo F429ZI]
>  - Hardware Revision: [e.g. Rev B]
>  - Extra hardware used if any: [e.g. X-Nucleo IKS01A1]
> 
> **Additional context**
> Add any other context about the problem here.
`
