### ISSUE TITLE
Add board NUCLEO L412RB-P

### ISSUE THREAD

**Issue by GunZi200** [stm32duino/Arduino_Core_STM32#1350]
- Name: ST Nucleo L412RB-P
 - Link to all relevant information:
* https://www.st.com/en/evaluation-tools/nucleo-l412rb-p.html (Here you can find User manual, schematics)
* I bought it here: https://www.digikey.com/en/products/detail/stmicroelectronics/NUCLEO-L412RB-P/9656230

**Comment by GunZi200** [comment]
I would add it myself but saw in the issue template I should wait for v2.0.0

**Comment by fpistm** [comment]
Hi @GunZi200 
I've added this request to the new variant request list #722.
2.0.0 will come soon.
