### ISSUE TITLE
怎样加到arduino IDE里使用

### ISSUE THREAD

**Issue by wxbkool** [stm32duino/Arduino_Core_STM32#1353]
**Board description (please complete the following information):**
 - Name: [e.g. DISCOVERY F769NI]
 - Link to all relevant information:
   * Documentations
   * Schematics
   * Where this hardware can be purchased
  * ...

**Note that user can add a STM32 based board following this [wiki](https://github.com/stm32duino/wiki/wiki/Add-a-new-variant-(board))**

Any contribution is welcome, so do not hesitate to submit a PR.

All new variant request will be moved to [New Variant] request list #722 and the related issue will be closed.

**Comment by fpistm** [comment]
Hi @wxbkool 
Please avoid to open empty issue.
