### ISSUE TITLE
[New Variant] STM32F030K6

### ISSUE THREAD

**Issue by HamidSaffari** [stm32duino/Arduino_Core_STM32#1357]
![2019-03-06T15_12_48 294Z-2](https://user-images.githubusercontent.com/35362339/115119681-d7ea6f00-9fbe-11eb-80ab-f7902babb7a5.jpg)
from:
https://www.tindie.com/products/ra0sms/stm32f030k6-development-board/

and
![rSTM32F030K6T6 pinout](https://user-images.githubusercontent.com/35362339/115119684-dd47b980-9fbe-11eb-88ff-df71b07726e4.jpg)

from:
https://github.com/r-pv/STM32F030K6

# DEMO_F030K6 board
# Support: Serial1 (USART1 on PA3, PA2)
GenF0.menu.pnum.DEMO_F030K6=STM32F030K6 Demo board
GenF0.menu.pnum.DEMO_F030K6.upload.maximum_data_size=4096
GenF0.menu.pnum.DEMO_F030K6.upload.maximum_size=32768
GenF0.menu.pnum.DEMO_F030K6.build.mcu=cortex-m0
GenF0.menu.pnum.DEMO_F030K6.build.board=DEMO_F030K6
GenF0.menu.pnum.DEMO_F030K6.build.series=STM32F0xx
GenF0.menu.pnum.DEMO_F030K6.build.product_line=STM32F030x6
GenF0.menu.pnum.DEMO_F030K6.build.variant=DEMO_F030K6
GenF0.menu.pnum.DEMO_F030K6.build.cmsis_lib_gcc=arm_cortexM0l_math

**Comment by fpistm** [comment]
Added to [New Variant] request list #722
