### ISSUE TITLE
HardwareTimer clock running faster than configured.

### ISSUE THREAD

**Issue by Bambofy** [stm32duino/Arduino_Core_STM32#1366]
See topic here for details: https://www.stm32duino.com/viewtopic.php?f=62&t=1019

**Comment by ABOSTM** [comment]
Hi @Bambofy,
There is not need to open an issue in parallel of forum. It doesn't help nor fasten analysis,
and it make us loose time to check both (or worth we need to duplicate information).
So I close this issue and keep only the forum.
