### ISSUE TITLE
can still use Arduino_Core_STM32 version 1.9.0

### ISSUE THREAD

**Issue by rohitlucky** [stm32duino/Arduino_Core_STM32#1367]
hi
 can i still use Arduino_Core_STM32 version 1.9.0 if yes how

**Comment by fpistm** [comment]
Hi @rohitlucky 
please do not open issue for question. Use the forum https://www.stm32duino.com.

Of course you can continue to use 1.9.0. Simply kept your installation or install it using previous package index JSON file:
https://github.com/stm32duino/BoardManagerFiles/raw/master/STM32/package_stm_index.json

Even if it is mark deprecated it allows to install the 1.9.0 version.

But if you have any issue with it there will be no fix. The supported version is 2.0.0.
