### ISSUE TITLE
How to update platformIO to STM32duino v2.0?

### ISSUE THREAD

**Issue by yqboy** [stm32duino/Arduino_Core_STM32#1368]
I replaced framework-arduinoststm32 but it does not work

**Comment by fpistm** [comment]
Hy @yqboy 
Here it is for issue with the core with Arduino IDE not PIO.
The good issue is this one you already known:
https://github.com/platformio/platform-ststm32/issues/521

**Comment by yqboy** [comment]
thank you for your reply!!!
