### ISSUE TITLE
[2.0.0] STM32F072RB UART2 Output LOW, no signal, 1.9.0 normal

### ISSUE THREAD

**Issue by MINI-Qiang** [stm32duino/Arduino_Core_STM32#1370]
**Describe the bug**
STM32F072RB  UART2  invalid (PA3,PA2)   [default serial]  , Oscilloscope measurement PA3,PA2 output，（Output LOW, no signal）

 [1.9.0] is ok

**To Reproduce**
Test board: Nucleo-F072RB  

```c++
void setup()
{
  Serial2.begin(115200);
}

void loop()
{
  Serial2.println("1");
  delay(10);
}
``` 

1. updata
2. Oscilloscope measurement PA3,PA2 output，（Output LOW, no signal）

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows10]
 - Arduino IDE version: [1.8.12]
 - STM32 core version: [2.0.0]
 - Tools menu settings : nucleo64, NucleoF072RB  , default....
 - Upload method: [STLink]

**Board (please complete the following information):**
 - Name: [e.g. Nucleo F072RB]

**Comment by ABOSTM** [comment]
Hi @MINI-Qiang,
I tested your sketch on my Nucleo F072RB with core version 2.0.0, and it is working fine: "1" is repeatedly printed on serial monitor.
Please note that Arduino D0/D1 are NOT connected to PA3/PA2 by default so it is not possible to see the signal with Oscilloscope on D0/D1 by default.
See https://www.st.com/resource/en/user_manual/dm00105823-stm32-nucleo64-boards-mb1136-stmicroelectronics.pdf
SB62/SB63 are not present by default. 
But signal can be observed on STLINKJ part: CN3 connector RX.
Or you can change the solder bridge.
