### ISSUE TITLE
Typo: MAX_ADC_RESOLUTION should be MAX_PWM_RESOLUTION ?

### ISSUE THREAD

**Issue by AndrewBCN** [stm32duino/Arduino_Core_STM32#1378]
Hello, 
in source file:
https://github.com/stm32duino/Arduino_Core_STM32/blob/master/cores/arduino/wiring_analog.c

line 123
_internalWriteResolution = MAX_ADC_RESOLUTION;

should (?) be
_internalWriteResolution = MAX_PWM_RESOLUTION; 

since the max ADC resolution is irrelevant for the analogWrite function?

**Comment by fpistm** [comment]
Hi @AndrewBCN 
Yes you are right.
Thank you for spotting this 👍

**Comment by AndrewBCN** [comment]
Yes, I spotted this by chance, while looking at how to set PWM resolution to 16 bits (the default is 8 bits, as you know). And MAX_ADC_RESOLUTION is 12 bits for the STM32F411CEU6, so that was a problem for me.
