### ISSUE TITLE
SPI.transfer(...) hangs on Adafruit STM32F405 Feather

### ISSUE THREAD

**Issue by eLEcTRiCZiTy** [stm32duino/Arduino_Core_STM32#1388]
Hi,

when I create SPI instance (or use "SPI") and try to transfer something It hangs.. freeze.. or go to sleep forever :) It shouldn't.

Test rig:
OS: Windows 10
Board: Adafruit STM32F405 Express Feather (in Arduino IDE: Generic STM32F4 series -> Adafruit Feather ...)
IDE: Arduino 1.8.13 + STM32 core 2.0.0
Upload: DFU
Hardware: Short the MISO(MI) and MOSI(MO) pins
Software:
```
#include <SPI.h>

// settings for future application
SPISettings spiSettings(2e6, MSBFIRST, SPI_MODE3); // 2 MHz, mode 3

static const uint8_t MOSI_PIN = PB_15; //MO on board
static const uint8_t MISO_PIN = PB_14; //MI on board
static const uint8_t SCLK_PIN = PB_13; //SCK on board

SPIClass MySPI2(MOSI_PIN, MISO_PIN, SCLK_PIN); //I want to control CS pin on my own

int counter = 0;

void setup() {
  Serial.begin(115200);
  while (!Serial);
  Serial.println(F("Hello"));
  
  MySPI2.begin();
  Serial.println(F("SPI2 begin"));
}

void loop() {
  Serial.print("Loop count: ");
  Serial.println(counter);
  
  uint8_t test = MySPI2.transfer(0x0F);
  Serial.print(0x0F);
  Serial.print("=");
  Serial.println(test);
  
  delay(1000);
  counter += 1;
}
```

Program output (timestamps on; print only this and nothing more):
```
02:32:04.165 -> Hello
02:32:04.165 -> SPI2 begin
02:32:04.165 -> Loop count: 0

```

Program should count to "infinity" and print out something like:
```
Hello
SPI2 begin
Loop count: 0
15=15
Loop count: 1
15=15
Loop count: 2
15=15
...
```

**Comment by fpistm** [comment]
Hi @eLEcTRiCZiTy 

I've tested with the F405 feather and it works as expected..
First using default `SPI` instance (simply comment SPIClass MySPI2(...). and defined MySPI2 to SPI) .
As a second step I defined the MySPI2 like you but I've fixed pin declaration like this:
```
static const uint8_t MOSI_PIN = PB15; //MO on board
static const uint8_t MISO_PIN = PB14; //MI on board
static const uint8_t SCLK_PIN = PB13; //SCK on board
```

You used PinName (PY_n) notations while SPI requires pin Number (PYn).

Note that by default `SPI` instance used those pins so no need to create a new instance.
