### ISSUE TITLE
RAK811 crashes after 1 day of work

### ISSUE THREAD

**Issue by bioshock2k** [stm32duino/Arduino_Core_STM32#1396]
Hi,

I am using the RAK811 with STMduino and i am having some issues.
After more a less a day of working the RAK811 stopes working.
I am using  lmic.h and STM32LowPower.h to put the STM32 to sleep for 10min.

Is this a know issue?

**Comment by fpistm** [comment]
Hi @bioshock2k 

please, for this kind of question  use the forum: https://www.stm32duino.com

I do not have this board and never tested it.
