### ISSUE TITLE
ARDUINO_ARCH_STM32

### ISSUE THREAD

**Issue by Adminius** [stm32duino/Arduino_Core_STM32#14]
is it possilble to add general definition for all STM32 boards like **ARDUINO_ARCH_STM32**?
actualy i have to check for multiple boards: e.g. 
`#if defined(STM32F4xx) || defined(STM32F0xx) || defined(STM32F3xx)` and so on.

EDIT:
which architecture flag (eg. avr, sam, samd...) should i use to mark a libary (in library.properties) compatible with STM32 platform?

**Comment by fprwi6labs** [comment]
@Adminius you can use `architectures=stm32`.

**Comment by fpistm** [comment]
Is it ok @Adminius?

**Comment by Adminius** [comment]
yes. thx.
`#ifdef STM32` works also. 
`ARDUINO_ARCH_STM32` not needed any more.

**Comment by fpistm** [comment]
STM32 is not defined. (old stuff for firmata)
The good one is ARDUINO_ARCH_STM32
