### ISSUE TITLE
Replace round brackets in the "variants" folder

### ISSUE THREAD

**Issue by valeros** [stm32duino/Arduino_Core_STM32#1410]
Hi there,

**Is your feature request/improvement related to a problem? Please describe.**

In the latest core v2.0 the "variants" folder was refactored and grouped in sub-folders per series. Now, some internal variant folders might be common for several boards and contain round brackets `()` in their names (e.g. `F042C(4-6)(T-U)`). Even though such brackets are valid symbols and can be used for naming files and directories, Unix systems require such symbols to be quoted or escaped. With the Arduino IDE it works just fine as you simply quoted that paths in your `platform.txt`, but in case with PlatformIO it generates some considerable inconvenience as we need to properly handle such paths internally for many external tools like other editors (some IDEs need escaped symbols, other expect a raw path), static analysis tools, remote development, etc. 

**Describe the solution you'd like**
Although we understand that this matter should have been discussed early on the stage of development, it would be great to switch to something more regular for variant grouping, for example the most generic and OS-neutral alternatives are underscore `_`  and hyphen `-`.

Thanks in advance.

**Comment by fpistm** [comment]
Hi @valeros,
this notation was kept to be inline with the [STM32_open_pin_data(]https://github.com/STMicroelectronics/STM32_open_pin_data/tree/master/mcu) mcu file name.
It have been discussed a lot and tests as you stated it works with Arduino IDE (1.8.x and 2.0.0 Beta) but also with VScode for debugging. 
Usage of parenthesis is more readable for name factorization: `F042C(4-6)(T-U)` vs `F042C_4-6_T-U`
And factorization are required to avoid long name path issue.
Hyphen is already used.
So I really don't want change that.
