### ISSUE TITLE
Make I²C initialisation (Wire.begin()) not slow

### ISSUE THREAD

**Issue by matthijskooijman** [stm32duino/Arduino_Core_STM32#1449]
I'm running the Wire library on a G030 and noticed that initialization is super slow (`Wire.begin()` takes 800ms).

Digging into the code, I found [`i2c_computeTiming()`](https://github.com/stm32duino/Arduino_Core_STM32/blob/0686e2d5a873e16842e9f61dcb69fd095893e8f2/libraries/Wire/src/utility/twi.c#L390) that contains 5 (!) nested forloops and essentially seems to just bruteforce all possible timing combinations or something like that.

Note that I tested on an older version of the Wire library, but looking at the history of that file, I do not think this was fixed in the meanwhile.

**Describe the solution you'd like**

It seems like it should be possible to be smarter and also a *lot* faster about this.

**Comment by fpistm** [comment]
Hi @matthijskooijman 
Yes it is slow mainly on small device and it is mentioned in the Wiki:
https://github.com/stm32duino/wiki/wiki/Custom-definitions#i2c-timing
Simply define the I2C timing to avoid call this function as explained in the Wiki.
