### ISSUE TITLE
flash got slashed in half

### ISSUE THREAD

**Issue by LuaksCz** [stm32duino/Arduino_Core_STM32#1454]
Hello, i am using STM32F103C, programming via HID bootloader 2.2 
on win 10 with USB support "CDC general 'Serial' supercede.
When compiling arduino IDE shows maximum flash size as 32kb, while in datasheet it is 64kb, also i used diffrent core before, there the flash size was correct.

**Comment by JiriBilek** [comment]
Are you sure you have selected the correct _Board Part Number_ option? With "BluePill F103C8" compiles ok to 64K.

**Comment by LuaksCz** [comment]
Yes, thank you, didnt notice, that was it.

**Comment by ABOSTM** [comment]
So let's close this issue
