### ISSUE TITLE
Missing errata fix in stm32l4xx_hal_sd.c ?

### ISSUE THREAD

**Issue by Bambofy** [stm32duino/Arduino_Core_STM32#1458]
**Describe the bug**
The bug is that some SD cards will not initialize properly.

The bug is described the errata sheet at section 2.15.2 "Wrong CCRCFAIL status after a response without CRC is received" here https://www.st.com/resource/en/errata_sheet/es0388-stm32l452xx-device-errata-stmicroelectronics.pdf

The bug is described in a comment by "hpipon957" here https://community.st.com/s/question/0D50X00009XkZxJSAV/sd-card-on-sdio-command-response-fails-after-acmd-41

The bug occurs at this line of code https://github.com/stm32duino/Arduino_Core_STM32/blob/master/system/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_sd.c#L3546 according to the errata i believe this IF statement needs modifying.

**To Reproduce**
Connect a version 1.0 Sd card into an SDMMC slot on an STM32L452RE and attempt to use STM32SD to initialize it.

**Board (please complete the following information):**
 - Name: Nucleo-64

**Comment by Bambofy** [comment]
Found that it was just a broken SD card.

**Comment by fpistm** [comment]
Hi  @Bambofy 

The core uses only the HAL and avoid changes.
You should open an issue to the dedicated repository then you will have a feedback from ST HAL Team about this issue: https://github.com/STMicroelectronics/STM32CubeL4/issues
Then if a fix is made in a further release it will be integrated when the HAL driver will be updated in the core.
