### ISSUE TITLE
I2C doesn't work on STM32WL55CCU6 variant

### ISSUE THREAD

**Issue by Liars126** [stm32duino/Arduino_Core_STM32#1467]
Hello, I'm working with the [Generic Node](https://github.com/TheThingsIndustries/generic-node-se) board. This board implements an STM32WL55CCU6 and for that reason I'm trying to used the Arduino_STM32_Core #1459  where the variant has been modified to use Generic Node board with Arduino.

The prooblem comes when I'm trying to scan the integrated sensors on board by using I2C_scanner and it detect nothing, just put on serial port that there's an error on some address and finally _no I2C devices detected._ I check the variant an there's seems to be nothing worng on it about pin declaration, also I'm put in HIGH the _LS1_SENSORS_EN_ so all the sensors on board can be ON. 

About the I2C_scanner.ino here's a preview of the firmware

```
#include <Wire.h>

//TwoWire Wire2(PA10, PA9);


void setup() {
pinMode(24, OUTPUT);
  
  Serial.begin(115200);
   //I2C-1
  Wire.setSDA(PA10);
  Wire.setSCL(PA9);
  //I2C-2
 // Wire.setSDA(PA11);
  //Wire.setSCL(PA12);

  Wire.begin();
  digitalWrite(24, HIGH);
  Serial.println("\nI2C Scanner");
}

void loop() {
  byte error, address;
  int nDevices;

  Serial.println("Scanning...");

  nDevices = 0;
  for(address = 1; address < 127; address++) {
    Wire.beginTransmission(address);
    error = Wire.endTransmission();
    
    if (error == 0) {
      Serial.print("I2C device found at address 0x");
      if (address < 16) 
        Serial.print("0");
      Serial.println(address, HEX);

      nDevices++;
    }
    else if (error == 4) {
      Serial.print("Unknown error at address 0x");
      if (address < 16) 
        Serial.print("0");
      Serial.println(address, HEX);
    }    
  }
  if (nDevices == 0)
    Serial.println("No I2C devices found");
  else
    Serial.println("done");

  delay(10000);
}
```

Im working with @sabas1080

**Comment by fpistm** [comment]
Hi @Liars126 
I saw your commit on the PR and this is not correct.
I will review and fix it.
Please avoid to open an issue for code in a PR. This duplicate discussion.
