### ISSUE TITLE
Missing STM32_Programmer.sh dependency.

### ISSUE THREAD

**Issue by zfields** [stm32duino/Arduino_Core_STM32#1478]
**Describe the bug**
When I attempt to deploy, the logs tell me `STM32_Programmer.sh not found.`

```
An error occurred while uploading the sketch
STM32_Programmer.sh not found.
Please install it or add '<STM32CubeProgrammer path>/bin' to your PATH environment:
https://www.st.com/en/development-tools/stm32cubeprog.html
Aborting!
```

1. Compile `Blink` example sketch
2. Attempt to flash device
3. See error

**Expected behavior**
I expect the BSP to provide the necessary utilities for me to program my board from the Arduino IDE.

**Desktop (please complete the following information):**
 - OS: Pop_OS! 20.04
 - Arduino IDE version: 1.8.13
 - STM32 core version: 2.0.0
 - Upload method: Tried all options with the same result.

**Board (please complete the following information):**
 - Name: STM32L4

**Comment by fpistm** [comment]
Hi @zfields 
Unfortunately, I could not provide the STM32CubeProgrammer belong to Arduino.
As stated by the log you have to install it on your side. 
And also in the Wiki:
https://github.com/stm32duino/wiki/wiki/Upload-methods#requirement
