### ISSUE TITLE
HardwareTimer lacks a function to check if it's running or not

### ISSUE THREAD

**Issue by positron96** [stm32duino/Arduino_Core_STM32#1525]
There are functions to pause/resume the timer, but there is no way to check if it's running or not. 

Right now one needs to take a HAL structure and check if the required bit is set.

Would be good to have such a function (for the entire timer and maybe for each channel).

**Comment by ABOSTM** [comment]
@positron96 ,
Can you please review the proposed Pull Request #1550 
and tell me whether it matches your expectations ?

**Comment by positron96** [comment]
Thanks! The PR sems to be doing exactly what I need.

**Comment by fpistm** [comment]
Thank you @positron96 for the quick feedback. PR merged.

**Comment by positron96** [comment]
Great! When is it expected to hit platformio registry?

**Comment by fpistm** [comment]
Well, don't know. we do not manage this. PIO will probably update after the next release.
