### ISSUE TITLE
I2C broken on STM32F4 since IT mode used

### ISSUE THREAD

**Issue by fpistm** [stm32duino/Arduino_Core_STM32#153]
Since the I2C IT mode is used #135, I2C tests with STM32 F4 based boards are broken.
(reproduced on several boards: 429ZI, 401RE, 411RE).
Seems the write operation do not end properly: ACK failed.
Changing the timing change the error occurrences.

Blocke for next release.

**Comment by cparata** [comment]
Hi all,
[this](https://github.com/stm32duino/Arduino_Core_STM32/pull/155) PR should fix this issue.
Best Regards,
Carlo
