### ISSUE TITLE
basic Arduino library "MIDIUSB" is not supported on stm32

### ISSUE THREAD

**Issue by jpnielsen** [stm32duino/Arduino_Core_STM32#1533]
I have the Nucleo-144 STM32H743ZI (and the Daisy board (STM32H750) and some STM32F103 and STM32F405 boards bought on aliexpress).

I would like to use arduino to program it to perform MIDI over USB - and do some 16 bit ADC of inputs coming through multiplexers (74HC4067) and i2c communication to SSD1309 OLEDs and MCP23017 I/O expanders. All software and hardware is going to be available as open source and presented in an educational context.

However, the nescessary, basic Arduino library "MIDIUSB" is not supported on stm32.
https://www.arduino.cc/en/Reference/MIDIUSB

```
WARNING: library MIDIUSB claims to run on avr, sam, samd architecture(s) and may be incompatible with your current board which runs on stm32 architecture(s).
In file included from F:\Arduino\portable\sketchbook\libraries\MIDIUSB\examples\MIDIUSB_write\MIDIUSB_write.ino:9:
F:\Arduino\portable\sketchbook\libraries\MIDIUSB\src/MIDIUSB.h:78:2: error: #error "Unsupported architecture"
   78 | #error "Unsupported architecture"
      |  ^~~~~
exit status 1
Error compiling for board Nucleo-144.
```

Is it possible that ST Microelectronic will make MIDIUSB run on it's Discovery/Nucleo boards (if technically possible)?

Thank you

**Comment by fpistm** [comment]
Hi,

added to [USB] Features request list #687
