### ISSUE TITLE
Error 503 Backend.max_conn reached

### ISSUE THREAD

**Issue by chetan1836** [stm32duino/Arduino_Core_STM32#1543]
When I try to download the version 2.1.0 I'm getting the below error in Board manager in Arduino IDE. Any solutions?

**Error 503 Backend.max_conn reached**

**Backend.max_conn reached**
**Guru Mediation:**

**Details: cache-hyd1100032-HYD 1636641585 1199651273**

**Varnish cache server**

**Comment by fpistm** [comment]
Seems to be an Arduino IDE error or Github one. Not link to the core.

**Comment by fpistm** [comment]
Searching your error drive me here:
https://www.section.io/blog/varnish-cache-503-error-guru-meditation/

As stated it is not link to the core. You can try to clear the Arduino package index cache.
But I could not help more.
