### ISSUE TITLE
genericSTM32F030C8 undefined reference to `Serial1'

### ISSUE THREAD

**Issue by zll900720** [stm32duino/Arduino_Core_STM32#1607]
#include <Arduino.h>

#define LED PC13

void setup()
{
  pinMode(LED, OUTPUT);
  Serial1.begin(115200);
  Serial2.begin(115200);
}

void loop()
{
  Serial1.println("hello world1");
  Serial2.println("hello world2");
  digitalWrite(LED, HIGH);
  delay(500);
  digitalWrite(LED, LOW);
  delay(500);
}

Processing genericSTM32F030C8 (platform: ststm32; board: genericSTM32F030C8; framework: arduino)
--------------------------------------------------------------------------------------------------------------------------------------------Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/ststm32/genericSTM32F030C8.html
PLATFORM: ST STM32 (15.1.0) > STM32F030C8 (8k RAM. 64k Flash)
HARDWARE: STM32F030C8T6 48MHz, 8KB RAM, 64KB Flash
DEBUG: Current (blackmagic) External (blackmagic, cmsis-dap, jlink, stlink)
PACKAGES:
 - framework-arduinoststm32 4.20100.211028 (2.1.0)
 - framework-cmsis 2.50700.210515 (5.7.0)
 - toolchain-gccarmnoneeabi 1.90201.191206 (9.2.1)
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 11 compatible libraries
Scanning dependencies...
No dependencies
Building in release mode
Linking .pio\build\genericSTM32F030C8\firmware.elf
c:/users/zhuliangliang/.platformio/packages/toolchain-gccarmnoneeabi@1.90201.191206/bin/../lib/gcc/arm-none-eabi/9.2.1/../../../../arm-none-eabi/bin/ld.exe: .pio/build/genericSTM32F030C8/src/main.cpp.o: in function `setup':
main.cpp:(.text.setup+0x24): undefined reference to `Serial1'
c:/users/zhuliangliang/.platformio/packages/toolchain-gccarmnoneeabi@1.90201.191206/bin/../lib/gcc/arm-none-eabi/9.2.1/../../../../arm-none-eabi/bin/ld.exe: .pio/build/genericSTM32F030C8/src/main.cpp.o: in function `loop':
main.cpp:(.text.loop+0x38): undefined reference to `Serial1'
collect2.exe: error: ld returned 1 exit status
*** [.pio\build\genericSTM32F030C8\firmware.elf] Error 1

**Comment by fpistm** [comment]
It is normal as only one default instance are defined:
https://github.com/stm32duino/Arduino_Core_STM32/blob/b192e502227c809c925b0338073f9f6e5175ca05/variants/STM32F0xx/F030C8T/variant_generic.h#L124

See https://github.com/stm32duino/wiki/wiki/API#hardwareserial
