### ISSUE TITLE
STM32L151RCT6

### ISSUE THREAD

**Issue by slavendam** [stm32duino/Arduino_Core_STM32#1608]
Hi, can anyone confirm is this board supported STM32L151RCT6?
I see it is not written, but did anyone try to use it?

Thanks :)

**Comment by fpistm** [comment]
Hi @slavendam 

This boards is currently not declared. You can try to add it following the wiki:
https://github.com/stm32duino/wiki/wiki/Add-a-new-variant-%28board%29

Added to https://github.com/stm32duino/Arduino_Core_STM32/issues/722
