### ISSUE TITLE
Disable (-Wunused-parameter) on F4 series 

### ISSUE THREAD

**Issue by DanielHaubjergVestergaard** [stm32duino/Arduino_Core_STM32#1610]
When "Compiler warnings" is set to "ALL" there will be a warning on the F4 series.

Drivers / STM32F4xx_HAL_Driver / Inc / stm32f4xx_ll_adc.h: In function 'uint32_t LL_ADC_DMA_GetRegAddr (ADC_TypeDef *, uint32_t)':
Drivers / STM32F4xx_HAL_Driver / Inc / stm32f4xx_ll_adc.h: 1881: 76: warning: unused parameter 'Register' [-Wunused-parameter]

Drivers / STM32F4xx_HAL_Driver / Inc / stm32f4xx_ll_adc.h: In function 'uint32_t LL_ADC_IsActiveFlag_MST_EOCS (ADC_Common_TypeDef *)':
Drivers / STM32F4xx_HAL_Driver / Inc / stm32f4xx_ll_adc.h: 4396: 75: warning: unused parameter 'ADCxy_COMMON' [-Wunused-parameter]

This is not a problem in itself, but would be good if they were disabled.

This does not occur on F1 & L4 series

This has been tested with Core version 2.2.0, with (Example Blink) and Arduino 1.8.19

**Comment by fpistm** [comment]
Hi @DanielHaubjergVestergaard 

We know those warnings. HAL and LL comes from the official STM32Cube release: https://github.com/STMicroelectronics/STM32CubeF4

STM32 core simply use it without any modification.
To avoid such warning with the core we used some pragma directive:
https://github.com/stm32duino/Arduino_Core_STM32/blob/b192e502227c809c925b0338073f9f6e5175ca05/cores/arduino/stm32/LL/stm32yyxx_ll_adc.h#L3-L6

but in some case it is not enough as headers are direcly included from source file.
The best way to remove them are to fix them within the official release then we will have the fix here when we will update.
I know some action are on going on each STM32Cube to solve those errors but can't tell you more. 
You can open an issue on the official repo to track this.
