### ISSUE TITLE
LoRa Support for STM32WL55JC

### ISSUE THREAD

**Issue by HelgeSeidel** [stm32duino/Arduino_Core_STM32#1614]
The Arduino Core for STM32 V2.1.0 does not support LoRa features for the STM32WL55JC.

I would appreciate if the LoRa support could be added to the Arduino Core for the  STM32WL55JC.

**Comment by fpistm** [comment]
Hi @HelgeSeidel 

we currently study this but I can't do any commitment on this at this time.

**Comment by sheggy012** [comment]
Do I understand correctly that Lora is not possible even in combination with other libraries, like Radiolib?

**Comment by fpistm** [comment]
Hi,
LoRaWAN support is available here:
https://github.com/stm32duino/STM32LoRaWAN

Soon STM32WL support in Radiolib shouldbe available.
See: https://github.com/jgromes/RadioLib/issues/588

So I close this issue.
