### ISSUE TITLE
PWM on STM32F030F4P6 Demo Board does not work on all possible pins.

### ISSUE THREAD

**Issue by evil-gears** [stm32duino/Arduino_Core_STM32#1619]
Hello, after testing in two different STM32F030F4P6 Demo boards, it seems that analogWrite() is only supported on pins PA4 (LED1), PA6, PA7 and PB1. The pins PA0, PA1, PA2, PA3 and PA5 all behave like digital outputs (0 - 127 = LOW, 128 - 255 = HIGH). I got the board reference from [this](https://github.com/stm32duino/Arduino_Core_STM32/issues/165) issue, where I found this image:
![STM32F030F4P6 Pinout](https://user-images.githubusercontent.com/20950920/48310324-4927cb80-e596-11e8-9a11-e4650a2e0309.jpg)
**STM32duino core**: Latest
**Programmer**: ST-LINK V2
**IDE**: Arduino 1.8.19

One of the boards was hooked to my circuit, and the other one was tested outside the circuit using a multimeter.

**Comment by fpistm** [comment]
Hi @JeanHenriqueAlves 
Seems normal if I refers to the TIM arra:
https://github.com/stm32duino/Arduino_Core_STM32/blob/a531c22091fb372a8c06b47c0b9dbdd6860c98e0/variants/STM32F0xx/F030F4P/PeripheralPins.c#L70-L85

**Comment by fpistm** [comment]
And datasheet confirm this
![Screenshot_20220113-195210_Drive](https://user-images.githubusercontent.com/20641798/149391649-187522ca-fd34-428a-847b-c2e93b26be2d.jpg)
