### ISSUE TITLE
Error regarding some missing header file

### ISSUE THREAD

**Issue by nicksterious** [stm32duino/Arduino_Core_STM32#1673]
**Describe the bug**

I am trying to compile a simple sketch:

```
void setup() {
  pinMode(PB_7, OUTPUT);
}

void loop() {
  digitalWrite(PB_7, HIGH);         // turn the LED on 
  delay(250);                       // wait for 1/4 s
  digitalWrite(PB_7, LOW);          // turn the LED off 
  delay(2000);                       // wait for 2s
}
```

And I get this output:

```
<command-line>: fatal error: variant_BLACK_F407VX.h: No such file or directory
compilation terminated.

Compilation error: exit status 1
```

I have **not** selected a F407 board anywhere at all.

**To Reproduce**

1. Select the Generic STM32F4 board
2. Select board part number Generic STM32F439ZIT
3. Try compiling a simple sketch

**Expected behavior**
Sketch should compile without error.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Arduino IDE version: 2.0.0rc4
 - STM32 core version: 2.2.0
 - Upload method: onboard STLink

**Board (please complete the following information):**
 - Name: Nucleo-144 STM32F439ZI

**Additional context**
I had to select a Generic STM32F4 series board and board part number Generic STM32F439ZI since there's no variant for Nucleo-144 with this MCU

This bug is not present with STM32 core v 2.1.0

**Comment by fpistm** [comment]
Hi @nicksterious 

I've tested with Arduino 1.8.19 and Arduino IDE 2.0.0 RC4 without any error.
I think it is an issue with the IDE. I saw several strange behaviour using it. It is a RC after all.
You should file an issue in the IDE. Or you can try to reinstall the core maybe it was not properly installed and some files are missing but not link to the core itself.

About your sketch, pay attention you used `PB_7` which is a pinName while you have to use pin number `PB7`.
