### ISSUE TITLE
Tools Dependencie xpack-arm-none-eabi-gcc version 10.3.1-2.3 does not exist

### ISSUE THREAD

**Issue by jfm-made** [stm32duino/Arduino_Core_STM32#1682]
**Describe the bug**
toolsDependencie xpack-arm-none-eabi-gcc version 10.3.1-2.3 does not exist.

**To Reproduce**
Add "https://github.com/stm32duino/BoardManagerFiles/raw/main/package_stmicroelectronics_index.json" to Arduino IDE board manager urls.
Install version 2.2.0 with the Arduino IDE. It will fail downloading xpack-arm-none-eabi-gcc version 10.3.1-2.3 with status 404.

**Expected behavior**
An existing version of xpack-arm-none-eabi-gcc is downloaded.

**Screenshots**
![bug-0](https://user-images.githubusercontent.com/23073123/159993135-b63d3a4a-b2f4-4d49-b719-b37515d8c6b9.PNG)

**Desktop:**
 - OS: Windows x64 (Tested also on Intel Mac and Apple Silicon, with latest version of Arduino IDE)
 - Arduino IDE version: 1.8.10

**Comment by fpistm** [comment]
Hi,
It should be fixed. See https://github.com/xpack-dev-tools/arm-none-eabi-gcc-xpack/issues/17.

Hope sha256 is the same.

**Comment by JoanMCD** [comment]
The URL is still not working.

**Comment by fpistm** [comment]
> 

I've tested and it works:
https://github.com/xpack-dev-tools/arm-none-eabi-gcc-xpack/releases/download/v10.3.1-2.3/xpack-arm-none-eabi-gcc-10.3.1-2.3-win32-ia32.zip

Maybe Arduino cache issue or proxy

**Comment by JoanMCD** [comment]
I reflect to this URL: "https://github.com/stm32duino/BoardManagerFiles/raw/main/package_stmicroelectronics_index.json"
Ending with .json and needed in the Arduino IDE

**Comment by fpistm** [comment]
I don't understand your previous comment. The json  file is the entry point then depending of the version you installed you get list of files to download. The xpack one was removed by mistake by the owner and it is now available.

**Comment by JoanMCD** [comment]
Yes - but the json isn't available -> click it.

**Comment by fpistm** [comment]
> Yes - but the json isn't available -> click it.

It is available. Moreover your point concern a package reference in this json. 
When I click on your link it appears properly.

**Comment by JoanMCD** [comment]
Oh? Yes you're right. Checked it by VPN and it's working. Hipee :)
 Sorry for interrupting and thank you for your time. It must be a local problem on my side. 
regards Joan
