### ISSUE TITLE
Ethernet support

### ISSUE THREAD

**Issue by sstaub** [stm32duino/Arduino_Core_STM32#169]
Can you add native Ethernet support for Nucleo-F429TI and 32F746G-Dicovery.
I would nice if the API works like the Ethernet library for the Wiznet Ethernet Shields.
I have done an advanced API for the Wiznet W5500, see [https://github.com/sstaub/Ethernet3](url)

**Comment by fpistm** [comment]
Hi @sstaub,

it is already added thanks:
https://github.com/stm32duino/STM32Ethernet
https://github.com/stm32duino/LwIP
available thanks the Arduino Library manager.

**Comment by sstaub** [comment]
Thank you, that's cool.
