### ISSUE TITLE
__HAL_AFIO_REMAP_SWJ_ENABLE(); definition for L1 and F3

### ISSUE THREAD

**Issue by Hoel** [stm32duino/Arduino_Core_STM32#172]
where is the definition of __HAL_AFIO_REMAP_SWJ_ENABLE for L1 and L3, i see it for F1 only.

**Comment by fpistm** [comment]
Hi @Hoel ,
This macro is only defined for F1. Alternate Function is different for F1.
For other series, I think it is it is GPIO_AF0_SWJ

**Comment by Hoel** [comment]
ok thank you, my bad
