### ISSUE TITLE
RTC Library for Arduino_Core_STM32

### ISSUE THREAD

**Issue by mayukhIITD** [stm32duino/Arduino_Core_STM32#173]
Can you please let me know if you have any RTC library for the STM32 core which can access the on board RTC of L476RG board? Something similar to RTC.h used by grumpyoldpizza core (https://github.com/GrumpyOldPizza/arduino-STM32L4/tree/master/libraries/RTC) ??

Thanks,
Mayukh,
IIT Delhi, India

**Comment by fpistm** [comment]
Hi @mayukhIITD 
One will come soon:
https://github.com/stm32duino/STM32RTC
