### ISSUE TITLE
Why is itoa.h missing in the includes and thus disabling use of utoa() function?

### ISSUE THREAD

**Issue by ArminJo** [stm32duino/Arduino_Core_STM32#1785]
I am using FQBN: stm32duino:STM32F1:genericSTM32F103C

**Using utoa(aNumber, tStringBuffer, 10); throws error: 'utoa' was not declared in this scope**
When I add a line `#include "itoa.h"` in wirish.h
```
#include <avr/interrupt.h>
#include "itoa.h"

#include <libmaple/stm32.h>
```
the error vanishes.

Pull request required?

**Comment by fpistm** [comment]
Hi,
Based on #1786 and your code: 
`#include <libmaple/stm32.h>`
you used this core: https://github.com/rogerclarkmelbourne/Arduino_STM32/
not this one.

**Comment by ArminJo** [comment]
Sorry again.
