### ISSUE TITLE
New variant STM32F303CCT6 / USB VCP 

### ISSUE THREAD

**Issue by Hoel** [stm32duino/Arduino_Core_STM32#180]
Hello,
I am writing new variants definitions for boards we make and i would like to know how to get the USB serial (USB VCP) working for them, at first STM32F303CC later STM32F103L151C8, STM32F103CB, STM32F411CE, STM32L476RG. 
Apparently some rework has been ongoing on USB VCP for STM32F103CB (bluepill) few month ago and bluepill will be part of the next release, _is it posible to get bluepill variant files so i can start from this for USB VCP on STM32F303CC?_
Thanks

EDIT: i found the branch with bluepill variant [https://github.com/fpistm/Arduino_Core_STM32/tree/STM32F1_merge_Other]
With bluepill, selecting CDC throws the error `This board does not support (yet?) USB CDC!`

I put together the USB folder for my target using files from a working STM32CubeMX USB VCP project for STM32F303CC, unfortunately it still throws `This board does not support (yet?) USB CDC!`, i presume something has to be changed in my variant definition. How to enable CDC support in boards.txt? Aything else I should modify in the USB folder for F303CC?

**Comment by fpistm** [comment]
Hi, 
since this PR core has got lot of change. So, I doubt it is compatible. I have to rebase it properly.

**Comment by Hoel** [comment]
Hi, thanks for the confirmation. Sadly serial over USB doesnt work either on the bluepill F103 and maple mini variants from your repo. 
This fork https://github.com/danieleff/STM32GENERIC/issues/52 has the USB working for F103, i cannot get it to work for F303 either.

**Comment by Hoel** [comment]
The problem is now solved, i used a fork of this repo https://github.com/huaweiwx/STM32GENERIC  USB virtual serial works on the F303
