### ISSUE TITLE
STM32 Black Pill (F401 CC)

### ISSUE THREAD

**Issue by MussabMehboob** [stm32duino/Arduino_Core_STM32#1800]
When I connect by Black Pill it is not detected (even the drivers are installed). When I take the board in DFU MODE by pressing boot ,rst and releasing them in the device manager there is unrecognized device showed. I have attached the screen shots. When I try to upload the simple Blink Sketch it gives me error and don't get uploaded
I have attached two images showing my issue. Let me know if there is something wrong with my board so is it the issue of the software? Thanking in anticipation.
<img width="960" alt="2" src="https://user-images.githubusercontent.com/99961872/184472670-b33c18ea-6e57-4638-96a1-6d06962c5560.PNG">
<img width="586" alt="1" src="https://user-images.githubusercontent.com/99961872/184472702-fb62b001-59b6-4f3e-9fde-2c5e151cb4cd.PNG">

.

**Comment by fpistm** [comment]
Hi @MussabMehboob 
it seems you have a bootloader installed on your board and it is not the default built-in bootloader.
I know some blackpill are sold with a default bootloader.
You should erase it using an STLink and the STM32CubeProgrammer.
Or simply see if vendor provide support for this.
