### ISSUE TITLE
Code not compiling if there is a space in the link

### ISSUE THREAD

**Issue by codejunkes** [stm32duino/Arduino_Core_STM32#1829]
I am using STM32 MCU based boards by STMicroelectronics version 2.3.0.

the code failed to compile as the compiler cannot resolve a link with spaces in it.

Error in Arduino:
arm-none-eabi-g++: error: lab\AppData\Local\Arduino15\packages\STMicroelectronics\hardware\stm32\2.3.0=.: No such file or directory
exit status 1
Error compiling for board Generic STM32F4 series.

The link to the hardware files is "C:\Users\pqm lab\AppData\Local\Arduino15\packages\STMicroelectronics\hardware\stm32\2.3.0", but it is unable to take the space in the user name "pqm lab".

**Comment by fpistm** [comment]
Hi, it is already know and fixed thanks #1759 

Fix will be available in the 2.40 release.
Simply replace `C:\Users\pqm lab\AppData\Local\Arduino15\packages\STMicroelectronics\hardware\stm32\2.3.0\system\extras\prebuild.sh` by this file while 2.4.0 is not released:
https://github.com/stm32duino/Arduino_Core_STM32/blob/main/system/extras/prebuild.sh
