### ISSUE TITLE
Problem for firmware upload on Discovery board B-U585I-IOT02A : wrong mass storage name

### ISSUE THREAD

**Issue by Yannick-Marietti** [stm32duino/Arduino_Core_STM32#1849]
When my Discovery B-U585I-IOT02A board is connected to my Windows 11 PC through ST_LINK, I can see its mass storage is named "DIS_U585AI".

Arduino IDE fails to upload compiled firmware inside it as it expect a mass storage named "NOD_U585AI".

**Comment by fpistm** [comment]
Hi  @Yannick-Marietti 
and thanks for the issue.
It seems new STLink firmware changes the name of the mass storage for this board.
@gautierg-st will add the new name.
