### ISSUE TITLE
Debugging stm32duino code

### ISSUE THREAD

**Issue by mayukhIITD** [stm32duino/Arduino_Core_STM32#185]
Is there any way I can debug STM32DUINO code for Nucleo 64 boards? Arduino IDE does not support debugging. Is there any other way to do it?

Thanks,
Mayukh

**Comment by fpistm** [comment]
Hi @mayukhIITD,
On Linux OS you could use arm gdb to debug (using texane stlink). For other OS. I know some people use Eclipse with Sloeber plugin but I've never use it.

**Comment by fpistm** [comment]
To complete the answer you could have a look in this section of the stm32duino.com forum:
http://stm32duino.com/viewforum.php?f=41
They are several topics around other IDE with debugging capabilities.
