### ISSUE TITLE
Can not set the SCB->VTOR sucessfully?

### ISSUE THREAD

**Issue by KiraVerSace** [stm32duino/Arduino_Core_STM32#1858]
It still can't solve this problem after a few days of attempts.
I want to use IAP function in my code.
0x08000000   30K     for the bootloader
0x08007800   226K   for the user application
1. First I modified the ld file as follows:

```
MEMORY
{
  RAM     (xrw)     : ORIGIN = 0x20000000,   LENGTH = LD_MAX_DATA_SIZE
  RAM2    (xrw)     : ORIGIN = 0x10000000,   LENGTH = 32K
  FLASH   (rx)      : ORIGIN = 0x8007800,    LENGTH = 226K
}
```

2. I modified the platformio.ini

```
build_flags = 
-DVECT_TAB_OFFSET=0x00007800
board_upload.offset_address = 0x08007800
```

3. I use the SEGGER Jlink JFlash to download the program,  I use it to download the Bootloader and it succeed, then I use platformIO download the Application.

No  matter how many times I try, the bootloader program still can not jump into user application, but I use the program that complied under the KEIL, it can succeed, So I can eusure that the bootloader is right, I doubt whether I missing some settings in stm32duino, or there some bugs?

Please help  me, thank you very much

**Comment by fpistm** [comment]
Which mcu?

**Comment by KiraVerSace** [comment]
> Which mcu?

MCU: STM32L476RCT6
ENV: VSCODE+PLATFORMIO+Frame(Arduino)+MacOS

**Comment by fpistm** [comment]
If `VECT_TAB_OFFSET` is set then it should be ok
https://github.com/stm32duino/Arduino_Core_STM32/blob/4e9dae5c87b5f5331545b02c0fa51d97228e4a37/system/STM32L4xx/system_stm32l4xx.c#L121-L124

and `SCB->VTOR` properly set:
https://github.com/stm32duino/Arduino_Core_STM32/blob/main/system/STM32L4xx/system_stm32l4xx.c#L191

I do not use PIO as we only support Arduino IDE. With Arduino IDE it works. So no more clue for you except check if PIO redefinition are properly take into account.

**Comment by KiraVerSace** [comment]
> If `VECT_TAB_OFFSET` is set then it should be ok
> 
> https://github.com/stm32duino/Arduino_Core_STM32/blob/4e9dae5c87b5f5331545b02c0fa51d97228e4a37/system/STM32L4xx/system_stm32l4xx.c#L121-L124
> 
> and `SCB->VTOR` properly set: https://github.com/stm32duino/Arduino_Core_STM32/blob/main/system/STM32L4xx/system_stm32l4xx.c#L191
> 
> I do not use PIO as we only support Arduino IDE. With Arduino IDE it works. So no more clue for you except check if PIO redefinition are properly take into account.

Thank you for your help, I find that the SCB->VTOR is unset after I download my application, as flow
<img width="776" alt="image" src="https://user-images.githubusercontent.com/55439370/199682734-538ddb03-7c43-4e14-9714-3630ec8a1408.png">
it still 0x08000000, so I try debug my program, I step into the SystemInit,and I see SCB->VTOR is set to 0x08007800, and my program can run, but If I reset my mcu, it first run the bootloader, the 0xE000ED08(
SCB->VTOR ) will not change, i do not know why,
my program use the stm32duino freeRTOS.

**Comment by KiraVerSace** [comment]
but as you see, I have set the offset in the ini file, and debug can succeed, but jump failed
![image](https://user-images.githubusercontent.com/55439370/199694126-7f4a39ec-beab-4a5a-b220-dda64f5deef8.png)
I  can not figure out the reason, if the application complie in KEIL  it can succeed.

**Comment by fpistm** [comment]
redefining `VECT_TAB_OFFSET` allows to redefine VTOR at the proper address when your application start but if your application does not start it is not set.
The upload offset is just to properly set where to flash and avoid write on your BL.

If keil succeed to start maybe it do some stuff to tell where to start. As stated when you flash 2 options:
1- board is reset (reboot) then BL have to jump at the correct @ 
2- the flash tools request to start at specific @ (jump) without reboot.

I could not help more on this as I have no more clue and relies to PIO.

**Comment by KiraVerSace** [comment]
I had sloved the problem, as the link.
[PlatformIO Community](https://community.platformio.org/t/how-to-iap-in-stm32-correctly-there-is-some-problems/30276/4)

**Comment by fpistm** [comment]
> I had sloved the problem, as the link. [PlatformIO Community](https://community.platformio.org/t/how-to-iap-in-stm32-correctly-there-is-some-problems/30276/4)

Thanks for the feedback.
