### ISSUE TITLE
USB Keyboard not working and USB device not recognized on bluepill.

### ISSUE THREAD

**Issue by zyppx** [stm32duino/Arduino_Core_STM32#1861]
- Arduino_Core_STM32 version：2.3.0
- Arduino IDE 1.8.19
- STM32F103C8T6 BLUEPILL 

> I compiled the [Keyboard  example](https://github.com/stm32duino/Arduino_Core_STM32/blob/main/libraries/Keyboard/examples/KeyboardMessage/KeyboardMessage.ino), but USB device not recognized .
> 
> ![A](https://user-images.githubusercontent.com/116325599/200463621-9bf001f5-b3ac-4e8a-bc52-84791774e5ba.png)
> 
> I can't find any help in issuse to make it work.
> 
> What should I do to make it work?

**Comment by fpistm** [comment]
Hi @zyppx 
There are a lot of fake bluepill and even not a fake several has hardware issue with USB. You should search on the forum about this and get some advice to fix it.

**Comment by JiriBilek** [comment]
First, check https://stm32duinoforum.com/forum/wiki_subdomain/index_title_Blue_Pill.html#Hardware_installation
