### ISSUE TITLE
stm32 with arduino Error compiling for board

### ISSUE THREAD

**Issue by robot78p** [stm32duino/Arduino_Core_STM32#1869]
i install Arduino  try with all versions
i install library too
https://raw.githubusercontent.com/stm32duino/BoardManagerFiles/main/package_stmicroelectronics_index.json
when try to loade code on STM32 Nucleo board getting error
STM32F401RE

**Comment by fpistm** [comment]
Issue malformed. Not enough information.
CI build is OK.
