### ISSUE TITLE
Leafony STM32 

### ISSUE THREAD

**Issue by masa6372** [stm32duino/Arduino_Core_STM32#1887]
Name: Leafony STM32
Document: https://docs.leafony.com/en/docs/leaf/processor/ap03/
Schematics: https://github.com/Leafony/HW-Design-Files/blob/master/AP03_STM32_MCU/AP03_STM32_MCU_Schematic.pdf
Where can be purchased: https://shop.leafony.com/en/collections/products/products/basic-kit-2

**Comment by fpistm** [comment]
Related to https://www.stm32duino.com/viewtopic.php?t=1785

Added to  [New Variant] request list #722 
Feel free to contribute and submit PR to add it. 
To add a STM32 based board follows this [wiki](https://github.com/stm32duino/wiki/wiki/Add-a-new-variant-(board))

**Comment by masa6372** [comment]
Hi, I'm wondering how to add a variant. Does it automatically created, or do we have to create it by following the wiki?

**Comment by fpistm** [comment]
Some files already exists:
https://github.com/stm32duino/Arduino_Core_STM32/tree/main/variants/STM32L4xx/L452RC(I-T-Y)_L452RE(I-T-Y)x(P)_L462RE(I-T-Y)
You have to  add your own variant_*.* which describe your board then declare it to the boards.txt.
If you can start to define the pin mapping and I will try to help you to finish the variant.

**Comment by masa6372** [comment]
Thanks！ 
I've added variant_LEAFONY_STM32.cpp and variant_LEAFONY_STM32.h. 
[https://github.com/Leafony/Arduino_Core_STM32/tree/main/variants/STM32L4xx/Leafony_STM32](url)

Can you tell where to modify?

**Comment by fpistm** [comment]
@masa6372 
I've made the variant update:
https://github.com/stm32duino/Arduino_Core_STM32/pull/1889

Please, Could you review and test it?

**Comment by masa6372** [comment]
LGTM!
