### ISSUE TITLE
Stm32f412zg support

### ISSUE THREAD

**Issue by Emirgkts** [stm32duino/Arduino_Core_STM32#1899]
How about stm32f412zg

**Comment by fpistm** [comment]
Hi,
added to new variant request list #722 

Base generated file available here:
https://github.com/stm32duino/Arduino_Core_STM32/tree/main/variants/STM32F4xx/F412Z(E-G)(J-T)

Feel free to add the generic support following the [wiki](https://github.com/stm32duino/wiki/wiki/Add-a-new-variant-(board))
