### ISSUE TITLE
Generic L4P5AGIxP

### ISSUE THREAD

**Issue by federicaventriglia** [stm32duino/Arduino_Core_STM32#1905]
- **Name**: Generic STM32L4P5AGIxP
 - Link to all relevant information:
   * **Documentations**: https://www.st.com/en/microcontrollers-microprocessors/stm32l4p5ag.html 
   * **Schematics**: https://www.st.com/resource/en/reference_manual/rm0432-stm32l4-series-advanced-armbased-32bit-mcus-stmicroelectronics.pdf 
   * Where this hardware can be **purchased**: https://www.digikey.ie/en/product-highlight/s/stmicroelectronics/stm32l4p5-ultra-low-power-32-bit-mcus 
  * Used as MCU for *STM32L4P5 Discovery kit*

**Comment by fpistm** [comment]
Added to #722
