### ISSUE TITLE
Allow to specify mass storage transfer for generic boards

### ISSUE THREAD

**Issue by nils-van-zuijlen** [stm32duino/Arduino_Core_STM32#1923]
**Is your feature request/improvement related to a problem? Please describe.**

I have a Nucleo32 F303RE that is not yet a supported board, but has a supported processor. I would like to be able to flash it via mass storage as I could do if I had a supported board.

**Describe the solution you'd like**

Selecting "Generic F3" -> F303RETx I would have the option to choose "Mass Storage" as upload method.

I would then be able to select the storage device for the board to flash, in the same way I can select a port for Arduino boards.

**Describe alternatives you've considered**

Integrating each Nucleo board so that all boards are covered. Keeping up with the releases would be hard.

**Comment by fpistm** [comment]
Hi @nils-van-zuijlen 
Mass storage is part of the STLink firmware. As you used a Nucleo, you can use the SWD.
Generic target have to be as generic as possible and so adding a mass storage option is not a good approach as you have to know the mass storage name and it is linked to a specific board.
Best way would be to add the Nucleo board definition.

An other way  is to define (extend) it yourself as explained here: https://github.com/stm32duino/wiki/wiki/Custom-board-based-on-a-core
