### ISSUE TITLE
Implement USBSerial baud/stopbits/partitytype/numbits getter methods 

### ISSUE THREAD

**Issue by mkals** [stm32duino/Arduino_Core_STM32#1935]
It would be great to have the USBSerial getter methods for baud, stopbits, partitytype and numbits implemented. 

I'm using a F4 chip as a USB-to-tty converter, and by having these implemented, I'm hoping it would be possible to have the converter mirror the settings used by the computer for the DUT. 

[See code here.](https://github.com/stm32duino/Arduino_Core_STM32/blob/1357c085354dff1048fb9e396740a81b32813223/cores/arduino/USBSerial.cpp#L161)

I have done a bit of searching, but not been able to find any information on how to do this with the HAL functionality.

**Comment by fpistm** [comment]
FOr USB CDC, Those parameters have no effects.
API are provided for compatibility with Serial API.
 And don't think we can get host config value nor the interest of those value on device side.
