### ISSUE TITLE
Uploads to Nucleo boards on MacOS 13.1 fail 

### ISSUE THREAD

**Issue by smcharg** [stm32duino/Arduino_Core_STM32#1953]
Under MacOS 13.1 (Ventura) the macosx/massStorageCopy.sh script fails to detect the Nucleo device when mounted.  This is due to the output from the "df -Hl" command used by the script no longer reporting the device, for example:

df -Hl
Filesystem       Size   Used  Avail Capacity  iused      ifree %iused  Mounted on
/dev/disk1s5s1   500G    12G    56G    18%   348618  548377440    0%   /
/dev/disk1s2     500G   3.4G    56G     6%     1652  548377440    0%   /System/Volumes/Preboot
/dev/disk1s4     500G   2.1G    56G     4%        2  548377440    0%   /System/Volumes/VM
/dev/disk1s6     500G    60M    56G     1%      650  548377440    0%   /System/Volumes/Update
/dev/disk1s1     500G   424G    56G    89%  3074033  548377440    1%   /System/Volumes/Data
/dev/disk1s5     500G    12G    56G    18%   348576  548377440    0%   /System/Volumes/Update/mnt1
/dev/disk2s2     5.0T   2.5T   2.5T    50% 17130817 4277836462    0%   /Volumes/SG_5TB#2

Using "df -Ha" does report the device (last in the output below):

df -Ha
Filesystem                  Size   Used  Avail Capacity  iused      ifree %iused  Mounted on
/dev/disk1s5s1              500G    12G    56G    18%   348618  548345480    0%   /
devfs                       206k   206k     0B   100%      702          0  100%   /dev
/dev/disk1s2                500G   3.4G    56G     6%     1652  548345480    0%   /System/Volumes/Preboot
/dev/disk1s4                500G   2.1G    56G     4%        2  548345480    0%   /System/Volumes/VM
/dev/disk1s6                500G    60M    56G     1%      650  548345480    0%   /System/Volumes/Update
/dev/disk1s1                500G   424G    56G    89%  3074033  548345480    1%   /System/Volumes/Data
map auto_home                 0B     0B     0B   100%        0          0  100%   /System/Volumes/Data/home
/dev/disk1s5                500G    12G    56G    18%   348576  548345480    0%   /System/Volumes/Update/mnt1
/dev/disk2s2                5.0T   2.5T   2.5T    50% 17130817 4277836462    0%   /Volumes/SG_5TB#2
msdos://disk3/NODE_F303RE   557k    29k   528k     6%        1          0  100%   /Volumes/NODE_F303RE

With the result the script can detect the device and properly perform the upload.

Arduino STM32 MCU based boards 2.4.0
Arduino IDE 2.0.3
MacOS 13.1

**Comment by fpistm** [comment]
Hi,
this issue has already been reported and fixed. 
It is linked to update of coreutils on Mac OS.
https://github.com/stm32duino/Arduino_Tools/pull/86

Fixed will be available within the next release.
