### ISSUE TITLE
[Feature request] rosserial_arduino for Arduino_Core_STM32

### ISSUE THREAD

**Issue by nopnop2002** [stm32duino/Arduino_Core_STM32#1956]
**Describe the solution you'd like**

I want rosserial_arduino_lib available with this core library

**Comment by fpistm** [comment]
Hi,
I guess this is this lib:
https://github.com/frankjoshua/rosserial_arduino_lib

If the lib uses standard arduino API it should works else you will have to modify it or request to their repo to support stm32  core.
Here it is for core issue.

**Comment by nopnop2002** [comment]
The library you pointed to, which is detailed here, may depend on rogerclarkmelbourne's core.

http://wiki.ros.org/rosserial_arduino

**Comment by nopnop2002** [comment]
Adding this line made it work.

Serial1 is used as the serial object.

TX=PA9/RX=PA10 for BluePill and BlackPill.


```
Adding this line made it work.
```
