### ISSUE TITLE
STM32H747XI or Portenta H7

### ISSUE THREAD

**Issue by sabas1080** [stm32duino/Arduino_Core_STM32#1984]
**Board description (please complete the following information):**
 - Name: Portenta H7 o Portenta Lite H7
 - Link to all relevant information: https://store-usa.arduino.cc/products/portenta-h7?selectedStore=us

I can help to test, since I have hardware, thanks

**Comment by fpistm** [comment]
Added to #722

**Comment by fpistm** [comment]
Hi @sabas1080 
Just a thought but I guess using the official Arduino core will provide best support of the board as it is dedicated to it. 😉
