### ISSUE TITLE
Can the 485 chip flow control function be added?

### ISSUE THREAD

**Issue by ShiPC123** [stm32duino/Arduino_Core_STM32#2019]
In industrial control, it is often necessary to use the 485,485 chip for half duplex control, receiving and sending depends on the 485 DE pin, high power usually for sending mode, low power usually for receiving mode. Can you add the following functions to the code: When the TXD is sending data over a serial port, one I/O of the MCU changes to the high level and automatically changes to the low level after the TXD is sent

**Comment by fpistm** [comment]
Hi @ShiPC123 
could you be more precise on this request? which chip? ....
