### ISSUE TITLE
I2C: extEEPROM test failed on Nucleo L152RE

### ISSUE THREAD

**Issue by fpistm** [stm32duino/Arduino_Core_STM32#203]
Since this #135, extEEPROM test failed on Nucleo L152RE

**Comment by fpistm** [comment]
Will be covered by #217

**Comment by LMESTM** [comment]
@fpistm few observations:
* I reproduced the issue of eeprom test failing with L152RE
* if using a digital probe to debug, the problem disappear ...  hmmm
 * if changing timing setting from I2C_DUTYCYCLE_2 to I2C_DUTYCYCLE_16_9 it works fine as well ...
to be continued
