### ISSUE TITLE
STM32H743IIT6 Flash Size Error

### ISSUE THREAD

**Issue by Mobin-Mortazavi** [stm32duino/Arduino_Core_STM32#2040]
### Discussed in https://github.com/stm32duino/Arduino_Core_STM32/discussions/2039

<div type='discussions-op-text'>

<sup>Originally posted by **Mobin-Mortazavi** June 13, 2023</sup>
I wrote a code that easily fits in STM32F103RET6 that has only 512KB of flash , But when I use same arrays in the STM32H743IIT6 it says :
" sketch_jun12b.ino.elf section `.rodata' will not fit in region `FLASH' "
and also :
" arm-none-eabi/bin/ld.exe: region `FLASH' overflowed by 32888 bytes "

when I reduce Array size a little bit , it says that my code only took 6% of the Flash 

My array is a 480*72 uint16 image in the flash , Like this :

const uint16_t image[34560] PROGMEM</div>

**Comment by fpistm** [comment]
Hi @Mobin-Mortazavi 
Please, avoid to open issue and discussion.
