### ISSUE TITLE
PVD not working in Arduino framework using HAL libraries

### ISSUE THREAD

**Issue by Khelicon** [stm32duino/Arduino_Core_STM32#2041]
I am trying to enable PVD feature in STM32G071 MCU to save the values to EEPROM. This is avoid flash memory wearing out due to continue write operation to Flash memory.  (I have device stop working after couple of months, and it seems writing to Flash every minute was the main reason).

So, I decided to enable PVD feature in Arduino framework using HAL libraries as I did not find any example to save on power failure using BOR or PVD.

I tested the **following PVD_init() code in STM32Cube framework and it works fine** but when the same code is added to STM32 Arduino framework, I don't see any interrupt triggered on power failure. 

```
#include "Arduino.h"
#include "EEPROM.h"

int pvdAddr = 0;
volatile count = 0;

void PVD_IRQHandler()
{ 
        EEPROM.write(pvdAddr, count); 
} 

/*
  * @brief  setup and start Power Voltage Detector interrupt 
 */

PWR_PVDTypeDef sConfigPVD;
void PVD_Init(void) {
 
	__HAL_RCC_PWR_CLK_ENABLE();

	HAL_PWR_EnablePVD();  //Enable PVD

	//2. Configure the NVIC for PVD
	HAL_NVIC_SetPriority(PVD_IRQn, 0, 0);
	HAL_NVIC_EnableIRQ(PVD_IRQn);

	// Configure the PVD Level to 2.9V for
	sConfigPVD.PVDLevel = PWR_PVDLEVEL_5;
	sConfigPVD.Mode = PWR_MODE_IT_RISING_FALLING;
	HAL_PWR_PVDConfig(&sConfigPVD);

       // added in Arduino framework
       attachInterrupt(PVD_IRQn, PVD_IRQHandler, CHANGE);  
  
}
// ============== Arduino specific ================
void Setup()
{
  Serial.begin(115200);
  PVD_Init();
  count = EEPROM.read(pvdAddr);
  Serial.printf("\nCount: ", count);
}

void loop()
{
   delay(1000);
   Serial.printf("\nCount: ", count++);
}
//=====================================
```

Is there any chance we can have this feature enabled, as this will be very useful for the applications that requires device to restore the state after power failure. 

Thank you.

**Comment by fpistm** [comment]
Hi @Khelicon 
ino sketch are converted as cpp file and so the IRQ handler have to be prefixed by extern "C" to avoid decoration which prevent its call from HAL C.
`extern "C" void PVD_IRQHandler()`
