### ISSUE TITLE
Generic L4 variants disable SWD debugging without any notice

### ISSUE THREAD

**Issue by fronders** [stm32duino/Arduino_Core_STM32#2047]
I have a custom STM32L486-based board and wanted to debug via SWD using ST-Link V3.
So I'm using release 2.5.0 and selected `Generic STM32L4 series` with board PN `Generic STM32L486RGTx` and the following options:
![image](https://github.com/stm32duino/Arduino_Core_STM32/assets/15352046/27761178-e1bb-4ae5-9f3c-898a939f08e3)

So the code uploads okay, but the debugging session would not start. After hours of battling with openocd configs and trying multiple different options I discovered it can only connect after chip was previously erased. This made me wonder if SWD pins might be disabled. 

I checked variant's `PeriperalPins.c`

https://github.com/stm32duino/Arduino_Core_STM32/blob/fa8f7b8568e2b6a5f1b5a471cb491276bcb50440/variants/STM32L4xx/L475V(C-E-G)T_L476V(C-E-G)T_L486VGT/PeripheralPins.c#L398-L411

`PA_13` is initialized there, which kills the debugging ability.
As soon as I redefined this PinMap as a _strong_ in my sketch with that line definitions commented out
```c
//   {PA_13, USB_OTG_FS, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF10_OTG_FS)}, // USB_OTG_FS_NOE
```
debugging started working like a charm!

Would it be better to define those pins overridden if needed explicitly? Like, wrap it in an `ifdef` for example when debug symbols are enabled, or smth similar. Also please advise on the best solution in my case. I can keep the redefined `PinMap_USB_OTG_FS[]`, or even create my own board variant, but the fact that this isn't mentioned anywhere and I had to kill like a day for finding this, is certainly discouraging.
Thanks

**Comment by fpistm** [comment]
Hi @fronders 
Sorry for that, generic provide all possibles values and those files are automatically generated.
With STM32 there are several possibilities for pins and hard to fit/guess what user want. You used the correct way by redefining the PinMap array, that is why it is defined as WEAK.
Maybe a note could be added in the FAQ section of the Wiki.

**Comment by fpistm** [comment]
I've added a debug section to the FAQ:
https://github.com/stm32duino/Arduino_Core_STM32/wiki/FAQ#debug
