### ISSUE TITLE
I2C SDA line stuck low after requestFrom with more than 1 byte - No I2C Stop sequence generated

### ISSUE THREAD

**Issue by yec23** [stm32duino/Arduino_Core_STM32#2064]
**Describe the bug**
I2C SDA line stuck low after requestFrom with **more than 1 byte**. Master seems to not generate the I2C Stop sequence.
Same result in normal or fast mode.
Working ok when requesting 1 byte
Same hardware and code run well when compiled with Roger Clark environment on Arduino IDE 1.8 Linux.

**To Reproduce**
- Wire.requestFrom with two bytes or more return ok but SDA remains low.  Adding stop parameter (true) has same behaviour (argument defaulted to true)
- I2C Registers after begin() and before requestFrom() call:
CR1: 1
CR2: 0x24
SR1: 0
SR2: 0
After  requestFrom() call:
CR1: 0xA01 => POS and STOP set
CR2: 0x424 => ITBUFEN set
SR1: 0x240 => ARLO and RxNE set
SR2: 2 => BUSY set
- Successive requestFrom then end in error. 
- Only a end() and begin() resume I2C state.

**Steps to reproduce the behaviour:**
see code attached
[Sourcecode.txt](https://github.com/stm32duino/Arduino_Core_STM32/files/12014817/Sourcecode.txt)

**Screenshots**
With Arduino Core STM32: **no I2C STOP generated**
![image](https://github.com/stm32duino/Arduino_Core_STM32/assets/139227232/67824182-e447-4d95-bee4-1e091de2bc47)

With Roger Clark, I2C STOP generated
![image](https://github.com/stm32duino/Arduino_Core_STM32/assets/139227232/d7179df5-008c-4743-bcd6-56498fb84b46)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Arduino IDE version: 2.1.0
 - STM32 core version: 2.6.0
 - Tools menu settings if not the default: USB support: CDC (generic serial supersede U(S)Art), U(S)ART support Enable (generic serial) 
 - Upload method: SWD

**Board (please complete the following information):**
 - Name: Blue PillF103CB 128k
 - Extra hardware used if any: MPU-6050 slave

**Additional context**
First version of the project was implemented with Roger Clarck STM32 environment. Project is being migrated to Arduino Core STM32 before implementing new features.

**Comment by fpistm** [comment]
Hi @yec23 
Thanks for this detailed report. Unfortunately, we do not have the MPU-6050 slave so we can't reproduce.
Could you provide an example without usage of external device?

Note: I guess you have PU resistors on each I2C lines?

**Comment by yec23** [comment]
Hi and thank you for your answer. 

Do you expect the Wire library example "master_reader_writer" ?  Tell me.
I would be surprised it does not work as it comes with the Core and was, I guess tested Ok. 

I don't have external resistors. Setup proved to be fine when compiled with RC so I concluded I did not have to investigate further this possibility. Isn’t it a good enough prove that the issue is not coming from that area? 

Thanks again for your help.

**Comment by yec23** [comment]
Can I provide you with GPIOB->CRH:  0x4444DD44, 
Mode10:  01b => Output mode, max speed 10 MHz
CNF10 : 11b => Alternate function output Open-drain
Mode11:  01b => Output mode, max speed 10 MHz
CNF11 : 11b => Alternate function output Open-drain

**Comment by fpistm** [comment]
You can add this to your sketch to enable internal PU (https://github.com/stm32duino/Arduino_Core_STM32/wiki/Custom-definitions#custom-pinmap-array):

```
const PinMap PinMap_I2C_SDA[] = {
  {PB_11, I2C2, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, AFIO_NONE)},
  {NC,    NP,   0}
};

const PinMap PinMap_I2C_SCL[] = {
  {PB_10, I2C2, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, AFIO_NONE)},
  {NC,    NP,   0}
};

```

**Comment by yec23** [comment]
Hi, I've added the two variables declaration. Result is the same: SDA low after requestFrom call. 
GPIOB->CRH: changed to 0x44449944: CNF 10 and 11 = 10b. MODE remaining 01b

**Comment by fpistm** [comment]
I have no more insight. Or maybe related to stretch feature anyway as I can not reproduce I could not help more.

**Comment by yec23** [comment]
1: Put 4.7K resitors in place of 2K
2: Change code to use STM_MODE_AF_OD
Still facing the issue.

Could you clarify following point : when in Master Receiver mode,  STM32F103xx RM008 describes two methods
Do you confirm the Core uses Method 2. i.e. "Interruption Mode" ? Is there a way to use Method 1 i.e. "Blocking mode" ?

**Comment by brightproject** [comment]
Just the other day I updated the core, and the `MPU9250` [stopped](https://github.com/sparkfun/SparkFun_MPU-9250-DMP_Arduino_Library/issues/53) working.

**Comment by fpistm** [comment]
I got an MPU 6050 and test your code and see no issue.
I've also tested with https://github.com/electroniccats/mpu6050 and it works as expected.

**Comment by brightproject** [comment]
> I got an MPU 6050 and test your code and see no issue.

If you have data in the fields of the magnetometer, then you have not `6500`, but `9250`.

**Comment by fpistm** [comment]
> > I got an MPU 6050 and test your code and see no issue.
> 
> If you have data in the fields of the magnetometer, then you have not `6500`, but `9250`.

I told 6050 not 6500...

**Comment by brightproject** [comment]
> I told 6050 not 6500...

I overlooked ... I didn’t think at all that there was a 6050.

**Comment by yec23** [comment]
@fpistm thank you for your additional tests and feedback. Sorry for the long answer.

I performed same tests and in addition IMU_Zero.ino example from MPU6050 library. I faced the same issue with the Core. I also did the tests with a new blue pill and a new MPU-6050 ([ITG-MPU](https://fr.aliexpress.com/item/1005001621877471.html?spm=a2g0o.productlist.main.1.c8a0494e0mwzdY&algo_pvid=5dc1e894-ae6f-4a11-a514-1c9f28b36312&aem_p4p_detail=202307210718405499537816860850000244012&algo_exp_id=5dc1e894-ae6f-4a11-a514-1c9f28b36312-0&pdp_npi=3%40dis%21EUR%211.42%211.16%21%21%211.54%21%21%402100b20d16899491203666817d0732%2112000016846829096%21sea%21FR%210&curPageLogUid=MoWqjKbvT09t&search_p4p_id=202307210718405499537816860850000244012_1)).

I then decided to open the code and have a look … 
I Modified i2c_master_read (twi.c) to use HAL_I2C_Master_Receive (blocking) in place of HAL_I2C_Master_Seq_Receive_IT => same issue
Had a closer look at HAL_I2C_Master_Receive and the RM08 Figure 274. "Method 1: transfer sequence diagram for master receiver. "

HAL_I2C_Master_Receive implements scenarios depending on number of variables to read
- 1 variable: is working made no changes.
- 2 variables:  code sequence of actions is not what is described in Method1 => changed it
- 3 variables: scenario not existing in RM08 => removed it to loop if more than 2 and not 3 variables
- More than 3 => made no change

Long story short, I now have a HAL_I2C_Master_Receive_Method1 function that works whith my Arduino test code and IMU_Zero example also. 

In addition, I performed the same tests with a compass (HMC5883) and a barometer (MS5611): **both worked well with the Core** !  (and the HAL_I2C_Master_Receive_Method1) …

I would then conclude my MPU-6050 ([ITG-MPU](https://fr.aliexpress.com/item/1005001621877471.html?spm=a2g0o.productlist.main.1.c8a0494e0mwzdY&algo_pvid=5dc1e894-ae6f-4a11-a514-1c9f28b36312&aem_p4p_detail=202307210718405499537816860850000244012&algo_exp_id=5dc1e894-ae6f-4a11-a514-1c9f28b36312-0&pdp_npi=3%40dis%21EUR%211.42%211.16%21%21%211.54%21%21%402100b20d16899491203666817d0732%2112000016846829096%21sea%21FR%210&curPageLogUid=MoWqjKbvT09t&search_p4p_id=202307210718405499537816860850000244012_1)) is a bit “sensitive” but still HAL_I2C_Master_Receive function code is unclear to me.

Thank you again for your help on that matter

**Comment by fpistm** [comment]
@yec23 
in fact the `i2c_master_read `is somehow blocking as we do the request to request then we poll the state with `HAL_I2C_GetState`.
Honestly, I don't know what do more as I can't reproduce your issue. 
Are you sure you have a legacy STM32F103? There is a lot of fake now.

**Comment by yec23** [comment]
"Are you sure you have a legacy STM32F103? " As I don't know how to answer that one, I can propose a photo but I guess that won't close the point of having a legacy.

![image](https://github.com/stm32duino/Arduino_Core_STM32/assets/139227232/5c7b2b48-45d0-488e-a822-5222e7be4def)

As wrote at the beginning, all works fine with RC framework, I can reproduce it on a different "blue pill" and MPU 6050, having HAL_I2C_Master_Receive following datasheet method1 makes it work. So, it is telling me there is a possibility it is coming from the Core but as you cannot reproduce it and I have seen other sensors working Ok, it makes it weird.

For now, I propose we close on this and see if the community reopens it.

Again, a big thank you for your time.
