### ISSUE TITLE
Pls add STM32F446ZE to supported controllers.

### ISSUE THREAD

**Issue by umtkyck** [stm32duino/Arduino_Core_STM32#2074]
**Is your feature request/improvement related to a problem? Please describe.**

A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Add any other context, example or screenshots about the feature request here.

Any contribution is welcome, so do not hesitate to submit a PR.

**Comment by fpistm** [comment]
Request added to #722.
