### ISSUE TITLE
Support for STM32H563VI

### ISSUE THREAD

**Issue by Blaze-Leo** [stm32duino/Arduino_Core_STM32#2089]
**The LQFP100 version of STM32H563ZI which is already present**
 - Name: STM32H563VIT6 
 - Link to all relevant information:
   * [Documentations](https://www.st.com/en/microcontrollers-microprocessors/stm32h563vi.html#documentation)

**Comment by fpistm** [comment]
Added to #722

**Comment by Blaze-Leo** [comment]
Thanks
