### ISSUE TITLE
Code incorrectly removed in commit

### ISSUE THREAD

**Issue by luke-adnav** [stm32duino/Arduino_Core_STM32#2094]
I believe these 2 lines of code were incorrectly removed in the latest commit to the file:

https://github.com/stm32duino/Arduino_Core_STM32/commit/0288818468e9f53651227af846f58012c0d40a7b#diff-f6b769f7b8597c3a03918579e5024885874caf2aa65259a76f8d80a5a2ff11e5L67-L68

https://github.com/stm32duino/Arduino_Core_STM32/blob/1559816ce8419acab0f5e28a2585f45af34756ad/system/STM32H7xx/system_stm32h7xx.c#L67-L68

**Comment by fpistm** [comment]
Hi @luke-adnav 
Thanks for pointing this. I've restored the 2 lines thanks #2095
