### ISSUE TITLE
Updated HID bootloader repo link in "Upload Method" page

### ISSUE THREAD

**Issue by arthurfprecht** [stm32duino/Arduino_Core_STM32#2109]
**Is your feature request/improvement related to a problem? Please describe.**

The HID bootloader recommended for F4xx boards on the "Upload methods" page of this repo (link to [Serasidis repo](https://github.com/samveen/STM32_HID_Bootloader/tree/merged) does not work with common F4xx boards such as the WeAct Black pills, because of some wrong PLL and clock configurations in the bootloader. 

**Describe the solution you'd like**

Include link of an alternative repo that offers a working alternative, like [Samveen's repo ](https://github.com/samveen/STM32_HID_Bootloader/tree/merged). The only problem is that there is no packages on this repo, so the user should be able to compile the bootloader by themselves (which might be a challenge for a newcomer).

**Describe alternatives you've considered**

Maybe directly give access to the bootloader binaries for these F4xx boards, since it is the same file for both F401 and F411 (and possibly add the HID bootloaders from Serasidis for F103 too) since they are very cheap and common, being used many times by newcomers - such ease of access would really improve the experience of a newcomer and increase the amount of people interested in the project.

**Additional context**

The bootloader from Serasidis repo just hangs on Black Pills because their HSE crystal is 25 MHz ( odd value, IDK was in the head of WeAct people when they chose this), and Serasidis bootloader seems to be configured for 8 MHz HSE crystal. Samveen's repo fixes this configuration and some other configuration details like pin definitions, port enabling and so on. 
An honorable mention is [Jiyong Youn's repo](https://github.com/hletrd/STM32_HID_Bootloader), which updated HAL and CMSIS libraries, and uses header files especially for F411. However, the PLL and clock settings are different from the ones present in Black pills, so I forked this repo and plan to update it to work with the Black Pills soon.

**Comment by fpistm** [comment]
Hi @arthurfprecht 
I understand your point anyway, all of those repo are forked from @Serasidis. This is the official supported.
The Blackpill from WeAct comes with a default bootloader inspired from HID https://github.com/WeActStudio/WeAct_HID_Bootloader_F4x1.
It would be hard to maintain and support all of them, officially we support only the one from @Serasidis which made a great job to include this here. Moreover F4 already have a builtin BL supporting USB and so interest is limited (more when automatic reset in BL will be supported).
