### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by deadly16soma** [stm32duino/Arduino_Core_STM32#2111]
when i try to compile the program using stm32f1 series its giving the below error 

section `.text' will not fit in region `FLASH'
/home/cepl/.arduino15/packages/STMicroelectronics/tools/xpack-arm-none-eabi-gcc/12.2.1-1.2/bin/../lib/gcc/arm-none-eabi/12.2.1/../../../../arm-none-eabi/bin/ld: region `FLASH' overflowed by 22324 bytes

**Comment by fpistm** [comment]
Your sketch is too big for the selected board. Try to reduce your sketch or optimize the build following the wiki.
