### ISSUE TITLE
different register toggled with a similar code in different IDE using the STM32 blue pill

### ISSUE THREAD

**Issue by mkeyno** [stm32duino/Arduino_Core_STM32#2118]
I have a blue pill board  and have tried to replicate the blinky program(toggle blue LED on PC13 pin) for both CubeIDE and Platformio

The clock setting and code as per the following image 
```c
void SystemClock_Config(void)
{
  RCC_OscInitTypeDef RCC_OscInitStruct = {0};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

  /** Initializes the RCC Oscillators according to the specified parameters
  * in the RCC_OscInitTypeDef structure.
  */
  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSE;
  RCC_OscInitStruct.HSEState = RCC_HSE_ON;
  RCC_OscInitStruct.HSEPredivValue = RCC_HSE_PREDIV_DIV1;
  RCC_OscInitStruct.HSIState = RCC_HSI_ON;
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
  RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSE;
  RCC_OscInitStruct.PLL.PLLMUL = RCC_PLL_MUL9;
  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
  {
    Error_Handler();
  }

  /** Initializes the CPU, AHB and APB buses clocks
  */
  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                              |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
  RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
  RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV2;
  RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;

  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_2) != HAL_OK)
  {
    Error_Handler();
  }
}


```

![5ea0b7b315ce20e5b449ce5a9941c6bbd347b2a6](https://github.com/stm32duino/Arduino_Core_STM32/assets/6232001/d807c8c3-b7f3-47a3-9a3a-3909ce308016)

It runs without any problem and SFR register monitoring tab shows the PC13 register (ODR13) works as it should be 

However, when I tried to make the same program with the Arduino platform, the debug tab in Platformio showed the different pin (ODR2 from GPIOB) had been changed and therefore the LED  not blinking
Following are images of the code and debug monitor 

![119d142e93f980ff19caa692903354e7b852e0c9](https://github.com/stm32duino/Arduino_Core_STM32/assets/6232001/c8d088a7-18ce-4498-9d6d-f613b9ffda18)

![94f52fac7cc41db53f55da241ed02da46a5a8e47](https://github.com/stm32duino/Arduino_Core_STM32/assets/6232001/62bdbe0b-de5d-4253-b5ad-683b0838b7b4)

![74abe2192d9fdf6427137708e4414f564db95bfe](https://github.com/stm32duino/Arduino_Core_STM32/assets/6232001/c3af2780-cea0-43c2-8845-c28761da90b9)

this is the issue[ link in Platformio ](https://community.platformio.org/t/on-compiling-and-uploading-blue-pill-code-does-not-work-within-platformio-as-does-in-cubeide/35081/14)

**Comment by fpistm** [comment]
We do not PIO. Only Arduino IDe.
