### ISSUE TITLE
[New Variant] does this lib support STM32F407IGT6?

### ISSUE THREAD

**Issue by EeeLo** [stm32duino/Arduino_Core_STM32#2131]
I using a STM32F407IGT6 board and want to build with this library,thanks.

**Comment by fpistm** [comment]
Hi @EeeLo,
STM32F407IG is not declared, base files to create the variatn are available here:
https://github.com/stm32duino/Arduino_Core_STM32/tree/main/variants/STM32F4xx/F407I(E-G)(H-T)_F417I(E-G)(H-T)

You can add it follinwing this wiki:
https://github.com/stm32duino/Arduino_Core_STM32/wiki/Add-a-new-variant-%28board%29

Added to #722 list
