### ISSUE TITLE
[New Variant] Support for RAK3271T

### ISSUE THREAD

**Issue by HelgeSeidel** [stm32duino/Arduino_Core_STM32#2162]
I kindly request support for the RAK3271T module. 

Existing variant RAK3271 worked fine for the module RAK3271E and RAK3271S. The RAK3172T module has an TXCO installed for a lower operation temperature and need a special configuration. Changing the LoRaWAN definition LORAWAN_BOARD_HAS_TCXO in [variant_RAK3172_MODULE.h](https://github.com/Oliv4945/Arduino_Core_STM32/blob/3874daca7e48a15801441a6a88ba471a7a092fdd/variants/STM32WLxx/WL54CCU_WL55CCU_WLE4C(8-B-C)U_WLE5C(8-B-C)U/variant_RAK3172_MODULE.h) from 0U to 1U was successful.

For details please see [RAK3172T TXCO configuration Issue](https://github.com/stm32duino/STM32LoRaWAN/issues/34).

Unfortunately I was not able to do the needed changes.

**Comment by fpistm** [comment]
> Unfortunately I was not able to do the needed changes.

Hi, added to #722 . Anyway I don't understand why you are not able to do the change if it works with other variant by simply change TCXO value.
