### ISSUE TITLE
STM32C011J6M6

### ISSUE THREAD

**Issue by DanSkareda** [stm32duino/Arduino_Core_STM32#2210]
Hello. I did not find the type: STM32C011J6Mx in the STM32C011 series list. Can you add it? The MCU is said to be on sale from January 2023. Thank you.

**Comment by fpistm** [comment]
Added to #722.
You can try to add it yourself following this wiki:
https://github.com/stm32duino/Arduino_Core_STM32/wiki/Add-a-new-variant-%28board%29
