### ISSUE TITLE
RawHID

### ISSUE THREAD

**Issue by rootexpression** [stm32duino/Arduino_Core_STM32#2216]
**Is your feature request/improvement related to a problem? Please describe.**

> A lack of RawHID (standalone, Keyboard+Mouse+RawHID) is a fairly large limitation these days.  It has become more and more common to use RawHID for various products and projects.

A clear and concise description of what the problem is.

> A lack of RawHID support

**Describe the solution you'd like**

> I'd like to see an option to allow RawHID, and RawHID with Keyboard and Mouse support for making HID devices that can use RawHID for LED control, keymap programming, and other types of control.  Serial is not a true replacement for RawHID.

**Describe alternatives you've considered**

> Serial was tried in the past but fails to suit the purpose in practice (it technically works but practically speaking it can be blocking, there are device identification issues, devices showing up on new ports, etc).

**Additional context**

Add any other context, example or screenshots about the feature request here.

Any contribution is welcome, so do not hesitate to submit a PR.

**Comment by fpistm** [comment]
Hi,

added to [USB] Features request list https://github.com/stm32duino/Arduino_Core_STM32/issues/687
