### ISSUE TITLE
USB CDC breaks application with STM32L4P5

### ISSUE THREAD

**Issue by maribeiro** [stm32duino/Arduino_Core_STM32#2237]
**Describe the bug**
Enabling the USB CDC (so that a virtual com port shows when i plug a usb to my board) seems to break the application.
[I also tried the exact same code  (minus the clock def) with a F407disco board (and although it's a different uP) it works fine! ]

**To Reproduce**
Just compile and upload the code (with USB Support CDC enabled) with a ST-LINK v2 :

```
extern "C" void SystemClock_Config(void)
{
  RCC_OscInitTypeDef RCC_OscInitStruct = {};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {};

  /** Configure the main internal regulator output voltage
  */
  if (HAL_PWREx_ControlVoltageScaling(PWR_REGULATOR_VOLTAGE_SCALE1_BOOST) != HAL_OK)
  {
    Error_Handler();
  }

  /** Initializes the RCC Oscillators according to the specified parameters
  * in the RCC_OscInitTypeDef structure.
  */
  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSE;
  RCC_OscInitStruct.HSEState = RCC_HSE_ON;
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
  RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSE;
  RCC_OscInitStruct.PLL.PLLM = 1;
  RCC_OscInitStruct.PLL.PLLN = 30;
  RCC_OscInitStruct.PLL.PLLP = RCC_PLLP_DIV2;
  RCC_OscInitStruct.PLL.PLLQ = RCC_PLLQ_DIV2;
  RCC_OscInitStruct.PLL.PLLR = RCC_PLLR_DIV2;
  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
  {
    Error_Handler();
  }

  /** Initializes the CPU, AHB and APB buses clocks
  */
  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                              |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
  RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
  RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV1;
  RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;

  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_5) != HAL_OK)
  {
    Error_Handler();
  }
}

// the setup function runs once when you press reset or power the board
void setup() {
  // initialize digital pin LED_BUILTIN as an output.
  pinMode(PB8, OUTPUT);
  Serial.begin(115200);
  Serial.println("Hello");
}

// the loop function runs over and over again forever
void loop() {
  digitalWrite(PB8, HIGH);  // turn the LED on (HIGH is the voltage level)
  delay(1000);                      // wait for a second
  digitalWrite(PB8, LOW);   // turn the LED off by making the voltage LOW
  delay(1000);                      // wait for a second
}
```

As soon as I enable the USB Support: CDC , the application seems to not run anymore. No LED blinking and no Virtual COM Port appear.
If i just comment the Serial related lines and revert the USB Support to: 'None', the LED blinks fine.

**Expected behavior**
A new Virtual Com port should appear when plugging the USB to the STM32L4P5 board and the LED should also blink.

**Screenshots**
![arduino](https://github.com/stm32duino/Arduino_Core_STM32/assets/546456/d33e675f-a3a1-49b3-8d43-df3868ff0b74)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Arduino IDE version: 2.2.1
 - STM32 core version: 2.7.1
 - Tools menu settings if not the default: USB Support: CDC (Generic 'Serial' supersed U(S)ART)
 - Upload method: SWD

**Board (please complete the following information):**
 - Name: Custom board with STM32L4P5
 - board has a 8MHz crystal
 - led on PB8 for testing purposes

**Additional context**
Using the exact same board with STM32CubeIDE and same clock configuration, the Virtual COM port shows correctly and the remaining code (PB8 toggle - blink) runs as expected.
Log with verbose output (compile and upload) : https://pastebin.com/DTvU40un

**Comment by fpistm** [comment]
.Thanks. So I close it.
