### ISSUE TITLE
Problem with Dynamic NFC tag based on M24SR with its printed NFC antenna

### ISSUE THREAD

**Issue by droussel3** [stm32duino/Arduino_Core_STM32#225]
Hello 

i try to use Dynamic NFC tag based on M24SR with its printed NFC antenna with
discovery L475VG-IOT01A.
There is a lot of error .
Thank you for issue

**Comment by fpistm** [comment]
Hi @droussel3 ,
same as for LSM6DSL question.
Submit your question/issue in the dedicated repo:
https://github.com/stm32duino/M24SR64-Y
Moreover you should gave more info about errors you get.
Arduino IDE, core version. copy of error...
Thanks
