### ISSUE TITLE
STM32 Cube Programmer - required installation

### ISSUE THREAD

**Issue by slavendam** [stm32duino/Arduino_Core_STM32#2252]
Please add in documentation (in "Getting Started" section) that installation of STM32 Cube Programmer is required to upload code with Arduino IDE.
Add link where to download file: https://www.st.com/en/development-tools/stm32cubeprog.html#get-software

Without that installed, it give errors that it can't find STM32_programmer_CLI file.
I'm not sure if that was installed automatically before with board installation, but now on 2 computers I needed to do that manually.

Thanks!

**Comment by fpistm** [comment]
Hi @slavendam 
This is already mentioned in the Getting Started WiKi page:
https://github.com/stm32duino/Arduino_Core_STM32/wiki/Getting-Started#extra-step 
It was never provided within the core due to the license agreement.
