### ISSUE TITLE
Question for 3D accelerometer and 3D gyroscope (LSM6DSL) 

### ISSUE THREAD

**Issue by droussel3** [stm32duino/Arduino_Core_STM32#226]
Hello
i would like to use gyroscope with x translation
So i try to convert measure in mdps with something like reading = accelerometer.get_x()

Thank you

**Comment by fpistm** [comment]
Hi @droussel3, you should submit your questions.issue about the LSM6DSL in the dedicated repo:
https://github.com/stm32duino/LSM6DSL
Than, probably @cparata could answer you.
Thanks
