### ISSUE TITLE
NUCLEO-144 / NUCLEO-H743ZI (STM32H743ZI)

### ISSUE THREAD

**Issue by HackInvent** [stm32duino/Arduino_Core_STM32#227]
Hi,
I'd like to know if there is a specific reason whether the NUCLEO-H743ZI isn't included.
We are willing to help to added it in the list of supported boards?
Thank you in advance,
Regards,
Alex

**Comment by Adminius** [comment]
Reason: nobody made a PR yet ;)
Feel free to do it. :)

**Comment by fpistm** [comment]
Hi @HackInvent 
There is no specific reason. H7 came later after the start of this core.
It will come.
First step will be to add HAL/LL, I've started this as a background task.
https://github.com/fpistm/Arduino_Core_STM32/tree/STM32H7
But this will required some work and tests.

**Comment by HackInvent** [comment]
@fpistm  I didn't see your commit! that's a good news.
I will give a try to create a new variant for NUCLEO-H743ZI from your commit an try to blink the builtin led (GPIO).
If things go well with the GPIO I will move for the other peripherals.
To be continued

**Comment by fpistm** [comment]
It's not a commit it's a working branch for H7 support.
Anyway, I will create the variant to test H7 support but before create it, it requires some work/test before.

**Comment by HackInvent** [comment]
Ok, if there is a specific task/test we can do it on the board.

**Comment by davidanger** [comment]
I have NUCLEO-F767ZI, can i help?

**Comment by fpistm** [comment]
@davidanger this issue is for H7 not F7.
Anyway, an update about H7 support, I get the Nucleo H743 up and running with my branch. I've some issue to fix and it will be released

**Comment by davidanger** [comment]
Now I got a NUCLEO-H743ZI, I'm working on this.

**Comment by davidanger** [comment]
#308

**Comment by fpistm** [comment]
unfortunately not, I'm OOO and this is on my local repo.
The first version is here as mentioned above:
https://github.com/fpistm/Arduino_Core_STM32/tree/STM32H7

**Comment by mjs513** [comment]
Was wondering if there is any update on the timeline for incorporating the H7?  Otherwise I will be using fpistm version

**Comment by fpistm** [comment]
Unfortunately, the next HAL/LL H7 is not released yet. I'm waiting it and I do not have any clue when this will be done.
I will try to get some info and then propose a first release.

**Comment by mjs513** [comment]
Thanks appreciate it.  Looking at using it for some development efforts.

**Comment by hasenbanck** [comment]
Just started a new project and wanted to use a H7 MCU. Too bad that the new HAL isn't ready yet. I will fall back to a F7 design for now.

**Comment by fpistm** [comment]
Hi @hasenbanck 
I know but this is not in my hands. I think a way to release it as soon as possible but I don't think having it before end of the year.

**Comment by hasenbanck** [comment]
@fpistm  Don't worry, I just wanted to show my interest. It's better to wait for the next HAL and use the new LL stuff / more stable HAL implementation.

**Comment by fpistm** [comment]
Hi @HackInvent, @davidanger, @mjs513, @Adminius, @hasenbanck 
I've submitted the PR to support H7: #392 ;)

**Comment by hasenbanck** [comment]
@fpistm It's seems you're pretty productive right now. Now you put me in a pinch and put pressure on me to change my current printer board project to use a H7...

**Comment by HackInvent** [comment]
Merci Frederic!

**Comment by HackInvent** [comment]
@fpistm I didn't dig around yet, but I was wondering what command are you using to upload the binary to the user flash, "stm32flash" tool?

**Comment by fpistm** [comment]
Simply by copying binary on the mounted mass storage. 
Or you can use STM32CubeProgrammer install on your host machine and selecting the binary generated by Arduino.
