### ISSUE TITLE
Board selection menu too long

### ISSUE THREAD

**Issue by tszaboo** [stm32duino/Arduino_Core_STM32#2271]
**Describe the bug**
Board selection is problematic. There are a large number of boards under Generic F1 or G0 series. Arduino IDE 1.8 under Windows doesn't allow scrolling menus, and the menu is so long it runs out of the screen (2560x1440). So selecting boards that are on the bottom isn't possible. 

**To Reproduce**

Select Generic F1 series.

**Expected behavior**
Possible to select the board.
Sub menu for the sub menu.
![stmduino](https://github.com/stm32duino/Arduino_Core_STM32/assets/74186529/bf9cced7-08f3-47df-b586-9287022f0ab3)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Arduino IDE version: 1.8.13
 - STM32 core version: [e.g. 1.4.0]
 - Tools menu settings if not the default: [e.g. Newlib Standard, No Serial]
 - Upload method: [e.g. SWD]

**Comment by fpistm** [comment]
Hi @tszaboo 
First this is not an issue with the STM32 core but linked to Arduino IDE.
I've already raised an issue for this to Arduino:
https://github.com/arduino/Arduino/issues/11416

Simply update your ide. 1.8.13 is old vs 1.8.19.
