### ISSUE TITLE
Disable HAL  feature when not used in the sketch

### ISSUE THREAD

**Issue by fpistm** [stm32duino/Arduino_Core_STM32#228]
Goal of this issue is to be able to disable HAL module if not used in the sketch in order to reduce binary size. 
- [x] I2C: done thanks https://github.com/stm32duino/Arduino_Core_STM32/commit/07dcdc414ab6b20e08c62e39a6554668b4fbdbca
- [x] SPI: done thanks https://github.com/stm32duino/Arduino_Core_STM32/commit/c41d8af147f7f84ebeff8bfb339f5bc324c02b45
- [x] ADC: done thanks https://github.com/stm32duino/Arduino_Core_STM32/commit/e4b1121a1be7c04871b06bb5d34f60e4ce3eacef
- [x] DAC: done thanks https://github.com/stm32duino/Arduino_Core_STM32/commit/68d3450ad38d26022bf48be2d840ada3c9e22a44
- [x] TIM: done thanks https://github.com/stm32duino/Arduino_Core_STM32/commit/b10696d7a092fdd07cf47dd9b57cf8c7b3a7552c
- [x] UART: done thanks  https://github.com/stm32duino/Arduino_Core_STM32/commit/83d872ff42c3d4988ffed7295199b22a453c9362
- [x] ETH: done thanks https://github.com/stm32duino/Arduino_Core_STM32/commit/680e01b3d558cae2f08f56aecdc4ef2ab03a3df7
- [x] SD: done thanks https://github.com/stm32duino/Arduino_Core_STM32/commit/e0e90cc3ab46c8a502bb86ca0555725fc74eb442
- [x] QSPI: done thanks https://github.com/stm32duino/Arduino_Core_STM32/commit/4e25050d2a8e9908d57af0fe9454870b655f338a
- [x] RTC: done thanks https://github.com/stm32duino/Arduino_Core_STM32/commit/075335850f8ee953556b85bb1ffe511c4b5cb8a1
- [x] USB: done thanks Arduino menu.
- [x] EXTI: done thanks https://github.com/stm32duino/Arduino_Core_STM32/commit/0e1f5a76f2e61fdf0077e457fb7e4d3ea18d4b4a. Interrupt API does not used HAL EXTI module anyway API is cleaned with `HAL_EXTI_MODULE_DISABLED`
- [x] RCC: mandatory. User can use LL to override `SystemClock_Config()`

Mainly useful for MCU with smallflash size (See #165)

## Proposition:
handle a default HAL conf file which could be override by end user at sketch level or variant.
~PeripheralPins arrays could also use new switch to force an array to be disable even if the HAL module is enabled.~

## Implementation done thanks #518 
* Extra HAL module can be enabled/disabled in `variant.h` if required or in a file named (at sketch level):       `hal_conf_extra.h`
  * To enable a HAL modules use the standard HAL definition: `HAL_PPP_MODULE_ENABLED` with `PPP` the peripheral to enable.
  * To disable a HAL modules use one or more following values:
      * `HAL_ADC_MODULE_DISABLED`
      * `HAL_I2C_MODULE_DISABLED`
      * `HAL_RTC_MODULE_DISABLED`
      * `HAL_SPI_MODULE_DISABLED`
      * `HAL_DAC_MODULE_DISABLED`
      * `HAL_ETH_MODULE_DISABLED`
      * `HAL_SD_MODULE_DISABLED`
      * `HAL_QSPI_MODULE_DISABLED`
      * `HAL_EXTI_MODULE_DISABLED`
      * `HAL_TIM_MODULE_DISABLED`
Note: `HAL_UART_MODULE_ENABLED` and `HAL_PCD_MODULE_ENABLED` are handled thanks Arduino menu.

* Custom HAL configuration file can replace the default one by adding  a file named (at sketch level):
      `hal_conf_custom.h` .

**Comment by fpistm** [comment]
This will be available for all variants. It's a core feature not specific to a variant.
Anyway, depending of the feature used, the HAL part is not embed if not used.
Example for SPI or I2C if SPI.h or Wire.h is not include, the HAL part is removed by the compiler as it is not used. Only the pinmap array is kept but it should be removed if not used to save some space.

**Comment by fpistm** [comment]
Serial can now be enabled or not:
https://github.com/stm32duino/Arduino_Core_STM32/commit/83d872ff42c3d4988ffed7295199b22a453c9362

This allow to build without HAL_UART_MODULE_ENABLED (save memory)
HAL_UART_MODULE_ENABLED should not be defined in stm32yyxx_hal_conf.h

**Comment by tve** [comment]
Shouldn't RCC also be on the list here, e.g., following the comment https://github.com/stm32duino/Arduino_Core_STM32/issues/165#issuecomment-373646769 ("I've generate the code with CubeMx to use LL instead of HAL for RCC") ?

**Comment by fpistm** [comment]
This could.

**Comment by Adminius** [comment]
hi @fpistm ,
for this points:

> ADC: be able to build without HAL_ADC_MODULE_ENABLED
>  DAC: it's already possible to build without HAL_DAC_MODULE_ENABLED, maybe a menu could be proposed to enable or not the feature...
>  PWM: be able to build without HAL_PWM_MODULE_ENABLED

we need menu and some ```ifdef``` "only", right?

**Comment by fpistm** [comment]
Hi @Adminius,
probably yes, I have to find a nice and easiest way to do this.
