### ISSUE TITLE
Define Two Serial ports

### ISSUE THREAD

**Issue by sabas1080** [stm32duino/Arduino_Core_STM32#230]
HI

I am trying to define 2 serial ports for the RAK811 Tracker Board but could not find an example of how to do it

Should it be the variant.h file?

![image](https://user-images.githubusercontent.com/2874292/37563067-f5bc89cc-2a3d-11e8-9a9b-9ce256fa4865.png)

//Serial USB-Serial port USB of the board
#define UART_TX                                     PA_9
#define UART_RX                                     PA_10

//Serial for GPS, Serial3?
#define GPS_UART        		            	UART_3 
#define GPS_POWER_ON_PIN		      PA_15
#define GPS_UART_TX                                 PB_10
#define GPS_UART_RX                                 PB_11
#define GPS_PPS_PIN                                 PA_0

http://docs.rakwireless.com/en/RAK811%20TrackerBoard/Software%20Development/RAK811%20TrackerBoard%20User%20manual%20V1.1.pdf

Thanks

**Comment by fpistm** [comment]
Theu are several way:
Define linked pins in variant.h:
```
#define GPS_UART_TX PB10
#define GPS_UART_RX PB11
```

Then at sketch level:
```
HardwareSerial SerialGPS(GPS_UART_RX, GPS_UART_TX);
SerialGPS.begin(115200);
```

Or in variant.h
```
// Enable Serial3
#define ENABLE_HWSERIAL3
// You can declare an alias
#define SerialGPS               Serial3
```
Then at sketch level for example:
```
SerialGPS.begin(115200);
```

**Comment by sabas1080** [comment]
Thanks!
