### ISSUE TITLE
Servo.attach() call to Servo::write() before min/max are configured leads to issue when writting angles in degrees

### ISSUE THREAD

**Issue by jan019** [stm32duino/Arduino_Core_STM32#2308]
**Describe the bug**
The Servo library calls the `write() `function within the `attach()` function https://github.com/stm32duino/Arduino_Core_STM32/blob/641f3d8883e9a7220f65dded355dc32e218a990d/libraries/Servo/src/stm32/Servo.cpp#L124 before configuring ` this->min` and `this->max` values https://github.com/stm32duino/Arduino_Core_STM32/blob/641f3d8883e9a7220f65dded355dc32e218a990d/libraries/Servo/src/stm32/Servo.cpp#L126-L127, which however need to be configured for `write()` function to work correctly when the servo position is set in degrees. The function `write() `uses the `this->min` and `this->max` values to map the passed value in degrees between min and max https://github.com/stm32duino/Arduino_Core_STM32/blob/641f3d8883e9a7220f65dded355dc32e218a990d/libraries/Servo/src/stm32/Servo.cpp#L156/

**To Reproduce**
```int pin = 1;
int min = 40;
int max = 70;
int value = 40;

// on first call to attach, the write is called with a different value in this->min and this->max than on following calls
Servo.attach(pin, min, max, value)
```

 - STM32 core version: 2.7.1

The `write()` function should either not be called in the `attach()` function at all, or it must be called after `this->min` and `this->max` are configured.

**Comment by fpistm** [comment]
Hi @jan019 
Thanks for the detailed report.
It seems logical. Could you submit a PR ? I guess configuring the values before the write call instead of after is enough.

**Comment by jan019** [comment]
Hi @fpistm, thanks for checking this out. I will submit a PR later today with configuring the values before the write call instead of after (I have tested this and it works well).
