### ISSUE TITLE
Is the STM32F030CCT6 chip supported? 

### ISSUE THREAD

**Issue by xiezhoubin** [stm32duino/Arduino_Core_STM32#2337]
Is the STM32F030CCT6 chip supported? If it is not currently supported, how can I modify the configuration file to support it?

**Comment by fpistm** [comment]
Hi @xiezhoubin 
no it is not declared.
You can follow this wiki to add a basic support:
https://github.com/stm32duino/Arduino_Core_STM32/wiki/Add-a-new-variant-%28board%29

Generated files are available here:
https://github.com/stm32duino/Arduino_Core_STM32/tree/main/variants/STM32F0xx/F030CCT

**Comment by fpistm** [comment]
Added to #722 (already requested).
Feel free to provide a PR and reference this issue.
