### ISSUE TITLE
SPI clock acting weird

### ISSUE THREAD

**Issue by danieleff** [stm32duino/Arduino_Core_STM32#24]
I was trying Adafruit ILI9341, but was not working.
I think the following code is a simplified version of the problem:
```
void setup() {
  int cs = 2;
  SPI.begin();
  pinMode(cs, OUTPUT);
  digitalWrite(cs, HIGH);

  while(1) {
      SPI.beginTransaction(SPISettings(1000000, MSBFIRST, SPI_MODE0));
      delay(100);
      digitalWrite(cs, LOW);
      SPI.transfer(0x01);
      digitalWrite(cs, HIGH);
      SPI.endTransaction();
      delay(100);
  }
}
````
With arduino UNO, I get the following:
![image](https://user-images.githubusercontent.com/1460099/27009801-8bdee75c-4e97-11e7-9de6-25654bb8c283.png)
With F746 discovery:
![image](https://user-images.githubusercontent.com/1460099/27009868-0bffd6f2-4e99-11e7-895a-6b998b575660.png)
or ( with F407 always)
![image](https://user-images.githubusercontent.com/1460099/27009870-0edc9b4e-4e99-11e7-9c8a-12ecca032bda.png)
Logic analizer settings are the same.
Can you check if you get the same results?

**Comment by fpistm** [comment]
Hi @danieleff ,

have you made those test with or without this fix?
https://github.com/stm32duino/Arduino_Core_STM32/pull/19

**Comment by danieleff** [comment]
With that fix:
```
> git show
commit 055864fb16457cd45b638f48588b85477f0eb226
Merge: dadfba3 052443e
Author: Frederic Pillon <frederic.pillon@st.com>
Date:   Fri Jun 9 17:36:17 2017 +0200
```
(Actually does not compile on 407 disco, `timer.c:466:22: error: 'RCC_PeriphCLKInitTypeDef {aka struct <anonymous>}' has no member named 'TIMPresSelection'`, but its another issue, I commented out)

**Comment by fpistm** [comment]
I do not check yet, but seems as GPIO pull config issue.

**Comment by fpistm** [comment]
Thanks @cparata 
Pull setting on the SCK pin should be in PULLDOWN if the SPI polarity is LOW and in PULLUP if the SPI polarity is HIGH.
