### ISSUE TITLE
Wire memory leak on multiple begin() call

### ISSUE THREAD

**Issue by benmalenfant** [stm32duino/Arduino_Core_STM32#2441]
**Describe the bug**
When calling begin() after the receive and transmit buffers have been allocated, the begin function orphans the allocations by resetting the pointer to nullptr, on the next call of allocateTxBuffer(), we get a new memory allocation while the previous one has never been freed, this in turns causes heap segmentation and will lead to lack of memory in the long run.

Proposed fix in #2442 

**To Reproduce**
Using this simplified code, we can see that the Wire receive buffer is reallocated every requestFrom call
```
#include <Arduino.h>
#include <Wire.h>

void setup() {
}

void loop() {
  Wire.begin();
  Wire.requestFrom(1,1);
}
```

1. Run demo code
2. Place a breakpoint in allocateRxBuffer right after the realloc line
3. Notice the tmp pointer increase location every call
4. Wait long enough and you'll run out of memory

**Expected behavior**
The wire library should not cause a memory leak, even if calling begin() multiple times is bad practice.

**Board (please complete the following information):**
 - Name: BlackPill STM32F411CEU6
 - Hardware Revision: V3.1

  Applicable to any stm32

**Comment by fpistm** [comment]
Hi. In fact your code is wrong. You have to call `Wire.end()`;
This is like you call malloc each loop iteration without calling free.

**Comment by benmalenfant** [comment]
Yeah I agree, this is dummy code, but my philosophy is that Arduino should be dummy proof. This became an issue for me because I had locally scoped a sensor object(I know this was stupid...), destroying and creating it every time caused it to call begin and in turn cause the memory leak.
