### ISSUE TITLE
J-Link support when using STM32CubeProgrammer

### ISSUE THREAD

**Issue by jamesy0ung** [stm32duino/Arduino_Core_STM32#2452]
STM32CubeProgrammer has support for J-Link probes, however the Arduino core only allows it to use SWD with ST-Link, DFU or UART

I'd like to be able to upload using a J-Link probe from the Arduino IDE. Thank you!

![Screenshot 2024-07-18 170617](https://github.com/user-attachments/assets/3b1e67a7-1c82-4d89-b2e6-38f2483f4571)

**Comment by fpistm** [comment]
Hi @jamesy0ung 
Feel free to contribute and provide a PR.

**Comment by jamesy0ung** [comment]
I don't know much about the internals of Arduino Cores, though I'd be happy to if I can get some pointers as to what needs to be modified

I did a search for STM32CubeProgrammer and saw some references to it in platform.txt, however I'm not sure what exactly creates the option in the Arduino IDE and where/how I can extend it.

I also searched up the docs for the STM32CubeProgrammer CLI and it's just a flag passed to it.

**Comment by jamesy0ung** [comment]
I haven't done any work on Arduino cores before, but I got the CLI working by using the following flag. `-c port=JLINK ap=0`

I tried to modify boards.txt to add support but I can't see it in the Arduino IDE as a programmer
```

GenF1.menu.upload_method.jlinkMethod=STM32CubeProgrammer (J-Link)
GenF1.menu.upload_method.jlinkMethod.upload.protocol=swd
GenF1.menu.upload_method.jlinkMethod.upload.options=-c port=JLINK ap=0
GenF1.menu.upload_method.jlinkMethod.upload.tool=stm32CubeProg
```

Is there anything I'm missing?

**Comment by fpistm** [comment]
I would recommend to check the script:
https://github.com/stm32duino/Arduino_Tools/blob/main/stm32CubeProg.sh

And simply add a new interface (protocol): jlink then in the script simply call it with correct option.
About the fact it is not in the menu, this is an Arduino IDE issue. You have to delete the cache.
#### Path:
* Linux: `$HOME/.config/arduino-ide/`
* Windows: `C:\Users\<login>\AppData\Roaming\arduino-ide`

**Comment by jamesy0ung** [comment]
I've opened 2 PR's

One adds a case to the flashing script, and the other adds support under the STM32F1, I'll look into adding J-Link programmer support for other boards, but I don't have any other hardware to test with

**Comment by Amir1387aht2** [comment]
Guys Any New Info? I Wanna Use Jlink Flasher And There's No Straight Option
