### ISSUE TITLE
 COM port under the Tools menu no longer appeared on V2.8

### ISSUE THREAD

**Issue by liuquanli1970** [stm32duino/Arduino_Core_STM32#2469]
When I upgraded to version 2.8, the COM port under the Tools menu no longer appeared, in fact, the serial port did exist. Version 2.71 can display normally. Do you have the same problem as me?

**Comment by fpistm** [comment]
Hi @liuquanli1970 
Since 2.8.0 only the Arduino IDE 2 is supported due to some Arduino specifications update.
I guess you used the legacy version 1.8 that's why the COM port does not appears.

**Comment by liuquanli1970** [comment]
Yes, I am using Arduino V1.8.19. Thank you for the prompt.
