### ISSUE TITLE
Debugging generic STM32L0 missing target/stm32l0x.cfg

### ISSUE THREAD

**Issue by nemtsov** [stm32duino/Arduino_Core_STM32#2471]
When attempting to run the debugger on a "Generic STM32L0 series" board, the "gdb-server" console reads the following error:

```
embedded:startup.tcl:28: Error: Can't find target/stm32l0x.cfg
in procedure 'script' 
at file "embedded:startup.tcl", line 28
```

The `launch.json's` `configFiles` section contains `target/stm32l0x.cfg`, but the file does not exist in `xpack-openocd-0.12.0-3/openocd/scripts/target` (nor in the latest 0.12.0-4). Instead there's a `target/stm32l0.cfg` file. When I update the `launch.json` to use the config that exists (without the `x`) the debugger starts without errors.

**To Reproduce**
1. Install STM32 Mcu based boards in the Boards Manager
2. Select the "Generic STM32L0 series" with the "/dev/cu.usbmodern1202 Serial Port (USB)"
3. File -> Examples -> Basics -> Blink
4. Press the "Start Debugging" button on the top left bar
5. Notice the error in the "gdb-server" console

**Desktop (please complete the following information):**
 - OS: macOS 14.5 (Apple M2)
 - Arduino IDE version: 2.3.2
 - STM32 core version: 2.8.1
 - Upload method: SWD

**Board (please complete the following information):**
 - Name: NUCLEO-L010RB
 - Hardware Revision: Rev C
 - Extra hardware used if any: No additional hardware. But the STLINK is broken off and is connected via CN7.

**Comment by fpistm** [comment]
Thanks @nemtsov for pointing this.
It is now fixed.
