### ISSUE TITLE
How to manually install the core?

### ISSUE THREAD

**Issue by edogaldo** [stm32duino/Arduino_Core_STM32#249]
Hello!
I know there is the easy install route via json file but I'd like to perform manual custom install in the "<Arduino_home>/hardware" folder.
Could you please provide tips on how to do it?
I.e.:
- where to install the tools?
- apart from the core and the tools, what else to install and where?

Thanks in advance, E.

**Comment by fpistm** [comment]
Is it ok now? Can I close this issue ?

**Comment by fpistm** [comment]
No feedback. Assuming it is ok.
