### ISSUE TITLE
Is this an error?!

### ISSUE THREAD

**Issue by edogaldo** [stm32duino/Arduino_Core_STM32#250]
https://github.com/stm32duino/Arduino_Core_STM32/blob/cf54e13565a50c0c61740d7f10e9f8f3ec4ede77/cores/arduino/stm32/clock.c#L99
In the comment you say "divide by 4" but in the code you divide by 5, is it an error?!

**Comment by fpistm** [comment]
Hi, in fact it was done by @fprwi6labs for the old F0 core:
https://github.com/fpistm/Arduino_Core_STM32F0/blob/a97ed35b1252e4fb667f354019279216de518af1/cores/arduino/libstm32f0/clock.c#L178
He probably copy/paste from F4 implementation to F0 and adapt the code without update the comment.
When I've merged all the core in one I did not seen this.

**Comment by edogaldo** [comment]
Looking at the code, precision seems not to be a big concern: the function always waits for `delay_us+1` us and also the function doesn't consider the effort required to calculate `(((HAL_RCC_GetHCLKFreq() / 1000000)/5)*delay_us)+1`. 
So, as long as the only difference is the constant loop duration (4 vs 5) and the usage of `subs.w` vs `sub`, why not simplifying and factoring everything?

**Comment by fpistm** [comment]
Yes, why not.
As I said this is linked to legacy code and probably some other clean/merge could be done elsewhere.
