### ISSUE TITLE
Incorrect clock settings for NUCLEO-H563ZI

### ISSUE THREAD

**Issue by dojyorin** [stm32duino/Arduino_Core_STM32#2505]
When I used CubeMX to verify clock settings of NUCLEO-H563ZI, an error occurred.
I also looked at reference datasheet for H563ZI chip and found some parts that were not optimized.

- ADC/DAC input clock is too high
https://github.com/stm32duino/Arduino_Core_STM32/blob/6e60087cabd8a037169d0ed6df4edc1f2d457bd9/variants/STM32H5xx/H563Z(G-I)T_H573ZIT/variant_NUCLEO_H563ZI.cpp#L238

The maximum clock for ADC/DAC components is 125MHz, but HCLK is 250MHz, so input clock is too high.
As an idea, by setting PLL2 to `N = 125` `R = 4` it is possible to supply 125MHz from PLL2R to ADC/DAC.

- LPUART clock is low
https://github.com/stm32duino/Arduino_Core_STM32/blob/6e60087cabd8a037169d0ed6df4edc1f2d457bd9/variants/STM32H5xx/H563Z(G-I)T_H573ZIT/variant_NUCLEO_H563ZI.cpp#L237

The LPUART will accept up to 250MHz, but PLL2Q is set to 32MHz, which may result in reduced performance.
I think using a PCLK3 (250MHz) would be fine.

The H563ZI Generic board seems to have same problem.

https://github.com/stm32duino/Arduino_Core_STM32/blob/6e60087cabd8a037169d0ed6df4edc1f2d457bd9/variants/STM32H5xx/H563Z(G-I)T_H573ZIT/generic_clock.c#L81

**Comment by fpistm** [comment]
Hi @dojyorin 
I didn't check the ADC/DAC but for LPUART, it is correct this allows to get low baudrate (9600) else it will not be available.
Feel free to provide a PR to fix ADC/DAC
