### ISSUE TITLE
Installation report error

### ISSUE THREAD

**Issue by banbeiduyao** [stm32duino/Arduino_Core_STM32#2541]
ARDUINO version 2.3.3 installation development board error

Some indexes could not be updated. Get "https://raw.githubusercontent.com/stm32duino/BoardManagerFiles/main/package_stmicroelectronics_index.json": dial tcp: lookup raw.githubusercontent.com: getaddrinfow: The requested name is valid, but no data of the requested type was found.: https://github.com/stm32duino/BoardManagerFiles/raw/main/package_stmicroelectronics_index.json

**Comment by fpistm** [comment]
Hi @banbeiduyao 
Unfortunately nothing can be done here. File is hosted on GitHub and Arduino IDE is in charge to download it. So you have an issue with your network (proxy, firewall, antivirus,...) or with Arduino IDE.

Try to clean up the Arduino IDE cache.
Hooe this help.
