### ISSUE TITLE
__libc_init_array fails on STm32H750XBH6

### ISSUE THREAD

**Issue by thisdp** [stm32duino/Arduino_Core_STM32#2551]
Arduino IDE 2.3.3
STM32H750XBH6
STM32 MCU Based Boards 2.8.1
An empty sketch is compiled with only setup and loop.
in startup_stm32h750xbhx.s
running "bl __libc_init_array" causes WWDG_Handler before entering "main".

Program compiled using CubeIDE works fine. "main" can be called.
Program compiled using Arduino but part number in VBTx works fine on STM32H750XBH6. "main" can be called.

**Comment by fpistm** [comment]
Hi @thisdp 
Thanks for the issue.
I think it is linked to the linker script. If you used the one from the VBTx it will works.
I have to analyze deeply to understand the root cause.

**Comment by thisdp** [comment]
> Hi @thisdp Thanks for the issue. I think it is linked to the linker script. If you used the one from the VBTx it will works. I have to analyze deeply to understand the root cause.

VBTx IBKx can work, I haven't tested others, but I am sure XBHx can not work.

**Comment by fpistm** [comment]
This is what I said if you used the linker script of the VB with the HB it will work.

**Comment by thisdp** [comment]
> This is what I said if you used the linker script of the VB with the HB it will work.

I mean that I am not sure if other chips/part numbers have the same problem
