### ISSUE TITLE
Issue when compiling on windows with path containing white space

### ISSUE THREAD

**Issue by jmchiappa** [stm32duino/Arduino_Core_STM32#256]
Compilation failed on Windows 7 x64. I'm using the release 1.2.0.
It appears when the build path contains white space.
By modifying platform.txt file in this way
`compiler.extra_flags=-mcpu={build.mcu} -mthumb "@{build.opt.path}"`
It fixed the issue. I just added double quote.

**Comment by fpistm** [comment]
Thanks for the report and fix @jmchiappa
