### ISSUE TITLE
Enable UCPD Dead Battery Support Again

### ISSUE THREAD

**Issue by klaus-liebler** [stm32duino/Arduino_Core_STM32#2576]
Good evening,

my feature request is related to the problem described here:
https://github.com/manuelbl/usb-pd-arduino/issues/20
https://www.mikrocontroller.net/topic/573034#7778987

In short: The Arduino Framework for STM32G431 disables the Dead Battery Support for USB-C PD applications without offering conditional compilation for this. However, at least I need Dead Battery Support in my application. The only way to archive this now is to comment out the particular line in hw_config.c

I would like to have a preprocessor symbol that enables Dead Battery Support (i.e. disables the deactivation).

Thank you, regards
Klaus

**Comment by fpistm** [comment]
Hi @klaus-liebler 
Feel free to provide a PR for this.
Thanks
