### ISSUE TITLE
 Arduino_Core_STM32 1.3.0 used for STM32lowpower when and where to download

### ISSUE THREAD

**Issue by jackyouandme** [stm32duino/Arduino_Core_STM32#258]

**Comment by fpistm** [comment]
Hi @jackyouandme 
The 1.3.0 will be release next week. I'm currently working on this.
STM32RTC and STM32LowPower will be also release and I will ask to Arduino to reference them in the Library manager.

**Comment by dds90** [comment]
Hi Frederic!
I need to use STM32RTC lib. When will be release the 1.3.0? Meantime, How can I use a preview?
Thank you in advance!

**Comment by fpistm** [comment]
Hi @dds90.
I've got some issue that's why I've delayed it. 
I hope release it end of this week.
To use the git:
https://github.com/stm32duino/wiki/wiki/Using-git-repository
and use the zip of the STM32RTC library

**Comment by fpistm** [comment]
Release done and available thanks Arduino Board manager:
https://github.com/stm32duino/Arduino_Core_STM32/releases/tag/1.3.0

Libraries released 
[STM32RTC 1.0.0 ](https://github.com/stm32duino/STM32RTC/releases/tag/1.0.0)
[ STM32LowPower 1.0.0](https://github.com/stm32duino/STM32LowPower/releases/tag/1.0.0)

and available thanks Arduino library manager soon:
https://github.com/arduino/Arduino/issues/7696

**Comment by dds90** [comment]
Hi @fpistm,
Thank you so much for your support!
I confirm that work well with RTC_LSE_CLOCK in a STM32VLDISCOVERY.
To keep the time with the external backup battery, I must use also the LowPower library?
Thank you again,
Daniele

**Comment by fpistm** [comment]
Welcome.
Not necessarily, but this could help to save power.

**Comment by fpistm** [comment]
I close this issue has 1.3.0 and libs are released.

**Comment by jackyouandme** [comment]
Hi  Frederic Pillon,

   Thank you very much for your hard work.



terry



jackyouandme@foxmail.com
 
From: Frederic Pillon
Date: 2018-06-16 13:17
To: stm32duino/Arduino_Core_STM32
CC: jackyouandme; Mention
Subject: Re: [stm32duino/Arduino_Core_STM32] Arduino_Core_STM32 1.3.0 used for STM32lowpower when and where to download (#258)
Closed #258.
