### ISSUE TITLE
[New Variant] STM32F407IGH

### ISSUE THREAD

**Issue by hlgzhx** [stm32duino/Arduino_Core_STM32#2589]
**Board description (please complete the following information):**
 - Name: Generic STM32F407IGH

I‘ve found the variant folder of F407I(E-G)(H-T)_F417I(E-G)(H-T) in "STMicroelectronics\hardware\stm32\2.8.1\variants\STM32F4xx",but it is not added in the "STMicroelectronics\hardware\stm32\2.8.1\boards.txt".
After I add:
# Generic F407IGHx
GenF4.menu.pnum.GENERIC_F407IGHX=Generic F407IGHx
GenF4.menu.pnum.GENERIC_F407IGHX.upload.maximum_size=524288
GenF4.menu.pnum.GENERIC_F407IGHX.upload.maximum_data_size=131072
GenF4.menu.pnum.GENERIC_F407IGHX.build.board=GENERIC_F407IGHX
GenF4.menu.pnum.GENERIC_F407IGHX.build.product_line=STM32F407xx
GenF4.menu.pnum.GENERIC_F407IGHX.build.variant=STM32F4xx/F407I(E-G)(H-T)_F417I(E-G)(H-T)
GenF4.menu.pnum.GENERIC_F407IGHX.debug.svd_file={runtime.tools.STM32_SVD.path}/svd/STM32F4xx/STM32F407.svd

in it,and put the ldscript.ld in F407I(E-G)(H-T)_F417I(E-G)(H-T) folder,it works perfectly.i tested several functions include Can bus.They all work correctly.My board is Robomaster Development Board Mk. C whose Mcu is STM32F407IGH.
May you stuffs add this beforehead during next version?thanks very much .

**Comment by fpistm** [comment]
Hi @hlgzhx 

did you plan to provide a PR ?

**Comment by hlgzhx** [comment]
sorry i forgot to answer that.I'd like to provide a PR

**Comment by fpistm** [comment]
No worry.  This issue is referenced. When you have time to do the PR it will be linked to this issue and update accordingly.
