### ISSUE TITLE
compilation for L051C8 fails

### ISSUE THREAD

**Issue by tshcherban** [stm32duino/Arduino_Core_STM32#2594]
Compiling the code below 

```
#include <Arduino.h>

const uint32_t BuzzerPinNum = PC1;

void setup() { }

void loop() { }
```

gives an error

`[src\main.cpp:3:31](stm32fail.ino:3:31): error: 'PC1' was not declared in this scope; did you mean 'PC_1'?`

**Desktop:**
 - Windows 10
 - Arduino CLI 1.1 / Arduino IDE 1.8 - 2
 - STM32 core 2.9.0
 - Tools menu settings default
 - Upload method: N/A

**Board:**
 - STM32L051C8T6

**Comment by fpistm** [comment]
There is no PC1 for LQFP48:

![Screenshot_20241208_083621_Drive](https://github.com/user-attachments/assets/7dbb4c15-19ec-48ad-be5d-4b1d6919eec2)
