### ISSUE TITLE
analog.c can't deal with a chip that doesn't have a DAC

### ISSUE THREAD

**Issue by RickKimball** [stm32duino/Arduino_Core_STM32#26]
I'm trying to add a variant for the STM32F030R8, however it doesn't have a DAC. The analog.c file fails to compile because of all the DAC structures and defines used.

My solution was a complete hack, I just ifdefed out code that wouldn't compile.

It seems that to grow into a broader range of chips and boards this is going to have to be addressed.

**Comment by RickKimball** [comment]
I checked out the Nucleo_F030R8 branch and tried this. It seems to be solved.  Should I close this or wait for it to be merged into the master branch?

**Comment by fpistm** [comment]
Thanks @RickKimball
