### ISSUE TITLE
UART7 causes Nucleo F091RC to lock up

### ISSUE THREAD

**Issue by TT-ZX** [stm32duino/Arduino_Core_STM32#260]
When I try to use Serial.print over UART7 on the Nucleo F091RC the MCU locks up.
Here is the code to demonstrate the issue:

```
HardwareSerial mySerial(PC7,PC6);

void setup() {
  pinMode(LED_BUILTIN, OUTPUT);
  mySerial.begin(9600);
}

void loop() {
  digitalWrite(LED_BUILTIN, HIGH);
  delay(1000);
  mySerial.println("Hello World!");
  digitalWrite(LED_BUILTIN, LOW);
  delay(1000);
}

```
The LED will turn on and stay on.  Nothing is received from UART7
I am using V1.2.0 of STM32 Cores.  I've tried earlier version but the result is the same.  I am using version 1.8.5 of the Arduino IDE on Gentoo.

Can anyone else confirm this issue or know of a work around?

Thanks,
Justin

**Comment by TT-ZX** [comment]
Is that something I can easily change and try or is it quite involved?

**Comment by TT-ZX** [comment]
I tried UART3 - UART8 and got the same problem.  Only UART1 and UART2 work for me.

**Comment by fpistm** [comment]
F091 is a bit specific for UART.
I think issue is probably linked to uart irq handler.
https://github.com/stm32duino/Arduino_Core_STM32/blob/22290391347075c19152716efe0c95bda5e9c6ac/cores/arduino/stm32/uart.c#L779

Maybe you can try comment here:
https://github.com/stm32duino/Arduino_Core_STM32/blob/22290391347075c19152716efe0c95bda5e9c6ac/cores/arduino/stm32/uart.c#L796

this test:
`if (__HAL_GET_PENDING_IT(HAL_ITLINE_USART7)!= RESET)`

**Comment by TT-ZX** [comment]
This works for all but UART6 and only works for one UART at a time.  If I comment more that one of those tests, only the last UART works.

**Comment by fpistm** [comment]
Ok thanks for the test. I will test and try to fix it for the next release.

**Comment by fpistm** [comment]
Hi, @TT-ZX 
I've found the issue.
__HAL_GET_PENDING_IT() read IT line status in SYSCFG register which required to be clocked.
    
This set of registers is implemented only on STM32F09x  to collect all pending interrupt sources associated with  each interrupt line into a single register.
This allows users to check by single read which peripheral requires service in case more than one source is associated to the interrupt line.

I've tested also with several USART in the same sketch:
```
HardwareSerial Serial7(PC7,PC6);
HardwareSerial Serial4(PA1,PA0);
HardwareSerial Serial3(PB_11,PB_10);

void setup() {
Serial3.begin(115200);
Serial4.begin(115200);
Serial7.begin(9600);
}

void loop() {
Serial3.println("Hello World I'm USART3!");
Serial4.println("Hello World I'm USART4!");
Serial7.println("Hello World I'm USART7!");
}
```
