### ISSUE TITLE
[New Variant] STM32H723VGT6 WeAct Studio

### ISSUE THREAD

**Issue by acronis2000** [stm32duino/Arduino_Core_STM32#2606]
STM32H723VGT6 WeAct Studio

Documentations, schematics :
https://github.com/WeActStudio/WeActStudio.MiniSTM32H723

Purchase Link:
https://aliexpress.com/item/1005005872938104.html

With a link to the Wiki https://github.com/stm32duino/Arduino_Core_STM32/wiki/Add-a-new-variant -(board) is familiar, but unfortunately I have no experience in this regard.

I really ask for help in adding this board !

**Comment by fpistm** [comment]
Added to #722
