### ISSUE TITLE
STM32 Watchdog begin function crash program on Wio E5 mini

### ISSUE THREAD

**Issue by larswd** [stm32duino/Arduino_Core_STM32#2611]
When reporting any issue, please try to provide all relevant information to help on its resolution.

**Describe the bug**
IWatchdog freezes program execution on [Seeed Studio's E5 mini](https://wiki.seeedstudio.com/LoRa_E5_mini/). If I call the IWatchdog.begin()-function, the entire board freezes. I am using the [platformio port](https://github.com/platformio/platform-ststm32) of the core, but the newest version is updatd to Arduino_Core_STM32 2.9.0.

**To Reproduce**
```c++
#include <Arduino.h>
#include "IWatchdog.h"

void setup() {
  IWatchdog.begin(10000);
  Serial.begin(115200);
}

void loop() {
  delay(2000);
  IWatchdog.reload();
  Serial.println("Hei verden!");
}
```

1. Compile and upload sketch using platformio. [User guide if necessary](https://github.com/larswd/STM32WL-Seeed-LoRa-E5-mini-Playground).
2. Observe the program never entering the loop-function.

**Expected behavior**
IWatchdog is supposed to begin, followed by repeated output of "Hei, verden!" to the serial monitor. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Arduino IDE version: n/a. Platformio version 3.3.3 for vscode is used. 
 - STM32 core version: 2.9.0 (Version 18.0.0 of platformio port)
 - Tools menu settings if not the default: The following lines are added to platformio.ini:
    ```
    debug_tool = stlink
    upload_protocol = stlink
    monitor_speed = 115200
    ```
 - Upload method: STLink

**Board (please complete the following information):**
 - Name: [Seeed Studio Wio E5 mini]((https://wiki.seeedstudio.com/LoRa_E5_mini/)
 - Extra hardware used if any: [ST link](https://www.adafruit.com/product/2548)

**Comment by fpistm** [comment]
Hi @larswd 
Your sketch is not correct and IWD works as expected.
The timebase of the watchdog is in **µs** not **ms**.
So you required it to expire each 10 ms and do a delay of 2000 ms before reload.

Correct sketch is:
```c++
#include "IWatchdog.h"

void setup() {
  IWatchdog.begin(10000000);
  Serial.begin(115200);
}

void loop() {
  delay(2000);
  IWatchdog.reload();
  Serial.println("Hei verden!");
}
```

**Comment by larswd** [comment]
Oops. I guess I should practice counting zeroes. Thanks for the quick reply!

**Comment by fpistm** [comment]
Welcome.
