### ISSUE TITLE
SoftwareSerial needed

### ISSUE THREAD

**Issue by Yannick-Marietti** [stm32duino/Arduino_Core_STM32#267]
Hello

Thanks for your great job  !

A working "SoftwareSerial" instruction for STM32 would be greatly appreciated for compatibility with many existing Arduino sketches.

Best regards

Yannick

**Comment by fpistm** [comment]
Could be interesting to investigate:
https://www.pjrc.com/teensy/td_libs_AltSoftSerial.html

**Comment by Yannick-Marietti** [comment]
Merci !

**Comment by harryberlin** [comment]
SoftwareSerial with parity option for Nucleo-32 L432KC would be awesome.

**Comment by stas2z** [comment]
JFYI alternate HAL compatible softserial implementation based on ported SoftwareSerialIntAP code
https://github.com/stas2z/SoftSerial_STM32

**Comment by fpistm** [comment]
Thanks @stas2z for sharing.

**Comment by Yannick-Marietti** [comment]
Merci encore !

-------- Message original --------
De : Frederic Pillon <notifications@github.com<mailto:notifications@github.com>>
Date : mer. 11 sept. 2019 à 20:27
À : stm32duino/Arduino_Core_STM32 <Arduino_Core_STM32@noreply.github.com<mailto:Arduino_Core_STM32@noreply.github.com>>
CC : Yannick MARIETTI <yannick.marietti@st.com<mailto:yannick.marietti@st.com>>,Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Objet : Re: [stm32duino/Arduino_Core_STM32] SoftwareSerial needed (#267)

Closed #267<https://github.com/stm32duino/Arduino_Core_STM32/issues/267> via #645<https://github.com/stm32duino/Arduino_Core_STM32/pull/645>.

-
