### ISSUE TITLE
Typical LSI on the Blue Pill (F103xy) should be 40000

### ISSUE THREAD

**Issue by edogaldo** [stm32duino/Arduino_Core_STM32#270]
https://github.com/stm32duino/Arduino_Core_STM32/blob/38605636366c442b5da96a5b1c9ead71356ccbf0/variants/BLUEPILL_F103C8/stm32f1xx_hal_conf.h#L117

**Comment by fpistm** [comment]
Hi @edogaldo 
Right,
https://www.st.com/resource/en/datasheet/stm32f103c8.pdf

![image](https://user-images.githubusercontent.com/20641798/41807923-ab55e99c-76d6-11e8-80e2-0744dfef0958.png)

I will update it. and check sysclock config
