### ISSUE TITLE
Enhance GPIO usage using LL

### ISSUE THREAD

**Issue by fpistm** [stm32duino/Arduino_Core_STM32#274]
Using LL instead of HAL will increase GPIO access.

**Comment by davidanger** [comment]
Good News

**Comment by ktand** [comment]
The link to the 2nd fille doesn't work. Should be:

https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/HAL/HAL_STM32/fastio_STM32.cpp

**Comment by hasenbanck** [comment]
Upps, yeah. Corrected. Was just programming C stuff and brain got a blackout.

**Comment by fpistm** [comment]
I've made a first try about this issue, see #368 
@hasenbanck , @ktand thanks for sharing.
I guess the `get_GPIO_Port` enhancement will allow you to avoid use `FastIO_init`
