### ISSUE TITLE
Needed USB support for STM32F7

### ISSUE THREAD

**Issue by Vicky-S** [stm32duino/Arduino_Core_STM32#276]
I need a USB support which can transfer files from SD card or STM32F7 internal memory to USB via USB-HS or  USB-FS. Is there any active example?

Thanks.

**Comment by fpistm** [comment]
Currently not. 
Will be covered by #222

**Comment by Vicky-S** [comment]
ok

**Comment by fpistm** [comment]
Closed as duplicated
