### ISSUE TITLE
The timer with external interrupt issue.....

### ISSUE THREAD

**Issue by Jason0416** [stm32duino/Arduino_Core_STM32#283]
When use the timer, The external interrupts not work.........

stimer_t timer1; // Timer1

void.....(){
    timer1.handle.Instance = TIM1;
    TimerPulseInit(&timer1, 417, 0, IsrTim1);
    .
    .
    .
    pinMode(PA1, INPUT);
    attachInterrupt(PA1, rxPinChanged, CHANGE);
}

The timer interrupt working, But the external interrupts no work.

**Comment by fpistm** [comment]
Hi, could you be more precise, please.
Which target? Full sketch,...

**Comment by Jason0416** [comment]
BluePill is the target.  When change the pinMode to INPUT_PULLUP or INPUT_PULLDOWN, It's working........

**Comment by fpistm** [comment]
And what is wired on PA1? and How?

**Comment by Jason0416** [comment]
![image](https://user-images.githubusercontent.com/8410110/43309031-269e7cf0-91b6-11e8-9248-9c64c1c329b3.png)

**Comment by fpistm** [comment]
I guess in INPUT the voltage level is not proper (10k too high?) that's why the CHANGE level is not detect.
Using the INPUT_PULL* probably clean the level.

**Comment by Jason0416** [comment]
I will test it and the results will be reported here. Thks.

**Comment by Jason0416** [comment]
Yes! The resistor is to small.....
