### ISSUE TITLE
Support for STM32F103Z

### ISSUE THREAD

**Issue by LucasFeliciano21** [stm32duino/Arduino_Core_STM32#289]
Just a little question guys.

I've installed the last version of the Arduino_Core_32 and I didn't find the STM32F103Z, V or R options. 

This boards are not available on this release?

Thanks

**Comment by fpistm** [comment]
Hi @LucasFeliciano21 
You probably want this core:
https://github.com/rogerclarkmelbourne/Arduino_STM32

**Comment by Adminius** [comment]
@LucasFeliciano21 or you can add your variant:
https://github.com/stm32duino/wiki/wiki/Add-a-new-variant-(board)

**Comment by LucasFeliciano21** [comment]
Thanks guys!
