### ISSUE TITLE
EEPROM usage

### ISSUE THREAD

**Issue by LucasFeliciano21** [stm32duino/Arduino_Core_STM32#291]
Hi guys, just a little question

I was trying to use the EEPROM to storage values to initialize an object globally.

The problem that I faced is, I have to initialize the object with an address out of the setup, like the Radiohead library. When I try to run the EEPROM.read() before the setup and I get the error that EEPROM it's not declared on the scope.

How can I read this data? Thanks!

**Comment by fpistm** [comment]
Hi @LucasFeliciano21 
For support or questions please use the forum.
Issue is mainly to report a bug or do a feature request.
Thanks in advance

**Comment by LucasFeliciano21** [comment]
Much sorry, 

Thanks anyway!
