### ISSUE TITLE
Uploader tool wrong path?

### ISSUE THREAD

**Issue by fprwi6labs** [stm32duino/Arduino_Core_STM32#3]
I think I missed some thing. Why change the path in platform.txt `{runtime.tools.STM32Tools.path}` in `{runtime.hardware.path}` ?

When I install the package from Arduino Manager board,  `tools/` is under `STM32/` and not `STM32/hardware/`...

I rather to ask before to fix it. Just to be sure.

**Comment by fpistm** [comment]
Hi @fprwi6labs,
There is no issue.
On the repo the path is {runtime.hardware.path} in order to be able to use the Arduino_Tools repo directly.
It is change to {runtime.tools.STM32Tools.path} by the packager script in order to be inline with Arduino_Tools package.

**Comment by fprwi6labs** [comment]
My bad.
I close this issue that is not one.
