### ISSUE TITLE
unknown chip id! 0x10076415

### ISSUE THREAD

**Issue by fpistm** [stm32duino/Arduino_Core_STM32#31]
_From @kuobakuoba on June 14, 2017 6:50_

I connected my STM32L476RG to the arduinoIDE with according settings.
<img width="367" alt="1191388541" src="https://user-images.githubusercontent.com/20016691/27118709-1de94858-510f-11e7-9865-0baf5d924af4.png">
And upload a Blink example from the IDE.

But I get these errors.
<img width="1026" alt="2017-06-14 2 39 14" src="https://user-images.githubusercontent.com/20016691/27118863-dab12474-510f-11e7-978d-f3d45749275a.png">
<img width="394" alt="2017-06-14 2 46 07" src="https://user-images.githubusercontent.com/20016691/27118948-4737988a-5110-11e7-929e-eed570628d21.png">

I am running mac with sierra.
![2017-06-14 2 41 12](https://user-images.githubusercontent.com/20016691/27119132-3188d3a4-5111-11e7-88d3-c424b3ceb376.png)
I have eclipse with Ac6 for STM32 and it works with no problem.
How can I get STM32duino to work?
Thanks.

_Copied from original issue: stm32duino/wiki#1_

**Comment by fpistm** [comment]
Hi @kuobakuoba,
Please, Could you try to update the STLink firmware.

[ST-LINK, ST-LINK/V2, ST-LINK/V2-1 firmware upgrade ](https://my.st.com/content/my_st_com/en/products/embedded-software/development-tool-software/stsw-link007.license%3d1497338034863.html)

**Comment by kuobakuoba** [comment]
Hi!! @fpistm 
I've tried but with no luck.
<img width="736" alt="2017-06-14 3 32 48" src="https://user-images.githubusercontent.com/20016691/27120619-e448b2de-5116-11e7-8ea9-b07b0aa361c0.png">
It was exactly the same error code as above.
Thanks.

**Comment by fpistm** [comment]
Ok thanks for the test.
Probably that the stlink binary released do not support this boards or have an issue.
Could you test with the latest version 1.3.0:
https://github.com/texane/stlink/releases/tag/1.3.0

To test, use this command line, where binary file is the path to your bin built with arduino (See the build log to find the fullpath):
stlink/st-flash write <binary path> 0x8000000

If it's work you could replace the binary installed by STM32Tools.
You also have the path in the build log:
/User/...../packages/STM32/tools/STM32Tools/2017.5.12/tools/macosx/stlink/

Unfortunately I do not have Mac to perform the test.
Maybe @rogerclarkmelbourne  has some clues about that?

**Comment by kuobakuoba** [comment]
@fpistm Sorry for the late reply.
To be honest,I don't know how to use these binaries.
But with some lucks or something I managed to get it work with the file you gave me.
I just clicked st-flash and copy all file in the bin folder to here(/User/...../packages/STM32/tools/STM32Tools/2017.5.12/tools/macosx/stlink/) and for some reason it just worked.
Thank you so much for your help.

**Comment by fpistm** [comment]
Ok, so if its work with the updated file, I will do an update in the [Arduino_Tools](https://github.com/stm32duino/Arduino_Tools)

**Comment by fpistm** [comment]
Moved to https://github.com/stm32duino/Arduino_Tools/issues/7
