### ISSUE TITLE
OT: STM32CubeProgrammer Windows DFU driver issue

### ISSUE THREAD

**Issue by edogaldo** [stm32duino/Arduino_Core_STM32#310]
Dear @fpistm please apologise for the OT issue..
I'm writing here to ask you, as long as you are an STM employee, if you could help addressing internally the subject issue.
Essentially the DFU driver delivered with the STM3CubeProgrammer (even with new version 1.1) is not signed so it's not possible to install it if the computer is locked to prevent installation of unsigned drivers..
There is also following ST community thread to address this issue: https://community.st.com/s/question/0D50X00009XkXagSAF/dfu-usage-with-stm32cbeprogrammer
but so far it received no attention at all from STM support...

Hope you can help, anyway thank you very much in any case.

Best regards, Edogaldo.

**Comment by fpistm** [comment]
Hi @edogaldo,
No worries.
I will raised it internally.
Anyway, I will close this issue as it is not related to this project. The best way, is to use ST community as primary support.
Note that I would like unify tools used to flash the board (stlink, serial,...), as STM32CubeProgrammer is now multi os it is probably a good candidate, anyway I currently met some issue with the CLI...

**Comment by fpistm** [comment]
Hi @edogaldo,
FYI, the STM32CubeProgrammer 1.2.0 is released and should contains signed DFU driver
https://www.st.com/en/development-tools/stm32cubeprog.html

**Comment by edogaldo** [comment]
Thank you very much Frederic, I'm pretty sure your sponsorship has
been decisive!! ;)

Il giorno gio 13 set 2018 alle ore 10:40 Frederic Pillon <
notifications@github.com> ha scritto:

**Comment by fpistm** [comment]
In fact no, issue was already opened and resolution on going when I've asked ;)
