### ISSUE TITLE
Serial doesn't work on a Nucleo L432KC

### ISSUE THREAD

**Issue by fivdi** [stm32duino/Arduino_Core_STM32#312]
The below program should blink the built-in LED and and print "Hello, World!" to Serial every two seconds. On a Nucleo L432KC it does blink the built-in LED but it doesn't print "Hello, World!" to Serial. On a Nucleo F303K8 or Nucleo F411RE the program functions correctly, the built-in LED blinks and "Hello, World!" is printed to Serial.
```cpp
void setup() {
  pinMode(LED_BUILTIN, OUTPUT);
  Serial.begin(9600);
}

void loop() {
  Serial.println("Hello, World!");

  digitalWrite(LED_BUILTIN, HIGH);
  delay(50);
  digitalWrite(LED_BUILTIN, LOW);
  delay(1950);
}
```
- Version of STM32 Core: 1.3.0
- Version of Arduino; 1.8.5
- operating system: Ubuntu 16.04
- Tools menu settings
  - Board: "Nucleo-32"
  - USB interface: "None"
  - Optimize: "Smallest (-Os default)"
  - Board part number: "Nucleo L432KC"
  - Serial interface: "Enabled with generic serial"
  - Upload method: "Mass Storage"
  - Port: "/dev/ttyACM1"

**Comment by fpistm** [comment]
Hi @fivdi 
Right, there is an issue with 1.3.0 with serial.
See https://github.com/stm32duino/Arduino_Core_STM32/commit/c322ae509c8b7c116be529d6b168ef917f043d8e
This fix this issue.

**Comment by gcormier** [comment]
Came here looking for exactly for this. Target date for 1.3.1 at all?

**Comment by fpistm** [comment]
Hi, this will be the 1.4.0 and it should be in one or 2 weeks

**Comment by projetandonoape** [comment]
It still not working for me, even with all that mentioned changes above:(
Serial communications only works on version 1.2.0

**Comment by fpistm** [comment]
Hi @projetandonoape 
With this fix it should work. I guess you have other issue but I can't guess which one without any info.
I will release 1.4.0 next week so I advise to wait and then test.
