### ISSUE TITLE
Arduino_Core_STM32/libraries/EEPROM/

### ISSUE THREAD

**Issue by edogaldo** [stm32duino/Arduino_Core_STM32#324]
Is this library working?

**Comment by fpistm** [comment]
Yes it should
#248 raised this is too slow on F7 linked to page size but works.
#302 is a rework for @hasenbanck to use buffered access to the
data on the flash.

**Comment by AnHardt** [comment]
Shouldn't there be a hint this library uses flash to replace the non existent EEPROM?

**Comment by fpistm** [comment]
This is a port from official Arduino EEPROM library, that's all:
https://github.com/stm32duino/Arduino_Core_STM32/blob/a320623be3d8a191e10140525a6aa6e05b7ff64c/libraries/EEPROM/library.properties#L5

**Comment by fpistm** [comment]
I close this issue as EEPROM is functional.
