### ISSUE TITLE
How to remove arduino library not used on STM32 program

### ISSUE THREAD

**Issue by edsonbrito** [stm32duino/Arduino_Core_STM32#325]
Hi,

I would like know how to remove some library not used to decrease memory STM32?

Thks,
my e-mail is engeletrojunior@hotmail.com

**Comment by fpistm** [comment]
Hi @edsonbrito,
Could you be more precise?
What do you mean by some library? or you talk about some feature?
What is your target? on which board?

**Comment by edsonbrito** [comment]
> Hi @edsonbrito,
> Could you be more precise?
> What do you mean by some library? or you talk about some feature?
> What is your target? on which board?

**Comment by edsonbrito** [comment]
> not used code and or library should be removed automatically by Compiler
It is a afirmation? Are they removided automatically?

**Comment by fpistm** [comment]
Yes, useless code are remove by the toolchain.
Anyway, this issue #228 will cover your request.
