### ISSUE TITLE
analogWrite() doesn't use the full range

### ISSUE THREAD

**Issue by RickKimball** [stm32duino/Arduino_Core_STM32#33]
On a NUCLEO-F030R8, if I call analogWrite(9,255), I'm seeing a 3.9us low pulse each period. I expected pin 9 to just stay HIGH when using a value of 255 as that is the max value for the range (0-255).  Shouldn't it do a digitalWrite(9,HIGH) if the value provided is the max of the analogResolution?

Using a value of 254 I'm seeing a low pulse of 7.8us where I expected to see a 3.9us one
Using a value of 1 I see a 3.9us high pulse this seems right so the problem isn't just an off by one problem.
Using a value of 0 produces a steady low value on the pin.

**Comment by RickKimball** [comment]
It appears like the period might be off
```
diff --git a/cores/arduino/stm32/analog.c b/cores/arduino/stm32/analog.c
index 25b74b9..e96e639 100644
--- a/cores/arduino/stm32/analog.c
+++ b/cores/arduino/stm32/analog.c
@@ -719,7 +719,7 @@ void pwm_start(PinName pin, uint32_t clock_freq,
   timHandle.Instance               = pinmap_peripheral(pin, PinMap_PWM);
   if (timHandle.Instance == NC) return 0;
   timHandle.Init.Prescaler         = (uint32_t)(getTimerClkFreq(timHandle.Instance) / clock_freq) - 1;
-  timHandle.Init.Period            = period;
+  timHandle.Init.Period            = period-1;
   timHandle.Init.ClockDivision     = TIM_CLOCKDIVISION_DIV1;
   timHandle.Init.CounterMode       = TIM_COUNTERMODE_UP;
 #ifndef STM32L0xx
```
That seems to produce better results

**Comment by fpistm** [comment]
Hi @RickKimball , i will check this tuesday. Thanks for the feedback

**Comment by fpistm** [comment]
You are right, Period need to be decrease by 1 ( = Auto-reload value : TIMx->ARR)
