### ISSUE TITLE
How to use "build_opt.h"?

### ISSUE THREAD

**Issue by edogaldo** [stm32duino/Arduino_Core_STM32#342]
As per subject. 

Thanks in advance, E.

**Comment by fpistm** [comment]
Hi @edogaldo 
https://github.com/stm32duino/wiki/wiki/Customize-build
Is it ok with this?

**Comment by edogaldo** [comment]
Thank you @fpistm, the wiki topic is clear and helpful; just a couple of comments:
- I'd suggest to add the name of the file in the title for better/faster identification, i.e. "How to customize build options - build_opt.h"
- Use of the ".h" extension is misleading: I was thinking of it as a normal header file and I was trying to add options in a pre-processor format ("#define xxx yyyy"); it would have been better to me to use a different extention (i.e. "build_opt.conf") anyway, once clarified, it's ok

Thanks again and best, E.

**Comment by fpistm** [comment]
I used the .h extension because Arduino IDE do not allow to add all extension file you want. If i well remember only .h, .c, .cpp, .ino.
I've updated the title.

**Comment by edogaldo** [comment]
Ah ok, didn't know.

Thanks you!

**Comment by edogaldo** [comment]
Just update also above link because it's no more valid.
