### ISSUE TITLE
Support for low power mode

### ISSUE THREAD

**Issue by rreicher** [stm32duino/Arduino_Core_STM32#35]
Hello,

Is there a plan that supports low power mode for the L4 family
Sleep
Stop0 / Stop1 / STop2
Standby
shutdown

And in addition, the possibility of using different range MSI?

thanks

**Comment by fpistm** [comment]
hi @rreicher,
yes it is planned to support low power (current target is week 43).
For MSI, I have to check.

**Comment by fpistm** [comment]
Answered.
Close.
