### ISSUE TITLE
USB not recognised error in STM32f103

### ISSUE THREAD

**Issue by Vicky-S** [stm32duino/Arduino_Core_STM32#358]
HI,
I bought STM32F103C8T6 today. when I connect my controller via micro USB it shows USB not recognized error.  What is the problem and how to solve this?

**Comment by fpistm** [comment]
Currently with this core, this is normal as it is not managed. USB provides power that's all.
#344 will provide this support.

**Comment by Vicky-S** [comment]
ok. Then I need to buy STLINK to program this controller right?

**Comment by fpistm** [comment]
No, you can Upload via Serial. See chapter Upload via Serial here: http://wiki.stm32duino.com/index.php?title=Uploading_a_sketch

**Comment by Vicky-S** [comment]
ok. Thanks bro.

**Comment by fpistm** [comment]
I let you close this as answered.
USB will come with 1.5.0 core ;)

**Comment by Vicky-S** [comment]
When will 1.5.0 come?
