### ISSUE TITLE
Missing node value in boards.txt for early NUCLEO-F030R8 boards

### ISSUE THREAD

**Issue by RickKimball** [stm32duino/Arduino_Core_STM32#36]
To support the older F030R8 boards, the "node" entry in boards.txt needs to look like this:

boards.txt:
```
Nucleo_64.menu.Nucleo_64_board.NUCLEO_F030R8.node=NODE_F030R8,NUCLEO
```

This is probably true for all boards?

**Comment by fpistm** [comment]
> This is probably true for all boards?
I need to check.

**Comment by RickKimball** [comment]
On linux with the quotes, I get this message:
```
/home/kimballr/.arduino15/packages/STM32/tools/STM32Tools/2017.5.12/tools/linux/massStorageCopy -I /tmp/arduino_build_547147/AnalogInOutSerial.ino.bin -O "NODE_F030R8,NUCLEO" 
"NODE_F030R8 not found. please ensure the device is correctly connected
An error occurred while uploading the sketch
```
This needs to be changed as per my comment or a bug needs to be created for the massStorageCopy code so it can handle the " character
