### ISSUE TITLE
upload vect

### ISSUE THREAD

**Issue by Homayoun-MH** [stm32duino/Arduino_Core_STM32#360]
Hi
I've  uploaded STM32duino-bootloader via st-link and installed windows driver using  libwdi.
https://github.com/rogerclarkmelbourne/STM32duino-bootloader/tree/master/binaries
https://github.com/pbatard/libwdi/releases

and I have a "Maple(COM12)" in my device manager.

but whenever I upload a sketch using upload methods st-link or serial, "Maple(COM12)" vanished.
possibly because upload vector of Arduino_Core_STM32 does not bypass the STM32duino-bootloader, so that the boot loader is lost.

how can I set a different upload vector an keep using Serial USB?

**Comment by fpistm** [comment]
Hi this is currently not supported, this will comes with DFU upload method.
The VECT_TAB_OFFSET can be redefined but the linker script need to be updated

**Comment by Homayoun-MH** [comment]
Thanks

but is there any way to get USB serial port working?

**Comment by fpistm** [comment]
This is plan for the 1.5.0 release:
https://github.com/stm32duino/Arduino_Core_STM32/pull/344

**Comment by fpistm** [comment]
`VECT_TAB_OFFSET` can be redefined thanks `build_opt.h` if required.
It will be also handle in #411 and will also covered the upload part.
