### ISSUE TITLE
Nucleo-L432KC serial no longer working

### ISSUE THREAD

**Issue by mwcoop** [stm32duino/Arduino_Core_STM32#362]
I first began trying this project on the Nucleo-L432KC boards a bit over 1 month ago. At that time everything seemed to work smoothly.

Over the past weekend I reinstalled the STM32 boards support. Now, for whatever reason, the default Serial object fails to work. I've checked the TX pin and it is not even pulled high by default after calling Serial.begin(9600).

Any help in resolving this ASAP would be greatly appreciated. I'm testing on a Mac if that matters.

When viewing the serial output of a program doing a simple Hello world loop every second, I get test similar to:

$$$x07702216...

**Comment by fpistm** [comment]
Hi @mwcoop 
Fix will be available in the next release: https://github.com/stm32duino/Arduino_Core_STM32/issues/312

**Comment by mwcoop** [comment]
Any approximate date for this? Seriously appreciated!

**Comment by fpistm** [comment]
Hi @mwcoop,
could you try with the latest release 1.4.0 which is now available?
Thanks in advance

**Comment by fpistm** [comment]
No feedback consider it is ok with #312
