### ISSUE TITLE
EEPROM Reset issue

### ISSUE THREAD

**Issue by mayurharge** [stm32duino/Arduino_Core_STM32#396]
Hello,
I am using EMBEDIS library for handling EEPROM related functions.
I am getting the proper response for the first startup. but I am not able to retain the values after a restart.
the code works fine with [http://dan.drown.org/stm32duino/package_STM32duino_index.json]
board files.
Thanks

**Comment by mayurharge** [comment]
Yes i have used controller from bluepill. stm32f103c series 128kb version.
Build options were default Just changed the upload method to serial and controller size to 128 kb.

Here is the link for sketch

https://github.com/thingSoC/embedis/blob/master/examples/Uno/Embedis_Uno/Embedis_Uno.ino


I will update the exact build options later

**Comment by fpistm** [comment]
I will not be able to test before next week. Anyway, last time I've tested the eeprom emulation on F1 it was functionnal. I saw some core define usage in the lib maybe there is a small update to do also in the lib.
Did you test default eeprom example which do not use the lib? (Put and get example)

**Comment by mayurharge** [comment]
Okay i wil test that.

Thanks & Regards,
   Mayur Harge <http://www.linkedin.com/in/mayurharge>
+919096028050
+918668423824

**Comment by fpistm** [comment]
Hi @mayurharge 
I've been able to test and reproduce.
In fact value are not reset and well present in the FLASH.
Issue come from a wrong E2END definition. As EMBEDIS store since the end of the EEPROM it miss one data as E2END was defined as the SIZE instead of the last valid address.

**Comment by mayurharge** [comment]
Can you please update where to define the valid E2END definition


Thanks & Regards,
   Mayur Harge <http://www.linkedin.com/in/mayurharge>

**Comment by mayurharge** [comment]
Thanks.
