### ISSUE TITLE
Support for Nucleo STM32L452

### ISSUE THREAD

**Issue by tekk** [stm32duino/Arduino_Core_STM32#425]
Hello guys,
Thanks for the amazing work.
I need support for Nucleo STM32L452.
Would that be possible?
Thank you.

**Comment by fpistm** [comment]
Hi @tekk 
Have you consider adding it following:
https://github.com/stm32duino/wiki/wiki/Add-a-new-variant-(board)

**Comment by fpistm** [comment]
@tekk 
FYI, I've been able to do the variant in //.
See #434

**Comment by tekk** [comment]
Thank you! That's really awesome! Will try it as soon as I'll have some spare time. Thanks again. 🙂👍

**Comment by fpistm** [comment]
Welcome.
Note, that I've also test the variant as I've got the board.

**Comment by tekk** [comment]
That's good. Is there any possibility that the STM32Duino core would also work for this board apart from standard HAL libraries? Thanks.

**Comment by fpistm** [comment]
I do not understand your question about working apart from HAL ?

**Comment by tekk** [comment]
Sorry, I'm not native english speaker. I'm asking if this board could work with STM32Duino. But I think you're not the right person to ask, STM32Duino guys would need to support it, right?

**Comment by fpistm** [comment]
Ok I think I understand your questions.
Roger's core (which does not use HAL) doesn't support L4 series. So no.
The only core supported it is this one.

**Comment by tekk** [comment]
Nevermind. I will stick with the HAL layer. Thank you for your effort.
