### ISSUE TITLE
SPI DMA support

### ISSUE THREAD

**Issue by thomasfla** [stm32duino/Arduino_Core_STM32#429]
SPI transfer is quite slow with a delay between each byte of about   
**1.4us** when calling `SPI.transfer(uint8* buff, int N); ` with a 9Mhz SPI clock. 

This delay is more than the duration of a byte transfer at this speed..

I think using DMA should solve this issue, but the current SPI library doesn't allow it.

Any chance this could be added to the todo features?

**Comment by fpistm** [comment]
They are already some improvement requests for SPI.
DMA could be one of this. Anyway I will not have time soon to do this. Any help are welcome

**Comment by VictorLamoine** [comment]
This should help you get started: http://stm32duino.com/viewtopic.php?f=14&t=3527&p=47009#p47009

**Comment by fpistm** [comment]
Close this one to track all SPI request on the same issue #257.
Mark it as duplicated.
