### ISSUE TITLE
Possible I2C bug - no devices recognized

### ISSUE THREAD

**Issue by Nufflee** [stm32duino/Arduino_Core_STM32#431]
I have a LSM9DS1 sensor connected to my STM32F407VG-DISC1 board but the I2C scanner example doesn't detect it. The wiring is correct because I can use it outside Arduino (STM32CubeMX with lower level libraries). 
I have it connected on PB9 (I2C1 SDA) and PB8 (I2C1 SCL) so I modified the sketch a bit ([hastebin of the modified sketch](https://hastebin.com/esiyaqetaj.cpp)) but I've also tried using different pins.
I also noticed that scan on the pins where the device is actually connected is way faster than on the default `Wire` global pins.

I would've reported this issue on the forums but registration seems to be disabled so I can't.

**Comment by fpistm** [comment]
Have you pull up with a resistor the i2c lines?

**Comment by Nufflee** [comment]
@fpistm  Oh, will try that out! And the LSM9DS1 has internal 10k pullups.

**Comment by Nufflee** [comment]
Yup, that fixes it, thanks!
