### ISSUE TITLE
Mis-placed extern "C" in board.h

### ISSUE THREAD

**Issue by ppescher** [stm32duino/Arduino_Core_STM32#446]
The `extern "C"` block inside "board.h" may cause incorrect symbols to be defined and linker issues. See:
https://github.com/stm32duino/Arduino_Core_STM32/blob/e07c02a20a409120682c9367841377a6edd2ce5f/cores/arduino/board.h#L8-L22

For example, when I added a global function in my own "variant.cpp" file, the corresponding function declaration in "variant.h" ended up being exported as a "C" symbol, causing the linker to fail with an "undefined reference" error message.

This can potentially cause similar troubles in other places and anyway it does not seem correct: any other header file does already handle `extern "C"` symbols and placing an "#include" directive inside an `extern "C"` block should be avoided.

I think only the `init()` function declaration in "board.h" should be made `extern "C"`.

**Comment by fpistm** [comment]
Thanks @ppescher 
I see your point.
