### ISSUE TITLE
Issue when uploading on MacOS with path containing white space / blank

### ISSUE THREAD

**Issue by gerardwr** [stm32duino/Arduino_Core_STM32#448]
**Describe the bug**
Upload to STM32 (maple_upload) fails when stm32duino is installed in a directory with a name containing a blank / white space.
 
**To Reproduce**

STM32duino installed in directory (space in "My Data"):
```
/Users/gerard/Documents/My Data/ArduinoESP/hardware/Arduino_STM32-master
```
Upload results in (sorry, is in Dutch):
```
De schets gebruikt 16132 bytes (12%)  programma-opslagruimte. Maximum is 131072 bytes.
Globale variabelen gebruiken 3088 bytes (15%) van het dynamisch geheugen. Resteren 17392 bytes voor lokale variabelen. Maximum is 20480 bytes.
/Users/gerard/Documents/My Data/ArduinoESP/hardware/Arduino_STM32-master/tools/macosx/maple_upload cu.usbmodemFA411 2 1EAF:0003 /var/folders/5l/fjrz26dn5710yvf5hgzlcvsw0000gn/T/arduino_build_316844/HelloWorld_STM32.ino.bin 
/Users/gerard/Documents/My Data/ArduinoESP/hardware/Arduino_STM32-master/tools/macosx/maple_upload: line 34: /Users/gerard/Documents/My: No such file or directory
Er trad een error op gedurende laden van de schets
```

**Desktop (please complete the following information):**
 - OS: MacOs
 - Arduino IDE version: [1.8.7]
 - STM32 core version: [1.5.0]
 - Upload method: [STM32 bootloader]

**Board (please complete the following information):**
 - Name: [Blue Pill]

** Workaround
As a quick fix I adapted the maple_upload source:

* Line 34 : replaced `$(dir)` with `"${DIR}"`
* Lines 44,48,53 : replaced `${DFU_UTIL}` with `"${DFU_UTIL}"`

I'm sure there's a neater way to fix the issue, but the quick fix worked for me.

* Desired solution
Fix STM32duino so that blanks in paths are supported out-of-the-box.

**Comment by fpistm** [comment]
I saw your issue in stm32duino bootloader repo.
Roger told you to open issue on the right repo. This is not this one.
You use Roger's core **Arduino_STM32**:

> /Users/gerard/Documents/My Data/ArduinoESP/hardware/**Arduino_STM32-master**/tools/macosx/maple_upload cu.usbmodemFA411 2 1EAF:0003 /var/folders/5l/fjrz26dn5710yvf5hgzlcvsw0000gn/T/arduino_build_316844/HelloWorld_STM32.ino.bin

So the right place is:
https://github.com/rogerclarkmelbourne/Arduino_STM32
