### ISSUE TITLE
STM32 support to ArduinoOTA library (help wanted)

### ISSUE THREAD

**Issue by jandrassy** [stm32duino/Arduino_Core_STM32#461]
For Arduino SAMD and for nRF5 there is [ArduinoOTA library](https://github.com/jandrassy/ArduinoOTA), enhanced and maintained by me. I plan STM32 support, but I have too many Arduino plans. Someone could add STM32 support. The InternalStorage class stores the uploaded binary into upper half of the flash and then a function running in RAM copies the binary to standard location and resets the MCU.

**Comment by fpistm** [comment]
Hi @jandrassy 
I guess you should also open an issue on your side referring  this one.
Currently, I could not managed this soon, I'm very too busy.
Anyway if an other contributor(s) could hep, I will be happy to help/support him/them.

**Comment by fpistm** [comment]
@jandrassy 
As there is an issue open to the Library, this should be tracked in this one.
Here this is mostly for issue with the core.
A topic about this can be open in the forum to discuss about it in the [STM32 CoreLibraries & Hardware](https://www.stm32duino.com/viewforum.php?f=39)

**Comment by jandrassy** [comment]
I made support for F1xx
