### ISSUE TITLE
[F4] I2C broken since last STM32F4 HAL update

### ISSUE THREAD

**Issue by charlie1024** [stm32duino/Arduino_Core_STM32#463]
_[Edit: transferred from stm32duino/STM32RTC]_

Hello,
I recently seen the board library was updated some days ago and the HAL feature was newly implemented.
I thought that with the new master branch board platform the new library will work, so with my Nucleo-F411RE I tried to operate the new library.

It worked without I2C. I use D14/D15(I2C1) and if I connect any I2C device, then the MCU goes to forever sleep(all codes are stopped). 

This code shows:
```
#include <Wire.h>
#include <STM32RTC.h>
STM32RTC& rtc = STM32RTC::getInstance();

void setup() {
  // put your setup code here, to run once:
  rtc.setClockSource(STM32RTC::LSE_CLOCK);
  rtc.begin(false); // initialize RTC 24H format

  if (!rtc.isTimeSet()) {
    rtc.setTime(0, 0, 0);
    rtc.setDate(1, 1, 19); // fallback
  }
  pinMode(LED_BUILTIN, OUTPUT);

  Wire.begin();

  Wire.beginTransmission(0x50);
  Wire.write(0);
  Wire.endTransmission();
}

void loop() {
  // put your main code here, to run repeatedly:
  delay(500);
  digitalWrite(LED_BUILTIN, !digitalRead(LED_BUILTIN));
}
```

0x50 means the EEPROM device and I just wrote a waste data to the line, so there must be no problem.
However If I use this code with any I2C device connected, F411RE just halts and not respond for anything(interrupts are all stopped too).

Couldn't be the new library used yet? Or is this a bug?

Thank you.

**Comment by fpistm** [comment]
@charlie1024,
I confirm this is a bug in the core since the last HAL update for F4.

**Comment by fpistm** [comment]
As a workaround you can revert those 2 commits:
https://github.com/stm32duino/Arduino_Core_STM32/commit/df4966143edb3811c7f94fb906193417b9ccd4fb
https://github.com/stm32duino/Arduino_Core_STM32/commit/0e8722f4ffa6e18033f9b061b6c5bd93353e06de

**Comment by charlie1024** [comment]
I tried to implement new RTC feature with [RTC] Avoid reset time after low power mode #442 and that did work in 1.5.0 platform. I hope the bug resolved. Thank you for assistance.

**Comment by fpistm** [comment]
Of course this will be resolved ;)
Moreover there is a workaround to not block user who want use the master.

**Comment by fpistm** [comment]
Issue found and fixed.
