### ISSUE TITLE
Problems with EEPROM.read() on L476RG

### ISSUE THREAD

**Issue by Adminius** [stm32duino/Arduino_Core_STM32#47]
i've tried to use a eeprom_clear demo sketch, but if i upload it, LED stays off.

Then i tried to read a EEPROM:
```
#include <EEPROM.h>

void setup() {
  Serial.begin(115200);
  Serial.print("EEPROM Size: ");
  Serial.println(EEPROM.length()); //it works with only with delay(10);
  delay(10); 
  Serial.print("Data: ");
  Serial.println(EEPROM.read(0));
  Serial.println("I'm here"); //i've never seen this line :/
}
void loop() {}
```
Console output with delay(10);
`EEPROM Size: 16384
Dat`
without delay:
`EEP`

i use official core release 2017.06.2
Upload via Mass Storage.

**Comment by fpistm** [comment]
Tested on L476:

- [ ] eeprom_clear
- [ ] eeprom_crc
- [ ] eeprom_get
- [ ] eeprom_iteration
- [ ] eeprom_put
- [ ] eeprom_read
- [ ] eeprom_update
- [ ] eeprom_write

**Comment by Adminius** [comment]
thx. no more problems 👍
