### ISSUE TITLE
Re-evaluate interrupt priority values

### ISSUE THREAD

**Issue by benwaffle** [stm32duino/Arduino_Core_STM32#472]
I am unable to use uart (via `printf`) in interrupt handlers such as the i2c handler (via `Wire.onRequest`).

**Describe the solution you'd like**
I am not sure about all the supported devices, but on the STM32F103, the subpriority is ignored because NVIC_PRIORITYGROUP_4 is used. Currently, the I2C interrupts are set to preemption priority 0. The USART1 preemption priority is also 0. This means that using UART in an interrupt handler will never exit, because HAL_UART_Transmit requires the USART interrupt.

On the other hand, this may be a good idea because using printf() inside an interrupt handler is slow, but interrupt handlers should be really fast.

Currently I can manually do this:
```c
Wire.begin(0x50);
HAL_NVIC_SetPriority(I2C1_ER_IRQn, 1, 0);
HAL_NVIC_SetPriority(I2C1_EV_IRQn, 1, 0);
HAL_NVIC_SetPriority(USART1_IRQn, 0, 0); // usart now has higher priority than i2c
```

Perhaps we should take a look at all of the interrupt priorities in the code base and decide on a global ordering.

**Comment by fpistm** [comment]
It's funny, I just watched this point this week. I even asked @LMESTM  what were the rules on mbed if any :)

In a general way, I think, only systick should be at 0.
