### ISSUE TITLE
Unable to build after installing the core thanks boards manager (STM32L432KC)

### ISSUE THREAD

**Issue by cloudtom** [stm32duino/Arduino_Core_STM32#489]
Arduino:1.8.9 (Windows Store 1.8.21.0) (Windows 10)
Error while detecting libraries included by C:\Users\w\AppData\Local\Temp\arduino_build_540589\sketch\Blink.ino.cpp
C:\\Users\\w\\AppData\\Local\\Temp\\arduino_build_540589\\preproc\\ctags_target_for_gcc_minus_e.cpp"
arm-none-eabi-g++: error: CreateProcess: No such file or directory

exit status 1

**Comment by fpistm** [comment]
Hi @cloudtom, how did you install the core?
It seems you do not have the arm gcc toolchains installed.

**Comment by cloudtom** [comment]
I have already instal the core as the procedure in the Getting Started page.
![OpenedWithImage](https://user-images.githubusercontent.com/17269580/55345036-8bb85900-54e1-11e9-9fd3-7e0f052efa7f.png)

**Comment by fpistm** [comment]
Well hard to tell what's going wrong.
I've started to use the Arduino IDE 1.8.9 and do not see any issue.
Is it a fresh Arduino install? If yes could you try to start from scratch? or clean up your install.
You could also check if all packages are well installed (Core, Tools, CMSIS and arm none eabi).

**Comment by cloudtom** [comment]
Could you tell me how to check if all packages are well installed. I don't know how to check because they are installed by Ardunio IDE.

**Comment by fpistm** [comment]
https://www.arduino.cc/en/guide/environment#toc13
Extract:

> Support for third-party hardware can be added to the hardware directory of your sketchbook directory. Platforms installed there may include board definitions (which appear in the board menu), core libraries, bootloaders, and programmer definitions. 

Sketchbook path are in the preferences menu.
Other links:
https://www.arduino.cc/en/hacking/preferences

You could also try a standalone version of the Arduino IDE:
Download archive install (zip).
Extract it and create a folder name "portable" inside the Arduino directory. Then all stuff will be put in portable directory (sketch books, packages and libraries install, preferences)
All are explained here: https://www.arduino.cc/en/Guide/PortableIDE

**Comment by fpistm** [comment]
Here details of where are the sources: https://github.com/stm32duino/wiki/wiki/Where-are-sources

**Comment by cloudtom** [comment]
The problem was solved after I installed the standalone version of the Arduino IDE. Thank you for your help!

**Comment by fpistm** [comment]
@cloudtom welcome.
Anyway this should work on the default installed. Probably an Arduino IDE issue. (cache, issue during install,...)

**Comment by cloudtom** [comment]
Yes, I think it is an Ardunio IDE issue, maybe it is because I was using the Windows Store version? Just now, I help my classmate to install the core on his computer. It is successful. And didn't meet any problem. And his Ardunio is default version.

**Comment by fpistm** [comment]
Note that for your case it is simply to use the standalone version, as you can get it on an USB key then simply copy where you want on several computer.
