### ISSUE TITLE
What is a "core"?

### ISSUE THREAD

**Issue by drelephant** [stm32duino/Arduino_Core_STM32#490]
I don't already have an account on the stm32duino forum, so I can't post there, but I'm asking because I saw [this post](https://www.stm32duino.com/viewtopic.php?f=39&t=4032).

Can someone explain or link to what a "core" is, what the different cores for STM32 are, and how they differ?

**Comment by fpistm** [comment]
Hi @drelephant ,
https://www.arduino.cc/en/guide/cores

Here some details about STM32 cores available
http://stm32duino.com/viewtopic.php?f=2&t=3111
This is not exhaustive.

**Comment by fpistm** [comment]
@drelephant 
does this answer your question?

**Comment by drelephant** [comment]
I think it does, thank you very much!
