### ISSUE TITLE
How to manually update packages?

### ISSUE THREAD

**Issue by xC0000005** [stm32duino/Arduino_Core_STM32#495]
In #491, it's mentioned we'll need to manually update our packages (I have my repo symlinked to the Arduino folder so I can pull updates in directly). I see where the CMSIS / GCC pacakages are. Is there any guide to where they should be put or unzipped?

**Comment by fpistm** [comment]
You can use the dev branch of the BoardManagerFiles repo: 
https://github.com/stm32duino/BoardManagerFiles/raw/dev/STM32/package_stm_index.json
And then symlink again

**Comment by fpistm** [comment]
Is it ok @xC0000005 ?

**Comment by xC0000005** [comment]
Yes sir. Worked just fine, thank you.
