### ISSUE TITLE
[New"Serial" and "Serial1" both  were declared on  same pins.. how to use "Serial" and "Serial1" lines individually Variant]

### ISSUE THREAD

**Issue by DeadSHoT555** [stm32duino/Arduino_Core_STM32#497]
**Board description (please complete the following information):**
 - Name: [e.g. DISCOVERY F769NI]
 - Link to all relevant information:
   * Documentations
   * Schematics
   * Where this hardware can be purchased
  * ...

**Note that user can add a STM32 based board following this [wiki](https://github.com/stm32duino/wiki/wiki/Add-a-new-variant-(board))**

Any contribution is welcome, so do not hesitate to submit a PR.

**Comment by DeadSHoT555** [comment]
![IMG_20190412_143030_161](https://user-images.githubusercontent.com/39310462/56025333-8f44af00-5d2f-11e9-91f8-e6af9bc4b511.jpg)
when i am using Serial1 it is printing on the monitor

**Comment by DeadSHoT555** [comment]
![IMG_20190412_143103_704](https://user-images.githubusercontent.com/39310462/56025378-a2577f00-5d2f-11e9-820a-ee97c4aedcb4.jpg)
when i am using Serial  again it is prining on serial monitor

**Comment by DeadSHoT555** [comment]
![IMG_20190412_143142_902](https://user-images.githubusercontent.com/39310462/56025436-bac79980-5d2f-11e9-97e1-d9e91a93b730.jpg)
![IMG_20190412_143140_352](https://user-images.githubusercontent.com/39310462/56025437-bb603000-5d2f-11e9-929e-0cae72bed5c7.jpg)
when i am using both the last declared one is getting active.hereby it is concluded that both "Serial" and "Serial1" pins were declared on same pins

**Comment by fpistm** [comment]
Right, this is normal.
Serial is just a define on the default Serialx to use or SerialUSB

**Comment by fpistm** [comment]
Why new variant?

**Comment by DeadSHoT555** [comment]
in the mean while i want to communicate with gps with "serial1"  and serialMonitor with "Serial" then how to declare two individual commn lines
OS: [ Windows10]
Arduino IDE version: [1.8.9]
STM32 core version: [1.5.0]
Tools menu settings [Newlib nano(default)]
Upload method: [serial]
Board (Generic STM32F1 Series):
Name: [BluePill F103C8]

**Comment by fpistm** [comment]
This is linked to how you wire your hardware.

**Comment by DeadSHoT555** [comment]
![IMG_20190412_170650_008](https://user-images.githubusercontent.com/39310462/56034613-662f1900-5d45-11e9-8fe6-5a616c0dcbc8.jpg)
as per the picture "Serial"  TX and RX is on A9 and A10  and  "Serial1"   TX and RX  is on A2 AND A3

**Comment by DeadSHoT555** [comment]
thank you 
i got it to work now

**Comment by fpistm** [comment]
`USART1` is on A9/A10 ans `USART2` on A2/A3.
Then by default `Serial1` is instantiate and `Serial` mapped to it and use `USART1`.
Then to use `Serial2`, it has to be instantiate using `-DENABLE_HWSERIAL2` or `HardwareSerial Serial2(PA3, PA2);`

Note:
`Serial` is the generic serial instance name.
`Serialx` is only a name, you can use the name you want.

For example, in your case, if you connect GPS on the `USART2`:
`HardwareSerial SerialGPS(PA3, PA2);`
And then use default `Serial` for monitor.
