### ISSUE TITLE
[EEXTR_F030_V1] Wrong HSE value?

### ISSUE THREAD

**Issue by fpistm** [stm32duino/Arduino_Core_STM32#516]
Hi  @ghent360 
Regarding  EEXTR_F030_V1 schematics it seems HSE is 8MHz:
![image](https://user-images.githubusercontent.com/20641798/57214564-a69f5100-6fea-11e9-9cb2-5b242a8b4999.png)

but in:
https://github.com/stm32duino/Arduino_Core_STM32/blob/5e2e32ab4f79ffbf9401eb2fc68ed403e974f145/variants/EEXTR_F030_V1/stm32f0xx_hal_conf.h#L86

what is the good value? `SystemClock_Config` should probably check also.

**Comment by fpistm** [comment]
Seems 16000000is the good value as discussed about it here:
https://github.com/stm32duino/Arduino_Core_STM32/pull/397#discussion_r244095376
So schematics is not up to date, right?

**Comment by ghent360** [comment]
Correct. I was planning to use 8Mhz, but had a stack of 16MHz crystals
laying around, so ended up with those.

**Comment by fpistm** [comment]
Ok. Thanks.
