### ISSUE TITLE
twi: why use non-blocking functions?

### ISSUE THREAD

**Issue by benwaffle** [stm32duino/Arduino_Core_STM32#520]
For example, in `i2c_master_write`, you call `HAL_I2C_Master_Transmit_IT()` and then busy wait until `HAL_I2C_GetState() == HAL_I2C_STATE_READY`.  Why not just use `HAL_I2C_Master_Transmit()`, the blocking function?

**Comment by fpistm** [comment]
IIRW, this was introduce to not block.
https://github.com/stm32duino/Arduino_Core_STM32/commit/2e9dc4dad770750996824ff4534673554a5d8b5c

**Comment by VVESTM** [comment]
Yes, we introduce this in order to be able to use I2C and SPI in the same time. With the blocking functions, there was too much delay in the SPI.

**Comment by fpistm** [comment]
Any update on this?

**Comment by benwaffle** [comment]
Why would this make a difference? As long as the interrupt priorities are right, the SPI interrupts can occur while I2C is running. Do we know where the delays came from?

**Comment by uzi18** [comment]
maybe we need just add setNonblocking(true)

**Comment by VVESTM** [comment]
Trying to get back on this subject... This code has been introduced by #115 .
I made a mistake on my previous comment. The delay was introduced in I2C instead of SPI...

The use case was the following : 
    * on L475 IoT board, sensors are connected on I2C and BTLE on SPI (there is an IT on BTLE Rx)
    * transfer on going on I2C, in polling mode.
    * data available on BTLE, and so, an SPI transfer is launched on BTLE IT context.
    * I2C transfer is blocked waiting for SPI ends. 
	=> this was making an error on I2C and we reach a timeout.

By replacing the polling mode by IT mode on I2C transfer, we can be interrupted by SPI.

**Comment by fpistm** [comment]
@benwaffle is @VVESTM  answer your question?
Thanks in advance

**Comment by benwaffle** [comment]
How is the timeout check different? Whether in polling or interrupt mode, it calls `HAL_GetTick()` to get the current time, and that interrupt fires in every case (even if SPI or I2C is running). So why would it timeout in one case and not in another?

**Comment by fpistm** [comment]
Well, in the original case, I2C was not in IT mode.
Then when the BTLE request a RX thanks an EXTI, the callback was called immediately. If this happen during the `HAL_I2C_Master_Transmit()`, then this cause I2C transfer to fail.
Moving to `HAL_I2C_Master_Transmit_IT()` allowed to not break the I2C transfer as I2C has higher prio than the EXTI. That's all.

**Comment by fpistm** [comment]
Considered answered.
