### ISSUE TITLE
how to use watchdog timer (iwdg) for blue pill STM32F103C8

### ISSUE THREAD

**Issue by leop123** [stm32duino/Arduino_Core_STM32#533]
I need to use a watchdog timer (iwdg) in my program. Is there any library that supports this?
I am new to STM32 and hope for help. Sorry if I violate any rule in Github since I am also new to Github

**Comment by RickKimball** [comment]
I was wondering how to do thing with the bluepill too and I asked on the forum on www.stm32duino.com and got an answer. Asking on github might not be the best way to get people to help you.

**Comment by leop123** [comment]
Okay, thanks
