### ISSUE TITLE
still no support for USB Bootloaders for STM32F1

### ISSUE THREAD

**Issue by crackwitz** [stm32duino/Arduino_Core_STM32#534]
I'm using v1.5.0 of your package. That is the latest release. According to your Wiki, the Boards Manager way should work. It does not. I am given only these three options, neither of which is upload via USB.

![image](https://user-images.githubusercontent.com/7065108/58769761-71b2f980-85aa-11e9-8ffa-77991f16527d.png)

Have you given up support for Maple Minis, or upload via USB?

**Comment by fpistm** [comment]
This is available with the repo. Thanks the board manager, this will be availaible with the 1.6.0. See #525.
