### ISSUE TITLE
Cant find STM32 Cores in the boards manager

### ISSUE THREAD

**Issue by paulxavier86** [stm32duino/Arduino_Core_STM32#538]
I have tried to install the STM32 Cores in the arduino IDE. I added the link in the preferences but in boards manager cant find the stm32 cores. I tried in 1.8.7 and 1.8.9 arduino

**Comment by fpistm** [comment]
Hi @paulxavier86 
The STM32 core is easy to find if you select `contributed` in the `Type` list.
![image](https://user-images.githubusercontent.com/20641798/59147352-8b18d300-89fa-11e9-8e45-4aadf3326f73.png)
or search `stm32` if you let `All`:
![image](https://user-images.githubusercontent.com/20641798/59147363-bbf90800-89fa-11e9-8307-1c8264a412e8.png)

If you do not find it, then check the link you add:
https://github.com/stm32duino/BoardManagerFiles/raw/master/STM32/package_stm_index.json
If it does not work check your internet connection.

**Comment by paulxavier86** [comment]
Thanks for the reply.
The error was real inspite  of all your suggestions. What worked was that i deleted the arduino15 folder from mydocuments and tried again.

now it works.

**Comment by fpistm** [comment]
Yes, sometimes, some local files are corrupted. I don't know why but relies to Arduino IDE.
Fine you find a solution. Note that sometimes, only cleaning some files in the local arduino is enough instead of delete all.

**Comment by poetlusint692** [comment]
Master!!
I found STM32 Core in the boards Manager but, it can't install. Why? Please.....

**Comment by fpistm** [comment]
> Master!! I found STM32 Core in the boards Manager but, it can't install. Why? Please.....

Proxy issue? Hard to tell without more information
