### ISSUE TITLE
__UNALIGNED_UINT32_READ() not defined for stm32l4xx_ll_usb.c

### ISSUE THREAD

**Issue by adammunich** [stm32duino/Arduino_Core_STM32#546]
When building the USB driver for the F4 series, (or F7), __UNALIGNED_UINT32_READ(), used in stm32l4xx_ll_usb.cis not found. Grep fails to find the string in the whole repository too.

**Comment by fpistm** [comment]
How do you get this issue?
stm32l4xx_ll_usb.c is not build when building for F4 or F7 as it is for L4.

**Comment by fpistm** [comment]
Closed as no feedback from OP.
