### ISSUE TITLE
I want to change frequency of STM32 pwm pin

### ISSUE THREAD

**Issue by gauri8427** [stm32duino/Arduino_Core_STM32#551]
**Is your feature request/improvement related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context, example or screenshots about the feature request here.

Any contribution is welcome, so do not hesitate to submit a PR.

**Comment by fpistm** [comment]
Hi  @gauri8427 
please use the forum for this kind of question as explained here : 
https://github.com/stm32duino/Arduino_Core_STM32#troubleshooting

_For question, support, ...,  you could submit a topic on the [stm32duino forum](http://stm32duino.com):_

 * _questions on the [STM32 Core](http://stm32duino.com/viewforum.php?f=48)_
 
 * _bugs/enhancements on the [STM core: Bugs and enhancements](http://stm32duino.com/viewforum.php?f=49)_ 

To answer your question:
https://github.com/stm32duino/wiki/wiki/API#frequency

**Comment by fpistm** [comment]
Considered answered.

**Comment by gauri8427** [comment]
But this didn't work for me

**Comment by fpistm** [comment]
@gauri8427,
open a new topic on the forum.
As mention this is not the right place to ask support and be more precise about your config:
host OS, IDE version, core version, board used,...

**Comment by sixtyfive** [comment]
This is the first hit on Google for "arduino stm32 pwm frequency" btw.
