### ISSUE TITLE
[F1] How do I debug ADC / analogRead() not working?

### ISSUE THREAD

**Issue by benwaffle** [stm32duino/Arduino_Core_STM32#552]
**Describe the bug**
analogRead() is returning incorrect / garbage values. A multimeter between PA2 and GND shows the correct value.

**To Reproduce**
```cpp
#include <Arduino.h>

void setup() {
    Serial.begin(923076);
    pinMode(PA2, INPUT_ANALOG);
    analogReadResolution(12);
}

void loop() {
    Serial.print(analogRead(PA2) / 4096.0 * 3.3);
    Serial.println(" V");
    delay(200);
}
```

1. Run code
2. Connect an analog input to PA2
3. See incorrect value

**Expected behavior**
Expected that code reads correct voltage as measured by multimeter.

**Desktop:**
 - OS: Mac
 - STM32 core version: 1.6.1
 - Upload method: STLink

**Board:**
 - Name: STM32F103C8T6 (Bluepill)

**Comment by fpistm** [comment]
Hi @benwaffle,
I've tested quickly with my BP and this seems correct.
Using  Fading example with DAC of an other board connected to PA2:
![image](https://user-images.githubusercontent.com/20641798/60383166-dbb9a400-9a6d-11e9-851d-74b5acd1a5c8.png)

Note: value change each 30ms, so I use your sketch with 15ms delay.

To debug you can try one of those methods:
https://github.com/stm32duino/wiki/wiki/How-to-debug

**Comment by fpistm** [comment]
Sorry misclicked when comment.

**Comment by fpistm** [comment]
@benwaffle any feedback?

**Comment by fpistm** [comment]
Bump

**Comment by benwaffle** [comment]
Sorry, I've been working on other things. Most recently, I was able to get stable-ish values, but still getting random spurts +/- 10 mV. How accurate can the ADC get with the arduino layer?

**Comment by AnHardt** [comment]
Mostly the noise you see is independent from the used core.
Mostly it comes down to the question: "How well is the noise protection of the analog circuitry. External. on board and inside the processor."
If you see single spikes, try to correlate them to events. Be prepared to find the source in: "Switching off the lights two rooms away."
Always think about hard- and soft-ware filtering the signals. Know and respect the [Nyquist–Shannon sampling theorem](https://en.wikipedia.org/wiki/Nyquist%E2%80%93Shannon_sampling_theorem) and its consequences.

**Comment by AnHardt** [comment]
Arduino analogRead() is notorious for its slowness.
Always preparing the pin, setting up the ADC, initialising the conversion, busy waiting for success, reading and returning the result costs time and is the price you have to pay when you try to make the use simple. That's the Arduino concept.
If you want it fast, bypass Arduino completely and split anologRead() to its functions. With many of the ST processors you can read frequencies up to some MHz.

**Comment by AnHardt** [comment]
If i remember correctly the analog circuitry on the 'Blue Pill' is far from 'well made'.

**Comment by fpistm** [comment]
@benwaffle 

As @AnHardt told, `analogRead()` is very limited.

You can try customize on sample time:
You should follow this wiki page to redefine them:
https://github.com/stm32duino/wiki/wiki/Customize-build-options-using-build_opt.h

`-DADC_SAMPLETIME=ADC_SAMPLETIME_55CYCLES_5`

With one of those possible values (default: `ADC_SAMPLETIME_13CYCLES_5`):
https://github.com/stm32duino/Arduino_Core_STM32/blob/5cc75ca9d4ef637bc0627ee30bb4bbf7865ab902/system/Drivers/STM32F1xx_HAL_Driver/Inc/stm32f1xx_hal_adc.h#L293-L300

Note: you should have at least Core  version 1.6.0.

**Comment by fpistm** [comment]
No feedback since a week.
analogRead is working, value precision with analogRead is dependent to several hardware factor and of the software implementation (single ended read).
Better precision could be achieved by implementing its own read using HAL/LL, this could be part of #5

**Comment by benwaffle** [comment]
Looks like I had noise from the power supply.
