### ISSUE TITLE
Is there any library to run I2C LCD Display with STM32F401RE Nucleo using **Arduino IDE**.....I searched through all the forums but didn't get any solution.....

### ISSUE THREAD

**Issue by gauri8427** [stm32duino/Arduino_Core_STM32#557]
**Is your feature request/improvement related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context, example or screenshots about the feature request here.

Any contribution is welcome, so do not hesitate to submit a PR.

**Comment by fpistm** [comment]
Hi @gauri8427 
see my comment here:
https://github.com/stm32duino/Arduino_Core_STM32/issues/551#issuecomment-508368621
