### ISSUE TITLE
USB library

### ISSUE THREAD

**Issue by sstaub** [stm32duino/Arduino_Core_STM32#559]
Can you add an USB library like the Mbed library https://github.com/ARMmbed/mbed-os/tree/master/usb/device ? Using the native USB port would be a great feature.

**Comment by fpistm** [comment]
There is already a USB device support based on [STM32_USB_Device_Library](https://github.com/stm32duino/Arduino_Core_STM32/tree/master/system/Middlewares/ST/STM32_USB_Device_Library).

Could you be more precise on what do you expect?

**Comment by kgamecarter** [comment]
I think more examples will be fine.
Like examples of maple mini stm32duino.

![image](https://user-images.githubusercontent.com/3646532/60764990-b2c88d00-a0c5-11e9-87a7-78b5c6b43c84.png)

**Comment by sstaub** [comment]
There are many things I miss, because there is no API like mbed [https://os.mbed.com/docs/mbed-os/v5.13/apis/usb.html](url) :
- Assigning an USBxxx class to USB RX/TX pins (e.g. PA_11/12 for NULEO-L423KC)
- VID/PID settings
- blocking / nonblock
Generell it should possible to work with the build in USB instead of the st-link debugging interface

**Comment by ahuxtable** [comment]
No examples on how to use the Keyboard and mouse features, and no joystick support like Roger Clark has.

**Comment by fpistm** [comment]
> No examples on how to use the Keyboard and mouse features, and no joystick support like Roger Clark has.

USB keyboard and mouse are functional, enable` HID (keyboard and mouse)` and use Arduino built-in example available in `09. USB` menu.

**Comment by fpistm** [comment]
Track in #687
