### ISSUE TITLE
Mega2560 external interrupt pins are not enough, how to redefine other pins as external interrupt pins

### ISSUE THREAD

**Issue by firstnamenie** [stm32duino/Arduino_Core_STM32#560]
Mega2560 external interrupt pins are not enough, how to redefine other pins as external interrupt pins

**Comment by fpistm** [comment]
@firstnamenie 
This GitHub repository is for STM32 based boards not for Mega2560.
You should open an issue here:
https://github.com/arduino/ArduinoCore-avr
