### ISSUE TITLE
[New Variant]STM32F469iDiscovery

### ISSUE THREAD

**Issue by HutTheNut** [stm32duino/Arduino_Core_STM32#571]
Yet another request :-)

**Comment by fpistm** [comment]
Well I could not add all variant :)
I've done the G4 was a new serie and required to add HAL and CMSIS.

Please refer to this wiki:
https://github.com/stm32duino/wiki/wiki/Add-a-new-variant-(board)

I will please to review the PR 😉

**Comment by fpistm** [comment]
Why close the issue?
It still a valid request, maybe I will have time to do it or a contributor.
What I would tell if that I currently do not have time to add all variant ;)

**Comment by fpistm** [comment]
As there is more and more support request for new variant, all are grouped in a single issue to ease tracking: #722.
