### ISSUE TITLE
black F407VG board

### ISSUE THREAD

**Issue by nopnop2002** [stm32duino/Arduino_Core_STM32#572]
I use this black F407VG board.
![VGT6-1](https://user-images.githubusercontent.com/6020549/61751626-ea347a80-ade3-11e9-882e-14aced3a8a0c.JPG)

I wrote a sketch using Nucleo.

Wirering   

|Nucleo||F407VG|
|:-:|:-:|:-:|
|3,3V|--|3.3V|
|GND|--|GND|
|SWDIO|--|PA13|
|SWCLK|--|PA14|

![VGT6-2](https://user-images.githubusercontent.com/6020549/61751637-f0c2f200-ade3-11e9-9c5b-752cf6eab743.JPG)

The parameters for writing are as follows.
![VGT6-3](https://user-images.githubusercontent.com/6020549/61751643-f4ef0f80-ade3-11e9-9bcd-ca44116dc882.JPG)

	      -------------------------------------------------------------------
	                       STM32CubeProgrammer v2.0.0                  
	      -------------------------------------------------------------------

	ST-LINK SN  : 066EFF534951775087182628
	ST-LINK FW  : V2J33M25
	Voltage     : 3.26V
	SWD freq    : 4000 KHz
	Connect mode: Under Reset
	Reset mode  : Hardware reset
	Device ID   : 0x413
	Device name : STM32F405xx/F407xx/F415xx/F417xx
	Flash size  : 63.999 MBytes
	Device type : MCU
	Device CPU  : Cortex-M4

	Memory Programming ...
	Opening and parsing file: Blink.ino.bin
	  File          : Blink.ino.bin
	  Size          : 16412 Bytes
	  Address       : 0x08000000 

	Erasing memory corresponding to segment 0:
	Erasing internal memory sectors [0 1]
	Download in Progress:

	File download complete
	Time elapsed during download operation: 00:00:00.719

	RUNNING Program ... 
	  Address:      : 0x8000000
	Application is running
	Start operation achieved successfully

The writing ends normally and the black board starts to work.
However, if i turn the Nucleo off and on again, the black board will not work.
Do you have any advice? ?

**Comment by fpistm** [comment]
Hi @nopnop2002 
I don't see any jumper on Boot pins.
I guess you restart in STM32 bootloader mode after power off the Nucleo then power on.

It works when you flash because the STM32CubeProgrammer start the program automatically.

**Comment by nopnop2002** [comment]
OH! Thank you.
When i put a jumper like this page, it started to work correctly.

https://www.instructables.com/id/Upload-Arduino-Sketch-to-STM32F407-Board/

I will close this issues.

**Comment by fpistm** [comment]
Welcome

**Comment by BennehBoy** [comment]
Not related to the issue, but be VERY CAREFUL if using the USB connector on
the diymroe boards, they do not have a good mechanical connection to the
board, I would suggest some epoxy and perhaps more solder to better anchor
the connector - I learned this the hard way.

**Comment by nopnop2002** [comment]
@BennehBoy 
Thank you for your advice.
