### ISSUE TITLE
<Question> Flash size  : 63.999 MBytes

### ISSUE THREAD

**Issue by nopnop2002** [stm32duino/Arduino_Core_STM32#578]
I compiled STM32F407G-DISC using STM32CubeProgrammer(SWD).
It is mounted F407VGT6 chip, and it has 1M flash.
But The Flash size is displayed as 63.999 Mbytes.
What is 63.999 MBytes.

	      -------------------------------------------------------------------
	                       STM32CubeProgrammer v2.0.0                  
	      -------------------------------------------------------------------

	ST-LINK SN  : 066BFF313236484D43164243
	ST-LINK FW  : V2J33M25
	Voltage     : 2.91V
	SWD freq    : 4000 KHz
	Connect mode: Under Reset
	Reset mode  : Hardware reset
	Device ID   : 0x413
	Device name : STM32F405xx/F407xx/F415xx/F417xx
	Flash size  : 63.999 MBytes -----> *
	Device type : MCU
	Device CPU  : Cortex-M4

**Comment by fpistm** [comment]
@nopnop2002 
Right, I didn't see this before.
This is the output log of the STM32Cubeprogammer. I had the same with the v2.1.0.
Probably a bug of the tool anyway the board is flashed correctly.
As this issue is not related to the core. I close the issue.
