### ISSUE TITLE
LL_ADC_InitTypeDef error

### ISSUE THREAD

**Issue by DmitriyGrigorov** [stm32duino/Arduino_Core_STM32#579]
Hello! I am currently trying to use the LL libraries to configure the ADC in Arduino IDE 1.8.9, but there is an error in the initialization of the LL_ADC_InitTypeDef Function when compiling: 

C:\Users\...\Arduino\HAL_LL\HAL_LL.ino: In function 'void setup()':
HAL_LL:15:5: error: 'LL_ADC_InitTypeDef' was not declared in this scope
LL_ADC_InitTypeDef ADC_InitStruct = {0}; Though it seems to be connected all the necessary files.

Here is the code of the sketch:

`#include "stm32f4xx_ll_adc.h"
#include "stm32f4xx_ll_rcc.h"
#include "stm32f4xx_ll_bus.h"
#include "stm32f4xx_ll_system.h"
#include "stm32f4xx_ll_exti.h"
#include "stm32f4xx_ll_cortex.h"
#include "stm32f4xx_ll_utils.h"
#include "stm32f4xx_ll_pwr.h"
#include "stm32f4xx_ll_dma.h"
#include "stm32f4xx.h"
#include "stm32f4xx_ll_gpio.h"

void setup() 
{
    LL_ADC_InitTypeDef ADC_InitStruct = {0};
    LL_ADC_REG_InitTypeDef ADC_REG_InitStruct = {0};
    LL_ADC_CommonInitTypeDef ADC_CommonInitStruct = {0};
   //LL_ADC_CommonInitTypeDef ADC_CommonInitStruct;
  // put your setup code here, to run once:
   //__HAL_RCC_GPIOA_CLK_ENABLE();
   //LL_GPIO_SetPinMode(GPIOA, LL_GPIO_PIN_1, LL_GPIO_MODE_ANALOG);
   //LL_GPIO_SetPinOutputType(GPIOA, LL_GPIO_PIN_1, LL_GPIO_OUTPUT_PUSHPULL);
   LL_ADC_CommonInitTypeDef.CommonClock = LL_ADC_CLOCK_SYNC_PCLK_DIV2;
    ADC_InitStruct.Resolution = LL_ADC_RESOLUTION_12B;
  ADC_InitStruct.DataAlignment = LL_ADC_DATA_ALIGN_RIGHT;
  ADC_InitStruct.SequencersScanMode = LL_ADC_SEQ_SCAN_DISABLE;
  LL_ADC_Init(ADC1, &ADC_InitStruct);
  ADC_REG_InitStruct.TriggerSource = LL_ADC_REG_TRIG_SOFTWARE;
  ADC_REG_InitStruct.SequencerLength = LL_ADC_REG_SEQ_SCAN_DISABLE;
  ADC_REG_InitStruct.SequencerDiscont = LL_ADC_REG_SEQ_DISCONT_DISABLE;
  ADC_REG_InitStruct.ContinuousMode = LL_ADC_REG_CONV_SINGLE;
  ADC_REG_InitStruct.DMATransfer = LL_ADC_REG_DMA_TRANSFER_LIMITED;
  LL_ADC_REG_Init(ADC1, &ADC_REG_InitStruct);
  LL_ADC_REG_SetFlagEndOfConversion(ADC1, LL_ADC_REG_FLAG_EOC_UNITARY_CONV);
  LL_ADC_DisableIT_EOCS(ADC1);
  ADC_CommonInitStruct.CommonClock = LL_ADC_CLOCK_SYNC_PCLK_DIV2;
  ADC_CommonInitStruct.Multimode = LL_ADC_MULTI_INDEPENDENT;
  LL_ADC_CommonInit(__LL_ADC_COMMON_INSTANCE(ADC1), &ADC_CommonInitStruct);
}

void loop() {
  // put your main code here, to run repeatedly:

}`

Desktop:
 - OS: Windows 7 64-bit
 - Arduino IDE version: 1.8.9
 - STM32 core version: 1.6.1
 - Tools menu settings: Newlib Standard, Serial
 - Upload method: dfu

Board:
 - Name: DevEBox STM32F407VGT6
 - Hardware Revision: 3.0
 
Update: in build_opt.h add -DUSE_FULL_LL_DRIVER

**Comment by fpistm** [comment]
Right, thanks for feedback.
