### ISSUE TITLE
Finally Blue Pill R10 has been corrected

### ISSUE THREAD

**Issue by SRQJohnson** [stm32duino/Arduino_Core_STM32#580]
Just a quick Heads up, as STMduino seems to no longer exist.   The Chinese have finally corrected the dreaded R10 resistor on the Blue Pill.  These boards are the variety which has a rectangular white plastic reset button rather than the round metallic one.  I have tried to put in a photo, but have just started here.

A package from ebay China arrived today with 1.5 K resistors.
![Correct_R10](https://user-images.githubusercontent.com/30204907/61999358-31916400-b08d-11e9-8159-25cdd91a4e47.jpg)

**Comment by TByte007** [comment]
You are right - I just checked. It's not '103' anymore but something like '01C'  (not 125 like yours).

**Comment by fpistm** [comment]
Hi @SRQJohnson 
thanks for the info, anyway this is not the place for this kind of info.
I know the forum is currently down and this is the main issue.
You can add a Wiki page on the BluePill:
https://github.com/stm32duino/wiki/wiki
