### ISSUE TITLE
How to use SerialEvent ?

### ISSUE THREAD

**Issue by arminsalcin** [stm32duino/Arduino_Core_STM32#584]
Hello to all , 

So my question is how to use it , i want to use it with Serial1 but it doesnt work if i regulary define it in my code. So how i need to do it properly , and can i use Serial for debugging while using Serial1 for communicating with sensor and using SerialEvent1 .

If anyone can write some small simple example code that will be nice 
- I'm using stm32f103C in board "Generic STM32f103c"

Thanks !

**Comment by fpistm** [comment]
Hi @arminsalcin 
By default, if USB CDC is not enabled is not defined. `Serial1` is the same than `Serial`.
I guess you use USB CDC so Serial is `SerialUSB`.
To enable the `SerialEvent1()` for `Serial1`, add a `build_opt.h` file alongside your main .ino file with: `-DENABLE_HWSERIAL1`. This will define the `Serial1` instance using the first `USART1` instance found in the P`eripheralPins.c` of your variant.

This is in the wiki:
https://github.com/stm32duino/wiki/wiki/API#hardwareserial

**Comment by arminsalcin** [comment]
Okay , just to clearify im using bluepill board and programm it via ftdi connected to (PA9 , PA10) , and my sensor is connected to (PA2 , PA3) , in my code i use Serial1 to communicate with sensor and it work. 

So when i add `build_opt.h` like this :

``
#include <build_opt.h>
``
I get error no build_opt found..

So what can be problem ?

**Comment by arminsalcin** [comment]
Ok i think i realize what is problem with in include if i choose from STM32 board selected from submenu it compiles okay if i select from stm32duino.com it doesnt want to compile 

<img width="305" alt="Screen Shot 2019-07-29 at 8 55 22 PM" src="https://user-images.githubusercontent.com/11528055/62074695-97275100-b243-11e9-99f0-1c292291784a.png">

So i dont understand this thing  `-DENABLE_HWSERIAL1` how to write this in arduino ide ?

**Comment by fpistm** [comment]
https://github.com/stm32duino/wiki/wiki/Customize-build-options-using-build_opt.h

**Comment by arminsalcin** [comment]
Ok i manage to do it , so after this embedded i just use Serial1 as i would regulary , example Serial1.begin(9600)

**Comment by fpistm** [comment]
> Ok i manage to do it , so after this embedded i just use Serial1 as i would regulary , example Serial1.begin(9600)

Right

**Comment by arminsalcin** [comment]
Thank you after i make all to work i will leave example here and close issue

**Comment by fpistm** [comment]
Hi @arminsalcin 
before leave I made some sweep.
I think your question is answered. Feel free to update Wiki with your example if you want.

**Comment by jonghaboy** [comment]
i have followed this example but i get  "expected unqualified-id before '-' token

can anyone help?
the build_opt.h file only has the line "-denable_hwserial1" right?

**Comment by jonghaboy** [comment]
by the way i am using stm32f103c series

**Comment by fpistm** [comment]
@jonghaboy 
Please use the forum for support.
Anyway your syntax is not correct... it is case sensitive.

**Comment by jonghaboy** [comment]
> @jonghaboy
> Please use the forum for support.
> Anyway your syntax is not correct... it is case sensitive.

-DENABLE_HWSERIAL3
-PIN_SERIAL3_RX=PB11
-PIN_SERIAL3_TX=PB10

this is my code in build_opt.h
 it does not work

use forum to write a new case you mean?
