### ISSUE TITLE
BluePill on USB

### ISSUE THREAD

**Issue by KJansun** [stm32duino/Arduino_Core_STM32#588]
I did some attends to get the bluepill to working with the new core with USB upload method, instead of the rogier clarks core on usb. When uploading for the first time its looks all ok, but immediately after uploading the code Windows (10) gives a message it doesnt recognize the usb anymore and i'm also not able to upload again. comport dissapeared in Tools/Port. Only way to get it back to work is to flash the device via serial. my attempts: 

- Rogier clark core with upload method: Maple DFU 2.0
- New stm32duino  core with upload method: Hid bootloader 2.2
- Used different sketches, for example the standard BLINK sketch
- Used latest 2.2.1 core from here: https://github.com/Serasidis/STM32_HID_Bootloader
Error message: `Build-opties gewijzigd, alles wordt opnieuw gebuild
De schets gebruikt 16584 bytes (25%)  programma-opslagruimte. Maximum is 65536 bytes.
Globale variabelen gebruiken 1980 bytes (9%) van het dynamisch geheugen. Resteren 18500 bytes voor lokale variabelen. Maximum is 20480 bytes.

+-----------------------------------------------------------------------+
|         HID-Flash v2.2.1 - STM32 HID Bootloader Flash Tool            |
|     (c)      2018 - Bruno Freitas       http://www.brunofreitas.com   |
|     (c) 2018-2019 - Vassilis Serasidis  https://www.serasidis.gr      |
|   Customized for STM32duino ecosystem   https://www.stm32duino.com    |
+-----------------------------------------------------------------------+

> Trying to open the [COM9]...
> Unable to open the [COM9]
> Searching for [1209:BEBA] device...
#
> [1209:BEBA] device is found !
> Sending <reset pages> command...
> Flashing firmware...
. 1024 Bytes
. 2048 Bytes
. 3072 Bytes
. 4096 Bytes
. 5120 Bytes
. 6144 Bytes
. 7168 Bytes
. 8192 Bytes
. 9216 Bytes
. 10240 Bytes
. 11264 Bytes
. 12288 Bytes
. 13312 Bytes
. 14336 Bytes
. 15360 Bytes
. 16384 Bytes
. 17408 Bytes

> Done!
> Sending <reboot mcu> command...
> Searching for [COM9] ...
> Finish`

Rogier clark's core worked fine with his board installs, but i cant get the new core to work on a regular bluepill

**Comment by fpistm** [comment]
You have to enable USB CDC in USB support in the menu else you will not be able to upload again as it require USB CDC to send magic sequence
