### ISSUE TITLE
Serial.print using BLUE_F407VE_Mini

### ISSUE THREAD

**Issue by nopnop2002** [stm32duino/Arduino_Core_STM32#591]
When i used DIYMROE_F407VGT/BLACK_F407VE/BLACK_F407VG/FK407M1, Serial.print work fine.

![DIYMROE407-Serial1](https://user-images.githubusercontent.com/6020549/62418554-9d378a80-b6a6-11e9-845e-4587f51798c2.jpg)
![BlackF407-Serial1](https://user-images.githubusercontent.com/6020549/62418557-a7f21f80-b6a6-11e9-90cf-4bc093cd151b.jpg)
![FK407M1-Serial1](https://user-images.githubusercontent.com/6020549/62418558-aaed1000-b6a6-11e9-8a03-26e9b3886857.jpg)

But when i used BLUE_F407VE_Mini, Serial.print don't work.

![BLUE_F407VE_Mini](https://user-images.githubusercontent.com/6020549/62418559-b5a7a500-b6a6-11e9-80e7-0e587eb1d8ce.jpg)

What is wrong??

This is my sketch:

	#if defined(ARDUINO_DIYMROE_F407VGT) || defined(ARDUINO_BLACK_F407VE) || defined(ARDUINO_BLACK_F407VG) \
	 || defined(ARDUINO_BLUE_F407VE_Mini) || defined(ARDUINO_FK407M1)
	#if defined(ARDUINO_DIYMROE_F407VGT)
	#define MODEL "DIYMROE_F407VGT"
	#endif
	#if defined(ARDUINO_BLACK_F407VE)
	#define MODEL "BLACK_F407VE"
	#endif
	#if defined(ARDUINO_BLACK_F407VG)
	#define MODEL "BLACK_F407VG"
	#endif
	#if defined(ARDUINO_BLUE_F407VE_Mini)
	#define MODEL "BLACK_BLUE_F407VE_Mini"
	#endif
	#if defined(ARDUINO_FK407M1)
	#define MODEL "FK407M1"
	#endif
	#define S1 "PA9"
	#define S2 "PA2"
	#define S3 "PB10"
	HardwareSerial Serial2(PA3, PA2);
	HardwareSerial Serial3(PB11, PB10);
	#endif

	void setup() {

	  Serial.begin(115200);
	  if (S1 != "") Serial1.begin(115200);
	  if (S2 != "") Serial2.begin(115200);
	  if (S3 != "") Serial3.begin(115200);
	  Serial.println(String(MODEL) + ":Serial start");
	  if (S1 != "") Serial1.println(String(MODEL) + ":Serial1 start to " + String(S1));
	  if (S2 != "") Serial2.println(String(MODEL) + ":Serial2 start to " + String(S2));
	  if (S3 != "") Serial3.println(String(MODEL) + ":Serial3 start to " + String(S3));
	}

	void loop() {
	  Serial.println(String(MODEL) + ":Serial print");
	  if (S1 != "") Serial1.println(String(MODEL) + ":Serial1 TX to " + String(S1));
	  if (S2 != "") Serial2.println(String(MODEL) + ":Serial2 TX to " + String(S2));
	  if (S3 != "") Serial3.println(String(MODEL) + ":Serial3 TX to " + String(S3));
	  delay(5000);
	}

**Comment by edogaldo** [comment]
Looks like a crystal issue, you sure you are using [this board](https://www.ebay.com/itm/STM32F407VET6-STM32-ARM-Cortex-M4-Development-Board-System-Board-/173407441568?nav=SEARCH)? It should have a 25Mhz crystal while the others a 8Mhz one.

**Comment by nopnop2002** [comment]
I used a DIYMROE board.
I didn't know that there was such a difference.
I will close this issue.
