### ISSUE TITLE
STM32F103C8T6 (BluePill) I2C1 not working

### ISSUE THREAD

**Issue by GianniDPC** [stm32duino/Arduino_Core_STM32#599]
I2C1 does not seem to work for me, I2C2 does seem to work as expected.

I used the I2C scanner and a TC74 temperature sensor to test.

Using I2C2 the address of the sensor is detected, when using I2C1 it tells me that no devices are found.

Can anyone confirm this? It could also be that my board is defective I guess.

I am using a STM32F103C8T6 board with the latest STM32duino release 1.6.1.

**Comment by nopnop2002** [comment]
I2C1 of STM32F103C8T6 works fine.
SDA=PB7
SCL=PB6

Maybe you need a PullUp resistor

![i2c](https://user-images.githubusercontent.com/6020549/63218308-b6eecc80-c192-11e9-81bb-9bf1d0025a09.jpg)

**Comment by GianniDPC** [comment]
@nopnop2002  already tried, I guess I have a bad solder somewhere on the chip connecting to the pcb.
