### ISSUE TITLE
Can't update to 1.7.0

### ISSUE THREAD

**Issue by nopnop2002** [stm32duino/Arduino_Core_STM32#601]
I'm using 1.6.1.
I can't update to 1.7.0  using board manager.

![ST-Core](https://user-images.githubusercontent.com/6020549/63218376-3fba3800-c194-11e9-840d-e7e8ff9f9157.jpg)

Do you have any help?

**Comment by fpistm** [comment]
There is no 1.7.0 released yet.

**Comment by GianniDPC** [comment]
Would it be possible to add dev release to the package_stm_index.json?

**Comment by fpistm** [comment]
Doing dev release would take times as need to update regurlarly. Best option is to use directly the repo as described in the wiki.

**Comment by nopnop2002** [comment]
OK
I'm waiting release.
