### ISSUE TITLE
How Reset/Restart Board in Software

### ISSUE THREAD

**Issue by glowlabs** [stm32duino/Arduino_Core_STM32#607]
Is there a command to restart the board? If so, what is it?

**Comment by fpistm** [comment]
Hi @glowlabs,
You can use:
`NVIC_SystemReset();`

**Comment by glowlabs** [comment]
Works perfect, thanks!

**Comment by BRoboticsSHADO** [comment]
Hi

Did you guys use `NVIC_SystemReset();` in Arduino IDE? Any examples that i can refer to? As i plan to do the same on bluepill board (STM32F103C8).

Best,
Samuel

**Comment by fpistm** [comment]
Simply use it in your code.

**Comment by BRoboticsSHADO** [comment]
Hi @fpistm 

Ok, i will try it out. Thank you

Best,
Samuel
