### ISSUE TITLE
STM32F030K6T6 supported?

### ISSUE THREAD

**Issue by buglyobalazs** [stm32duino/Arduino_Core_STM32#619]
HI guys!

Is this MCU is supported? i did not see it but a family member did. Any1 can help me with this? 
STM32F030K6T6 
STM32F030F4P6 -- this is supported.

regards

Balazs Buglyó

**Comment by fpistm** [comment]
Hi @buglyobalazs 
in fact this core support several STM32 series, including STM32F0xx.
Currently there is no variant (board) added with the STM32F030K6T6.
You can add your board following this Wiki:
https://github.com/stm32duino/wiki/wiki/Add-a-new-variant-(board)

**Comment by buglyobalazs** [comment]
Hi!

Thanks for your replay. 

I will get one , and will try it. 

Balazs
