### ISSUE TITLE
What is this repo?

### ISSUE THREAD

**Issue by Malmik** [stm32duino/Arduino_Core_STM32#623]
https://github.com/rogerclarkmelbourne/Arduino_STM32 - Is it fork? Is it original repo? Who are those guys?

**Comment by fpistm** [comment]
Hi @Malmik 
This is a repo hosting a core for several STM32 series. This is a different core from @rogerclarkmelbourne which mainly support F1 and F4.
This one is based on STMicroelectronics HAL/LL  and CMSIS as described in the README.md.
@rogerclarkmelbourne allows us to join STM32duino community. It exists several other STM32 cores...

Linked to https://github.com/rogerclarkmelbourne/Arduino_STM32/issues/667

**Comment by Malmik** [comment]
Thanks for explanation!

**Comment by fpistm** [comment]
Welcome.
