### ISSUE TITLE
Encoder Mode on Stm32f103c8

### ISSUE THREAD

**Issue by pasindu-sandima** [stm32duino/Arduino_Core_STM32#628]
Is there feature where I can use the timers in the encoder mode in STM32f103c8. @fpistm 
![Annotation 2019-09-03 163853](https://user-images.githubusercontent.com/37769828/64168781-e9264c80-ce69-11e9-85e0-ab4f5f6397cf.png)
![Annotation 2019-09-03 163756](https://user-images.githubusercontent.com/37769828/64168782-e9bee300-ce69-11e9-8646-1c1d110e15aa.png)

**Comment by fpistm** [comment]
@pasindu-sandima 
There is no dedicated `Arduino` API to use it.
You can use the encoder feature using HAL/LL or direct register access:
https://github.com/stm32duino/Arduino_Core_STM32/blob/e638225486c529bf787735d6a14ddd326156f015/system/Drivers/STM32F1xx_HAL_Driver/Inc/stm32f1xx_hal_tim.h#L1692-L1705

**Comment by ABOSTM** [comment]
Hi @pasindu-sandima,
The HardwareTimer API https://github.com/stm32duino/Arduino_Core_STM32/pull/576
doesn't support encoder mode. But any contribution is welcome.
Nevertheless it is still possible to use STM32Cube API (HAL or LL) to access encoder mode. 
Note: HAL/LL API can be used directly in your arduino sketch.

**Comment by pasindu-sandima** [comment]
@ABOSTM I tried to compile the code generated from CubeMX in arduino. But it did not work.  Is there any specific way that I can use HAL library in arduino sketches??

**Comment by ABOSTM** [comment]
@pasindu-sandima, there is no specific way.
I am not sure to understand what you mean by 'compile the code generated from CubeMX in arduino':
CubeMX doesn't manage specific arduino functions like setup() and loop(), so you need to copy piece of code from CubeMX within setup() or loop() in your arduino sketch.
Also what kind of issue do you have ? compiler error, runtime error ?

**Comment by pasindu-sandima** [comment]
What is the toolchain that has to be used in CubeMX. To be able to use with Arduino core

**Comment by pasindu-sandima** [comment]
I had a compiler error. But now I tried doing direct register editing and now its working. Thanks a lot for your help.
