### ISSUE TITLE
Bootloader

### ISSUE THREAD

**Issue by zpowellman** [stm32duino/Arduino_Core_STM32#630]
Just a question?  Does the Roger Clark Bootloader work with this core?  If not, is there one that does work?
Many Thanks,
Dan Powell

**Comment by fpistm** [comment]
Hi @zpowellman ,
yes it works.
See https://github.com/stm32duino/wiki/wiki/Upload-methods#maple-dfu-bootloader

**Comment by BennehBoy** [comment]
Yes it does, but only with the board variants supported by that bootloader.

**Comment by fpistm** [comment]
is it ok @zpowellman ?

**Comment by zpowellman** [comment]
Thanks for the information guys.  I asked because I tried to burn the bootloader into a blue pill.  It worked fine (Maple Com30) until I uploaded the blink app.  It appears to overwrite the bootloader.  So...It looks like I did something incorrectly.  I'll read the documentation you provided and give it a try again.  I was just making sure I wasn't just spinning my wheels. 
Thanks again
Dan

**Comment by fpistm** [comment]
You have to enable USB in CDC.

**Comment by zpowellman** [comment]
Thanks for the response Fredric.  Not sure what CDC is though.

**Comment by zpowellman** [comment]
Thanks, figured it out
