### ISSUE TITLE
STM32L010rb support

### ISSUE THREAD

**Issue by vasav123** [stm32duino/Arduino_Core_STM32#662]
**Is your feature request/improvement related to a problem? Please describe.**
Can the stm32L010rb be supported as one of the boards?

**Comment by fpistm** [comment]
Hi @vasav123 
in fact this core support several STM32 series, including STM32L0xx.
Currently there is no variant (board) added with the STM32L010RB.
I do not know if you talk about a specific board or having a generic one based on this MCU.

You can add your board following this Wiki:
https://github.com/stm32duino/wiki/wiki/Add-a-new-variant-(board)

Here an example how to add a generic one:
https://github.com/stm32duino/Arduino_Core_STM32/pull/615

**Comment by uzi18** [comment]
like NUCLEO-L010RB ?

**Comment by vasav123** [comment]
@uzi18 Yes, I meant the Nucleo-L010RB board. I also was hoping that a generic STM32L0 could be supported like it is for the F0 series. 
@fpistm thanks for your help, I'll take a look at that and see If I can try to make board myself.

**Comment by fpistm** [comment]
As there is more and more support request for new variant, all are grouped in a single issue to ease tracking: #722.
