### ISSUE TITLE
[USB Composite] Please help bring these functionalities to this core.

### ISSUE THREAD

**Issue by rtek1000** [stm32duino/Arduino_Core_STM32#668]
> Protocols supported
> 
>     standard USB HID, with many built-in profiles, and customizable with more
> 
>     MIDI over USB
> 
>     XBox360 controller (only controller-to-host is currently supported)
> 
>     Mass storage

https://github.com/arpruss/USBComposite_stm32f1

**Comment by rtek1000** [comment]
https://github.com/arpruss/USBComposite_stm32f1/issues/15

**Comment by fpistm** [comment]
Track in #687
