### ISSUE TITLE
How add a variant  from an external project

### ISSUE THREAD

**Issue by fprwi6labs** [stm32duino/Arduino_Core_STM32#67]
Question from [stm32duino](http://stm32duino.com/viewtopic.php?f=48&t=2357):

Roger Clark suggestion:

> Someone on another forum recently told me about being able to add new boards to an existing core, but I have not had time to try it.
I will take a look at your files as if we can separate out the boards into different json files it will simply the number of variants in the core repo
We could also do things like bake json files for the blue pill and black pill etc etc

**Comment by fpistm** [comment]
It has been done by @tomvdb 
https://github.com/tomvdb/edubot_arduino

See board.txt
https://github.com/tomvdb/edubot_arduino/blob/f895c710718ee98e10e3661f46b58e2c058e3a1d/boards.txt#L21

`BennyBot.build.core=STM32:arduino`

**Comment by fpistm** [comment]
@RickKimball 
I found this on your GitHub repositories:
https://github.com/RickKimball/vendor

Can I link to this in the Wiki to answer this issue?
Thanks in advance.

**Comment by RickKimball** [comment]
@fpistm .. sure

Just be warned I haven't tried that github since you added the bluepill as a official board. However, it does give someone hints at some of the things they might need to do.  Just don't expect me to answer questions on why someone's personal board doesn't work. : )

**Comment by fpistm** [comment]
Sure. This is mainly for the hints and examples.

**Comment by fpistm** [comment]
I've added a new Wiki page to answer this issue:
https://github.com/stm32duino/wiki/wiki/Custom-board-based-on-a-core
Thanks @RickKimball
