### ISSUE TITLE
[New Variant] Nucleo L452RE-P Support

### ISSUE THREAD

**Issue by jgromes** [stm32duino/Arduino_Core_STM32#671]
Hi, I'd like to add support for Nucleo L452RE-P. There's already a variant for L452RE, and it looks like code compiled for L452RE does upload to L452RE-P. Since the LED in the Blink example doesn't blink, I guess there's some difference in pin mapping. 

Is it enough to add a few #ifdef statements to the variant files (like with L496ZG and L496ZG-P), and the new variant into boards.txt, or is there something else as well? Thanks!

**Comment by fpistm** [comment]
Hi @jgromes 
looking at your point, I saw some minor issue so I've updated it and add the -P variant.
I've tested Blink, I2C, Serial, SPI and Analog.

**Comment by jgromes** [comment]
Wow, that was fast - I can confirm it's working, will let you know if any issues pop up.

Thanks!

**Comment by fpistm** [comment]
Welcome do not hesitate to open other issue if you meet one.
