### ISSUE TITLE
'HardwareTimer' does not name a type; did you mean 'HardwareSerial'?

### ISSUE THREAD

**Issue by kunalpawar330** [stm32duino/Arduino_Core_STM32#674]
I have installed the stm32duino core on my arduino ide and trying to detect frequency of input signal but I am getting this error. The code is also from examples->stm32duino examples->hardwaretimer->Input capture  

Arduino: 1.8.9 (Windows 10), Board: "Generic STM32F1 series, BluePill F103C8, STM32CubeProgrammer (Serial), Enabled (generic 'Serial'), None, Low/Full Speed, Smallest (-Os default), Newlib Nano (default)"

A subdirectory or file sketch already exists.

InputCapture:15:1: error: 'HardwareTimer' does not name a type; did you mean 'HardwareSerial'?
 HardwareTimer *MyTim;
 ^~~~~~~~~~~~~
 HardwareSerial
InputCapture:17:31: error: variable or field 'InputCapture_IT_callback' declared void
 void InputCapture_IT_callback(HardwareTimer*)
                               ^~~~~~~~~~~~~
InputCapture:17:31: error: 'HardwareTimer' was not declared in this scope
C:\Users\kunal\AppData\Local\Temp\arduino_modified_sketch_515907\InputCapture.ino:17:31: note: suggested alternative: 'HardwareSerial'
 void InputCapture_IT_callback(HardwareTimer*)
                               ^~~~~~~~~~~~~
                               HardwareSerial
InputCapture:17:45: error: expected primary-expression before ')' token
 void InputCapture_IT_callback(HardwareTimer*)
                                             ^
InputCapture:17:31: error: variable or field 'InputCapture_IT_callback' declared void
 void InputCapture_IT_callback(HardwareTimer*)
                               ^~~~~~~~~~~~~
InputCapture:17:31: error: 'HardwareTimer' was not declared in this scope
C:\Users\kunal\AppData\Local\Temp\arduino_modified_sketch_515907\InputCapture.ino:17:31: note: suggested alternative: 'HardwareSerial'
 void InputCapture_IT_callback(HardwareTimer*)
                               ^~~~~~~~~~~~~
                               HardwareSerial
InputCapture:17:45: error: expected primary-expression before ')' token
 void InputCapture_IT_callback(HardwareTimer*)
                                             ^
C:\Users\kunal\AppData\Local\Temp\arduino_modified_sketch_515907\InputCapture.ino: In function 'void setup()':
InputCapture:42:3: error: 'MyTim' was not declared in this scope
   MyTim = new HardwareTimer(Instance);
   ^~~~~
InputCapture:42:15: error: expected type-specifier before 'HardwareTimer'
   MyTim = new HardwareTimer(Instance);
               ^~~~~~~~~~~~~
InputCapture:45:27: error: 'TIMER_INPUT_CAPTURE_RISING' was not declared in this scope
   MyTim->setMode(channel, TIMER_INPUT_CAPTURE_RISING, pin);
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\kunal\AppData\Local\Temp\arduino_modified_sketch_515907\InputCapture.ino:45:27: note: suggested alternative: 'TIM_ICPOLARITY_RISING'
   MyTim->setMode(channel, TIMER_INPUT_CAPTURE_RISING, pin);
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~
                           TIM_ICPOLARITY_RISING
InputCapture:56:35: error: 'InputCapture_IT_callback' was not declared in this scope
   MyTim->attachInterrupt(channel, InputCapture_IT_callback);
                                   ^~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\kunal\AppData\Local\Temp\arduino_modified_sketch_515907\InputCapture.ino:56:35: note: suggested alternative: 'uart_attach_tx_callback'
   MyTim->attachInterrupt(channel, InputCapture_IT_callback);
                                   ^~~~~~~~~~~~~~~~~~~~~~~~
                                   uart_attach_tx_callback
exit status 1
'HardwareTimer' does not name a type; did you mean 'HardwareSerial'?

![Capture](https://user-images.githubusercontent.com/54369570/65816402-abbea000-e218-11e9-800a-4e0ae1c47e77.JPG)

**Comment by fpistm** [comment]
Hi @kunalpawar330 
 You need to install 1.7.0 version of the core.
