### ISSUE TITLE
PWM Build Error on Arduino IDE

### ISSUE THREAD

**Issue by hyuny0505** [stm32duino/Arduino_Core_STM32#679]
Hi!
I'm trying to build my sketch in Arduino IDE, but it can't compile PWM.
![ErrScreen1](https://user-images.githubusercontent.com/22028386/66063197-d9d81300-e57d-11e9-90ed-c3adb9368e9a.png)
It causes an error like the screenshot.
I'm using Arduino IDE 1.8.9 in Windows and Arduino_Core_STM32 1.7.0 and using BluePill F103C8. The upload method is STM32CubeProgrammer (SWD) with ST-LINK v2.
I searched for many examples on the internet. Almost code uses pinMode(xx, PWM); and pwmWrite(); with no error, but it causes error for me.

**Comment by fpistm** [comment]
Hi @hyuny0505 ,
`PWM` is not a valid argument, it is for this core:
https://github.com/rogerclarkmelbourne/Arduino_STM32/

Same for `pwmWrite`.
Those syntaxes do not follow ooficial Arduino API.
Simply use one of the Arduino sketches like the fading.

**Comment by hyuny0505** [comment]
Oh, sorry. Really sorry. Thank you for your help!

**Comment by fpistm** [comment]
No worry 😉

**Comment by deltavra** [comment]
> Hi @hyuny0505 ,
> `PWM` is not a valid argument, it is for this core:
> https://github.com/rogerclarkmelbourne/Arduino_STM32/
> 
> Same for `pwmWrite`.
> Those syntaxes do not follow ooficial Arduino API.
> Simply use one of the Arduino sketches like the fading.

so which argument is valid?

**Comment by fpistm** [comment]
`OUTPUT `even if it is not needed to se pinMode for analogWrite() as it will configure it properly.
