### ISSUE TITLE
SerialUSB  no print-out 

### ISSUE THREAD

**Issue by anatom74** [stm32duino/Arduino_Core_STM32#696]
HW: Nucleo board STM32F4RE411

I wanted to use USB CDC for serial communication and set this accordingly: 
![image](https://user-images.githubusercontent.com/5960221/66705013-1811c700-ed22-11e9-98d6-521d730d96dd.png)

Running the code below I get LED blinking but no print out on com port (COM3)
`void setup() {
  // put your setup code here, to run once:
 SerialUSB.begin();
 pinMode(LED_BUILTIN, OUTPUT);
 delay(2000);
}

void loop() {
  // put your main code here, to run repeatedly:
  SerialUSB.println("TEST");
  delay(400);
  digitalWrite(LED_BUILTIN, !digitalRead(LED_BUILTIN));
}`

The COM port is ST-LINK VCP (COM3):
![image](https://user-images.githubusercontent.com/5960221/66705094-aa19cf80-ed22-11e9-9697-7e964ed53def.png)

Am I using this right?

**Comment by fpistm** [comment]
Hi @anatom74 
This is not the USB CDC. This is an hardware serial connected to stlink. So disable USB cdc then use Serial.

**Comment by anatom74** [comment]
oh, my bad. works now.
Thanks @fpistm.

**Comment by fpistm** [comment]
Welcome
