### ISSUE TITLE
Please update st-link / st-flash tools for compatibility with BluePill

### ISSUE THREAD

**Issue by AndKe** [stm32duino/Arduino_Core_STM32#714]
updating these two tools fixes a lot of problems:  (copying freshly compiled version)

```
andre@loke:~$ cp /usr/local/bin/st-info .arduino15/packages/stm32duino/tools/stm32tools/2019.10.5/linux/stlink/st-info 
andre@loke:~$ cp /usr/local/bin/st-flash .arduino15/packages/stm32duino/tools/stm32tools/2019.10.5/linux/stlink/st-flash
```

before the updated tools, it failed with 
```
2019-01-03T14:08:37 INFO common.c: Starting Flash write for VL/F0/F3/F1_XL core id
2019-01-03T14:08:37 ERROR flash_loader.c: unknown coreid, not sure what flash loader to use, aborting! coreid: 2ba01477, chipid: 410
```

**Comment by fpistm** [comment]
Those tools are no more supported with this core since 1.5.0.

**Comment by AndKe** [comment]
My stm32duino library for Arduiono seems to be version 2019.10.9 , what exactly is not supported since what was 1.5.0 ?

**Comment by fpistm** [comment]
I understood, you use Roger core (https://github.com/rogerclarkmelbourne/Arduino_STM32) packaged here:
http://dan.drown.org/stm32duino/package_STM32duino_index.json
where we find 2019.10.5 version of the stm32tools.

**Comment by AndKe** [comment]
Now I see that this is not the project I used.
I understand that this project does more or less the same job, most likely better, as it seems to me STM32duino is no longer developed?

Should I uninstall/remove the stm32duino boards, before removing it, and replacing with this project ?
Please advise.
Thank you.

**Comment by fpistm** [comment]
You could have both installed.
Each core is different. This one support all series and is more Arduino compatible.
