### ISSUE TITLE
Extend I2C buffer

### ISSUE THREAD

**Issue by Pararera** [stm32duino/Arduino_Core_STM32#725]
Add ability to change `BUFFER_LENGHT`(I2C buffer size) from main file.

**Comment by fpistm** [comment]
In this core the I2C `BUFFER_LENGTH` is the min size.
It is allocated dynamically in order to be able to growrh if needed until 256.

**Comment by fpistm** [comment]
Hi  @Pararera 
any feedback on this?

**Comment by fpistm** [comment]
No feedback considered as answered

**Comment by Pararera** [comment]
I forgot for this, sorry.
Thanks, I didn't know that!
