### ISSUE TITLE
PA12 pin not toggling on stm32f103c series

### ISSUE THREAD

**Issue by Broman3100** [stm32duino/Arduino_Core_STM32#732]
The digitalWrite(PA12, LOW/0) function for PA12 pin doesn't work on generic stm32f103 board, (f103c8), I know it's not just my board problem since I used keil and it worked just fine so I figured the problem is in stmduino.

**Comment by fpistm** [comment]
Hi @Broman3100 
Could you be more precise.
Which core version you used?
Build option set in the Arduino menu, ...
All relevant information to help

**Comment by Broman3100** [comment]
I used arduino 1.8.9( windows store 1.8.21.0), I'm confident I used newest version of stm32duino and build options are following:
![image](https://user-images.githubusercontent.com/44446127/67570417-6079ad80-f742-11e9-91f9-6b96a2fbc168.png)

**Comment by fpistm** [comment]
Ok that's what I think.
Same issue than here: #729
You do not use this core. You use this one:
https://github.com/rogerclarkmelbourne/Arduino_STM32

**Comment by Broman3100** [comment]
I guess you were right, I apologize for the inconvenience and thank you for taking your time to help me.

**Comment by fpistm** [comment]
Welcome
