### ISSUE TITLE
is -fno-threadsafe-statics supported ?

### ISSUE THREAD

**Issue by AndKe** [stm32duino/Arduino_Core_STM32#733]
I had other STM32Duino programs that consumed lots of flash. Mostly due to byte-padding for 32bit.
used -fno-threadsafe-statics successfully.
Adding that flag to build-opt.h does not affect the size.
Why ?

**Comment by fpistm** [comment]
https://github.com/stm32duino/Arduino_Core_STM32/blob/9ddecc3f9c723ef71d2c2b983984113cfc2cfbcd/platform.txt#L37

**Comment by AndKe** [comment]
Thank you.

**Comment by fpistm** [comment]
Welcome
