### ISSUE TITLE
F412RE: Issues with TIM6_DAC_IRQn in timer.h

### ISSUE THREAD

**Issue by InternetAthiest** [stm32duino/Arduino_Core_STM32#739]
Created a custom variant of a F412RET6 and kept getting compiler errors. Apperently timer.h assumes that all but L1 and F1 series has a DAC (see row 61-69 in timer.h) which is not correct. Maybe add a check for those certain models or maybe check if HAL_DAC_MODULE_ENABLED is defined?

**Comment by fpistm** [comment]
Hi @InternetAthiest 
Could you share your variant, please?
HAL_DAC_MODULE_ENABLED is not the right thing to check. You can have DAC and module disabled.

**Comment by fpistm** [comment]
@InternetAthiest 
Could you test #740 
Thanks in advance

**Comment by InternetAthiest** [comment]
Works wonders now!
Thanks!

**Comment by fpistm** [comment]
welcome
