### ISSUE TITLE
OpenAMP list.h name collision with freertos list.h

### ISSUE THREAD

**Issue by adammunich** [stm32duino/Arduino_Core_STM32#760]
When compiling with stm32freertos, list.h in OpenAMP's name over-rides list.h with freertos and compilation fails. Renaming OpenAMP's list.h solves this issue.

**Comment by fpistm** [comment]
Hi @adammunich 
Thanks for reporting this.
Currenlty, I guess I will remove OpenAMP from include list in the platform.txt as it is not used.
/CC @kbumsik

**Comment by fpistm** [comment]
@adammunich 
How you met the issue?
I have no issue. I thought OpenAmp include path was in the platform.txt but this is not.

**Comment by adammunich** [comment]
Some platforms and makefiles I have seen include Arduino_Core_STM32/system/Middlewares/ST recursively, which causes the issue.

**Comment by kbumsik** [comment]
@fpistm Please reconsider deleting. The virtual serial using OpenAMP is completed and it's code cleaning phase. I'm going to make a PR right after #717 is merged.

@adammunich Could I ask what platforms are? I'm personally interested in projects using stm32freertos.
> Arduino_Core_STM32/system/Middlewares/ recursively

This sounds like their responsibility to update the project build though.

**Comment by fpistm** [comment]
> This sounds like their responsibility to update the project build configurations though.

I agree with @kbumsik.
I see no issue with `list.h` as OpenAmp requires to include it thanks: `#include <metal/list.h>`
