### ISSUE TITLE
STM32L031K6 UART pins

### ISSUE THREAD

**Issue by crameur** [stm32duino/Arduino_Core_STM32#761]
Hello,

I have encountered an issue while trying to have make an UART connection between 2 L031K6.
If I do it using arduino boards, it works fine, but when I switch to the STM32 (under stm32duino) and after having changed the pins, I can't have them echo each other.
```
/* 
  WORKS WITH 2 UNOS

 */
#include <SoftwareSerial.h>

#define RX PB5
#define TX PB4

SoftwareSerial mySerial(RX, TX); // RX, TX

//HardwareSerial mySerial(PA3,PA1);

void setup()
{
  // Open serial communications and wait for port to open:
  Serial.begin(115200);
  while (!Serial) {
    ; // wait for serial port to connect. Needed for Native USB only
  }


  Serial.println("Goodnight moon!");

  // set the data rate for the SoftwareSerial port
  mySerial.begin(38400);
  mySerial.println("Hello, world?");
}

void loop() // run over and over
{
  if (mySerial.available())
    Serial.write(mySerial.read());
  if (Serial.available())
    mySerial.write(Serial.read());
}
```

Is there something wrong with my code ? Am I not choosing the correct pins ? Should I use HardwareSerial instead ?

**Comment by fpistm** [comment]
Hi @crameur  
How do you wired the 2 boards?

**Comment by crameur** [comment]
Same GND, RX of the 1st one to the TX of the second one and conversely

**Comment by fpistm** [comment]
You use the 1.7.0 core version ?

**Comment by crameur** [comment]
@fpistm Yes, STM32 Cores version 1.7.0

**Comment by fpistm** [comment]
I think this could be related to interrupt prio. 
Anyway, the best way should be to use an hardware serial. SoftwareSerial was mainly designed for mcu with one hardware serial and we add it mainly for libraries compatibility.
Like STM32 has more U(S)ART this shoukd superseded this.

**Comment by crameur** [comment]
Yeah that's why I tried to implement it using an hardware serial but it seems as if there is only one UART on these stm.. And the Serial for the Arduino monitor is already using it ?
Am I mistaking, which pins should I use then ?

**Comment by fpistm** [comment]
I will check when got some time. Keep in touch

**Comment by fpistm** [comment]
Hi  @crameur 
Unfortunately, this is not possible to use the SoftwareSerial with the STM32L031K6. 
It spends all its time in the Timer IRQ handler, it is not enough fast for that use case.
About using an hardware Serial. This is not possible on this Nucleo as there is only 2 UART's available:
 * `USART2` used for default Serial
 * `LPUART1` but the pins are not accessible and reserved for SWD stuff. That's why it is commented in the `PeripheralPins.c`.

**Comment by fpistm** [comment]
I close it as there is nothing to do.
