### ISSUE TITLE
[MAX3421E] USB HOST SHIELD: Please help bring these features to this core.

### ISSUE THREAD

**Issue by rtek1000** [stm32duino/Arduino_Core_STM32#768]
> UHS30: USB Host Library version 3.0
>
> Current working USB interface drivers
>     -- HID RAW
>     -- MIDI
>     -- Hub
>     -- Mass storage
>     -- CDC-ACM serial
>     -- XR21B1411 serial
>     -- PROLIFIC serial
>     -- FTDI serial

I would like to suggest that this library for USB Host Shield with MAX3421E be ported to this STM32 core. In arduino mega2560 worked fine. The UHS30 library already has support for some ARM models, maybe it is not so difficult to port and may also be of interest as a base of understanding for STM32's internal USB hardware.

I have tried to port, but still do not fully understand the operation of STM32 interrupt vectors: https://github.com/felis/UHS30/issues/57

This library is version 3.0 and it was possible to recognize the mouse and keyboard at the same time, using a mini keyboard similar to the link below. (Library version 2.0 did not work correctly with this keyboard)

Ref.:
https://github.com/felis/USB_Host_Shield_2.0/issues/499

Original code:
https://github.com/felis/UHS30/tree/master/libraries/UHS_host/UHS_HID/examples/USB_HOST_SHIELD/UHS_HID_RAW

![Mini Keyboard](https://user-images.githubusercontent.com/8660811/68538489-e8230700-0353-11ea-9c7f-0aebb6e21023.jpg)

**Comment by fpistm** [comment]
Hi @rtek1000 
I add this to the USB request list.
If anyone wants to contribute.
Just a quick note from the README:
```
Pre-release of USB Host Library version 3.0. No technical support offered at this time.

This set of libraries is EXTREMELY ALPHA!
```
