### ISSUE TITLE
missing core_cm3.h ?

### ISSUE THREAD

**Issue by JBerg60** [stm32duino/Arduino_Core_STM32#777]
This one is keeping me busy for quit some time now ..
In clock.h stm32_def.h is included.

In stm32.h the USE_HAL_DRIVER is defined, and a board is selected over a define.

I selected the STM32F1xx, so the stm32f1xx.h is included.

The only stm32f1xx.h file is in /system/Drivers/CMSIS/Device/ST/STM32F1xx/Include

I have another define STM32F103xB this selects the stm32f103xb.h file.

In this file, on line 132 is #include "core_cm3.h".

This file is not present in the repo.

When I generate a project over CubeMX, there is a folder Drivers/CMSIS/Include and there is also the core_cm3.h

What am I missing?

**Comment by JBerg60** [comment]
@fpistm Answered?

**Comment by fpistm** [comment]
Yes but it seems it was not properly submitted.
The file is not in this repo. It is part of the cmsis package installed when you use the boards manager.

**Comment by JBerg60** [comment]
Thanks.

Found it .. in my case it is version 5.5.1 ..
