### ISSUE TITLE
enable HAL RTC and CRC in variants/FEATHER_F405/variant.h

### ISSUE THREAD

**Issue by manitou48** [stm32duino/Arduino_Core_STM32#781]
add **#define HAL_RNG_MODULE_ENABLED** and **#define HAL_CRC_MODULE_ENABLED** to 
 variants/FEATHER_F405/variant.h

enable HAL-based sketches for RNG and CRC on  STM32F405

**Comment by fpistm** [comment]
Hi @manitou48 
For the most user this will not be used.
You can define it easily by adding an `hal_conf_extra.h` along your sketch.
See [HAL-configuration](https://github.com/stm32duino/wiki/wiki/HAL-configuration#core-version--150-1)
