### ISSUE TITLE
`HardwareTimer` PWM resolution stuck at 12-bit?

### ISSUE THREAD

**Issue by jeffstaley** [stm32duino/Arduino_Core_STM32#790]
If I run a one-line Arduino program on a STM32F7 of 

```
analogWrite(FAN1_PIN, 255)
```

I get a PWM signal with a very low duty cycle instead of the expect 100%. 

Digging into the code I see `pwm_start()` setting up a HardwareTimer with a __hard coded__ 12-bit resoultion:

```
  HT->setCaptureCompare(channel, value, RESOLUTION_12B_COMPARE_FORMAT);

```

**Comment by fpistm** [comment]
FAN1_PIN is equal to?

**Comment by jeffstaley** [comment]
Any of the PinMap_PWM pins.  But in this case 30.

**Comment by fpistm** [comment]
The default PWM resolution is 12 bits. 
So you should do:
`analogWrite(FAN1_PIN, 1023);`
To get a 100% duty cycle

**Comment by jeffstaley** [comment]
But if

```
#define PWM_RESOLUTION              12
```

is redefined in variant.h to


```
#define PWM_RESOLUTION              8
```

`analogWrite()` is still in 12-bit mode.

**Comment by fpistm** [comment]
The 8 bits value is converted to 12 bits thanks the map function.
Which board you used?

**Comment by jeffstaley** [comment]
I'm not seeing that.  If `PWM_RESOLUTION` is set to 8 the map function does nothing (since we're in 8-bit mode).  But the HWTimer is still _hard coded_ to 12-bit mode.

It appears that the map function is used when you dynamically change the resoultion via `analogWriteResolution()`

Board is `RemRam v1`

**Comment by fpistm** [comment]
@jeffstaley 
You're right there is an issue.
There is a misalignment when the `PWM_RESOLUTION` is redefined.
This was introduced when HardwareTimer was released. We will fix this.
As a workaround simply comment the `PWM_RESOLUTION` in the variant.h.

**Comment by jeffstaley** [comment]
Commenting out `PWM_RESOLUTION` in variant.h doesn't work for me since all the code I'm using (Marlin) assumes 8-bit resolution.  Presumably I could do that and then dynamically change the resolution to 8-bit with `analogWriteResolution()` but I haven't tested that.  Instead I pass in `RESOLUTION_8B_COMPARE_FORMAT` to the HardwareTimer module when compiled in 8-bit PWM mode.  That my not be a general enough solution for you if accept additional resolutions.

**Comment by fpistm** [comment]
By default `analogWriteResolution()` is 8 bits. So the range you can used is 0-255. At a lower layer it is converted as 12 bits value to match Timer config at 12 bits. So you should have the proper duty cycle if you comment the `PWM_RESOLUTION` in `variant.h`.

**Comment by jeffstaley** [comment]
OK I see that now and that should be cleaner.  I'll give that a try. Thanks.
