### ISSUE TITLE
spi_com isn't in the PIO include path anymore

### ISSUE THREAD

**Issue by LinoBarreca** [stm32duino/Arduino_Core_STM32#801]
**Describe the bug**
Commit fe3fca1e breaks code.

**To Reproduce**
Yesterday's code [here](https://github.com/LinoBarreca/Marlin/pull/7) was buildable with PlatformIO+VSCode.
After pulling this morning it isn't anymore because he doesn't find spi_com.h in the default include paths.

**Expected behavior**
If a file was reachable through #include <> it should remain reachable.

**Screenshots**
![image](https://user-images.githubusercontent.com/897723/69800440-8ed12980-11d5-11ea-99f5-30dcd47c8793.png)

![image](https://user-images.githubusercontent.com/897723/69801152-eb811400-11d6-11ea-8732-dfd7b5ff7e8e.png)

**Comment by fpistm** [comment]
Hi @LinoBarreca 
unfortunately, it is fine for Arduino IDE.
I do not know how PIO handle include of library but I could not help on this subject.
Maybe you can try to replace in your code:
`#include <spi_com.h>`
by 
`#include <utility/spi_com.h>`
