### ISSUE TITLE
stm32f103xx jump to User Application

### ISSUE THREAD

**Issue by gsaikiran29** [stm32duino/Arduino_Core_STM32#802]
Hello,
First of all this is not an Issue,
I want develop In application programming in stm32f103xx board.
I am using stm32f103xx development board, Arduino IDE, rogerclark's Arduino_STM32 library.

I want to take user application code from SD/SPI flash and upload into controller new flash location and jump to that new user application and perform as per that.
I know that usart bootloader already developed, but by using SD/SPI flash I want develop.

I tried somehow by using Arduino_STM32 internal libraries 
#include <SPI.h>
#include <SD.h>
#include <EEPROM.h>
#include <stdint.h>
#include "libmaple/scb.h"
#include "usb_lib.h"
 i have developed one code that code performed as that took code from SD card and stored into controller's new address 0x8010000 successfully. but its not jumping into new application address.
this piece of code i used to jump from main app to user app.

`typedef void (*funcPtr)(void);
  u32 jumpAddr = *(vu32 *)(usrAddr + 0x04); /* reset ptr in vector table */

  funcPtr usrMain = (funcPtr) jumpAddr;

  SET_REG(SCB_VTOR, (vu32) (usrAddr));

  asm volatile("msr msp, %0"::"g"(*(volatile u32 *)usrAddr));

  usrMain();        `

And before generating the .bin file of my application i have changed vector starting address in library files and linker files too.

can any one give some suggestions where I am doing wrong.

**Comment by fpistm** [comment]
Hi @gsaikiran29 
I saw you issue on Roger's Core.
I will not be able to help you as this is not linked to this core (Arduino_Core_STM32) and that I could not debug all end user code.
Sorry.
