### ISSUE TITLE
Blue Pill Stm32f103 USB CDC Serial Not Recognized

### ISSUE THREAD

**Issue by exothink** [stm32duino/Arduino_Core_STM32#809]
I have several blue pill boards.  Six appear to be Stm chips the other five are CKS knockoffs based on internal IDs.  External markings don't match up with internal IDs.  Two of them out of the bunch are recognized by Win10 as com devices the others show as unrecognized devices.  USB data+ pullups at 10k or 1.5k have no effect.

This is an FYI for those having issues getting 'SerialUSB' to work on Blue Pills.

**Comment by fpistm** [comment]
Hi @exothink 
thanks for sharing, this should be better to have this in the wiki.
You can add a not in the FAQ:
https://github.com/stm32duino/wiki/wiki/FAQ
