### ISSUE TITLE
[New Variant] Open107V from Waveshare

### ISSUE THREAD

**Issue by Oh-Doo-Yong** [stm32duino/Arduino_Core_STM32#815]
hello.
I like arduino_core_stm32. 
Can you support stm32f107vct ?

I try new new variant... but difficult...
-------------------------------------------------------------------------------------------------
1. Name : STM32F107VCT
2. LINK : 
https://www.waveshare.com/open107v-standard.htm
3. Documentations
https://www.waveshare.com/wiki/Open107V
4. Schematics : 
https://www.waveshare.com/w/upload/4/40/Open107V-Schematic.pdf
5. Where this hardware can be purchased :
https://www.amazon.com/Waveshare-Development-STM32F107VCT6-STM32F107-Cortex-M3/dp/B00KM6W6JK/ref=sr_1_1?keywords=stm32f107&qid=1575415768&sr=8-1
------------------------------------------------------------------------------------------------------
Thank you.

**Board description (please complete the following information):**
 - Name: [e.g. DISCOVERY F769NI]
 - Link to all relevant information:
   * Documentations
   * Schematics
   * Where this hardware can be purchased
  * ...

**Note that user can add a STM32 based board following this [wiki](https://github.com/stm32duino/wiki/wiki/Add-a-new-variant-(board))**

Any contribution is welcome, so do not hesitate to submit a PR.

**Comment by fpistm** [comment]
Hi @Oh-Doo-Yong 
I've added it to #722 [New Variant] request list
