### ISSUE TITLE
Counting pulses

### ISSUE THREAD

**Issue by mrguen** [stm32duino/Arduino_Core_STM32#816]
To complement https://github.com/stm32duino/Arduino_Core_STM32/issues/763 

Would it be possible to implement these 

* clocking of timers from an external source i.e. positioning the timer register SMCR with the ECE bit set

* timers master / slave modes that also allows gating i.e. positioning the timer register SMCR with TIMER_SMCR_SMS_GATED | TIMER_SMCR_TS_ITR0 (old Roger's defines)

* including prescaling of the external signal (so it could input signal up to around 200 MHz)

* will also need to set the gating timer's registers  CR2 with MMS_ENABLE and  possibly SMCR with SMCR_MSM

* Or all together implementing a mode for setting a timer as clocked by external source, with prescaler, and gated by another timer.

**Comment by ABOSTM** [comment]
Hi @mrguen,
Humm, this HardwareTimer library aims to provide simple access to basic features of Timer. Thus benefits from hardware capabilities despite very simple API. 
Clearly the features you requested are far from this objective, and are for advanced users.
There is already STM32 HAL/LL drivers that give you access to all hardware capabilities and we cannot afford to develop a new arduino library just to do the same thing.
No need to reinvent the wheel, just use HAL/LL . Those API could be called directly from your arduino sketch.
