### ISSUE TITLE
[Nucleo-G431KB] Upload fails with "NODE G431KB not found"

### ISSUE THREAD

**Issue by niels4911** [stm32duino/Arduino_Core_STM32#820]
It looks like the Upload fails because my board shows up as E\:NOD_G431KB in the file manager. 

When I rename the mass storage to NODE_G431KB it works - but I have to rename the E: drive every time I what to upload a new version.

**Comment by fpistm** [comment]
Hi @niels4911 
Could you try to update the STLink firmware thanks STM32CubeProgrammer.

**Comment by fpistm** [comment]
I've made a test with a newer board and reproduce.
It seems the most recent STLink firmware decide to change the name....
With V3J2M1: _"NODE_G431KB"_
wtih newer: _"NOD_G431KB"_

I will do an update to the boards.txt:
https://github.com/stm32duino/Arduino_Core_STM32/blob/ad09a48db2d4c6a05491f9be91ef095580fca5f6/boards.txt#L286


```patch
- Nucleo_64.menu.pnum.NUCLEO_G431RB.node=NODE_G431RB
+ Nucleo_64.menu.pnum.NUCLEO_G431RB.node="NODE_G431RB,NOD_G431RB"
```

**Comment by Nivek92** [comment]
I receive a similar issue (NOD_C031C6 not found.) when trying to use it with an Nucleo-64 STM32F302R8

**Comment by fpistm** [comment]
> I receive a similar issue (NOD_C031C6 not found.) when trying to use it with an Nucleo-64 STM32F302R8

Not the same, seems you didn't select the correct board, the C031 is the first one of the list....
