### ISSUE TITLE
warning: ISO C++1z does not allow 'register' storage class specifier [-Wregister]

### ISSUE THREAD

**Issue by adammunich** [stm32duino/Arduino_Core_STM32#830]
Looks like the register storage class specifier is officially dropped from C++. Compiling gives lots of:

warning: ISO C++1z does not allow 'register' storage class specifier [-Wregister]

But, it doesn't seem to break anything. Maybe we should remove the register designators from the codebase? Many are in the HAL unfortunately.

**Comment by fpistm** [comment]
Hi @adammunich 

> Many are in the HAL unfortunately.

Right, the core uses the HAL without modify them. Hope this will be fixed in further release.
This is something you can raise on the STM32 Cube Fw repo:
https://github.com/stmicroelectronics
