### ISSUE TITLE
hid code 43 on high speed

### ISSUE THREAD

**Issue by uuuvn** [stm32duino/Arduino_Core_STM32#845]
board: black stm32f407vet6
I use last version

**Comment by fpistm** [comment]
Hi @uuuvn 
Could you be more precise?
The USB connector of the Black F407 is connected to the FS pins so you could not use HS in this case.

**Comment by uuuvn** [comment]
@fpistm Same thing in "Hight speed in full speed mode"

**Comment by uuuvn** [comment]
But it works in STM32CubeIDE

**Comment by fpistm** [comment]
This is normal. You have to select Full speed.

**Comment by fpistm** [comment]
Hi @uuuvn 
I've tested and HID works fine on the Blacj F407VE while you configure properly  the USB in "Low/Full Speed".
As I said the USB on the Black F407 use the USB OTG FS and not the HS.
