### ISSUE TITLE
DISCO_F100RB board using HSI should use HSE

### ISSUE THREAD

**Issue by RickKimball** [stm32duino/Arduino_Core_STM32#85]
The STM32VL Discovery board has an external 8MHz xtal.  In spite of that, the SystemClock_Config() configures itself for the HSI which leads to a less accurate SYSCLK.  Please consider using the HSE with this board.

**Comment by fpistm** [comment]
@RickKimball could you submit a PR with a config using HSE ? As I do not have this one, I could not test. :'(
