### ISSUE TITLE
Release 1.8.0 produces a lot of errors on linking stage with VisualMicro

### ISSUE THREAD

**Issue by Kabron287** [stm32duino/Arduino_Core_STM32#854]
VisualMicro for Visual Studio 1911.23.2. Visual Studio 2017
Nucleo 64 F411RE. Blink exampe.
Upload set to STM32CubeProgrammer(SWD)
ST-Link V3 mini.

Since I had to return to Release 1.7.0(which works fine) I could not offer error messages. To reinstall release take a huge time.
Everybody can reproduce the issue just compiling Blink example.

**Comment by fpistm** [comment]
Hi @Kabron287 
I guess you made your custom configuration to use visual micro. The 1.8.0 sources organisation have changed and  whole-archive  option has been removed 
We do not support other IDE, only Arduino. 
You can post a message in the IDE section of the forum.
https://www.stm32duino.com/viewforum.php?f=18
