### ISSUE TITLE
STM32G031K8T6

### ISSUE THREAD

**Issue by spa-sam** [stm32duino/Arduino_Core_STM32#855]
Atmel has the most popular atmega328p microcontroller. In my opinion, the STM32G031K8T6 is the best alternative.
Is it possible to add this chip and is there any reason for this in view of memory?

**Comment by fpistm** [comment]
Hi @spa-sam 
The G0 serie is already supported in this core.
I guess you want he board variant for https://www.st.com/content/st_com/en/products/evaluation-tools/product-evaluation-tools/mcu-mpu-eval-tools/stm32-mcu-mpu-eval-tools/stm32-nucleo-boards/nucleo-g031k8.html

It can be added following this wiki:
https://github.com/stm32duino/wiki/wiki/Add-a-new-variant-(board)

I've added your request to this issue: #722
