### ISSUE TITLE
STM32G031 Support?

### ISSUE THREAD

**Issue by gilgm12** [stm32duino/Arduino_Core_STM32#857]
Is the STM32G031 line of MCUs supported?  Easy enough to add?

Datasheet is here:
https://www.st.com/resource/en/datasheet/stm32g031j6.pdf

I know the STM32G071RB is supported - perhaps I can modify that definition?

**Comment by fpistm** [comment]
All STM32 series and MCU lines are supported. It only requires to add a variant. 
It was already requested in #855 and added to the #722 variants list.

**Comment by gilgm12** [comment]
Excellent, thank you. :)

**Comment by fpistm** [comment]
> Excellent, thank you. :)

Welcome.
This list is all the specific requirements by the community and anyone could help to do the variant following the Wiki.
