### ISSUE TITLE
analogRead() - adc_read_value() unimplemented?

### ISSUE THREAD

**Issue by ag88** [stm32duino/Arduino_Core_STM32#860]
**Describe the bug**
ADC didn't seem to work. During a code examination analogRead()
i drilled into the codes and found a call to adc_read_value()
https://github.com/stm32duino/Arduino_Core_STM32/blob/master/cores/arduino/wiring_analog.c#L164
However, a search for adc_read_value() didn't seem to turn up an entry for the function.

**To Reproduce**
Complete source code which can be used to reproduce the issue. Please try to be as generic as possible (no extra code, extra hardware,...)

https://github.com/stm32duino/Arduino_Core_STM32/blob/master/cores/arduino/wiring_analog.c#L164
However, a search for adc_read_value() didn't seem to turn up an entry for the function.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux
 - Arduino IDE version: VSCode, IDE 1.8.9
 - STM32 core version: 1.8.0
 - Tools menu settings if not the default: USBSerial
 - Upload method: dfu

**Board (please complete the following information):**
 - Name: Blackpill F401

**Additional context**

**Comment by fpistm** [comment]
@ag88 
it is here and well implemented: https://github.com/stm32duino/Arduino_Core_STM32/blob/ea8664573c69acf7673103b6ef198ef4b22d00b9/libraries/SrcWrapper/src/stm32/analog.cpp#L764

Don't know why VSCode do not find it but it works, probably the intellisense which is not properly configured.

**Comment by ag88** [comment]
thanks !
