### ISSUE TITLE
Print::printf on SerialUSB

### ISSUE THREAD

**Issue by Tretgo** [stm32duino/Arduino_Core_STM32#862]
Preconditions:
OS: Win10
Arduino 1.8.10
STM32 1.8.0
BluePill F103
HID Bootloader
USB CDC Serial

USB Serial output is not working when setting
HAL_UART_MODULE_ONLY
HAL_UART_MODULE_ENABLED
in build_opt.h

Target: LIN Serial implementeation on UART1 and USB Serial for debugging

Root cause:
https://github.com/stm32duino/Arduino_Core_STM32/blob/ea8664573c69acf7673103b6ef198ef4b22d00b9/cores/arduino/Print.cpp#L199-L220

Function write in Print.cpp gets disabled when setting UART into HAL mode.
But only uart_debug should be disabled. 

Working bugfix:

```C
extern "C"
{
  __attribute__((weak)) int _write(int file, char *ptr, int len)
  {
#if defined(HAL_UART_MODULE_ENABLED) && !defined(HAL_UART_MODULE_ONLY)
    switch (file)
    {
    case STDOUT_FILENO:
    case STDERR_FILENO:
      uart_debug_write((uint8_t *)ptr, (uint32_t)len);
      break;
    case STDIN_FILENO:
      break;
    default:
      ((class Print *)file)->write((uint8_t *)ptr, len);
      break;
    }
#else
    if (file != STDERR_FILENO)
      ((class Print *)file)->write((uint8_t *)ptr, len);
#endif
    return len;
  }
}
```

**Comment by fpistm** [comment]
Hi @Tretgo 
I guess this is when you use `printf()` with SerialUSB ?

**Comment by Tretgo** [comment]
Hi,
just checked.
`println()` works, but `printf()` does not.
