### ISSUE TITLE
Error in Uploading STM32F401RE

### ISSUE THREAD

**Issue by Vicky-S** [stm32duino/Arduino_Core_STM32#865]
**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Arduino IDE version: [e.g. 1.8.8]
 - STM32 core version: [e.g. 1.8.0]

**Board (please complete the following information):**
 Name: Nucleo 401RE

I updated my STM32 official core today and after this i am getting the following error if I try to upload the code in Arduino. Please check below for the error shown in arduino IDE.

Insufficient disk space on current disk.
Insert another disk and type <Return> to continue... An error occurred while uploading the sketch

**Comment by fpistm** [comment]
Seems strange.
Did you try to update the STLink Firmware?

I guess this is with MassStorage ?
Which sketch you use ?

**Comment by Vicky-S** [comment]
I can create HEX file and upload it via STLINK UTILITY. But I can't directly program in arduino.

Even blink example giving the same error while uploading.

**Comment by fpistm** [comment]
When I've got this error it was due to an issue with STLink Firmware. So please try to update it.

**Comment by Vicky-S** [comment]
Ok...

**Comment by fpistm** [comment]
If this not solved your issue share all option you used, the STLink Fw version and all relevant information.
Anyway as the Hex file works when flashed with STLink utility means the FW is well formed and rely on massStorage copy. And MassStorage copy is managed by STLink FW.

**Comment by fpistm** [comment]
Hi @Vicky-S 
I've made some tests (Linux/Windows, MassStorage, STlink SWD)  on my Nucleo F401 and I have no issue.

**Comment by Vicky-S** [comment]
I removed and Reinstalled the STM32 core in Arduino Boards manager. Problem is solved.
