### ISSUE TITLE
I2S Interface? HAL?

### ISSUE THREAD

**Issue by Bambofy** [stm32duino/Arduino_Core_STM32#871]
Hi, is there a way to use the I2S library with STM32Duino?

Thank, Richard

**Comment by fpistm** [comment]
Hi @Bambofy 
currently there is no "Arduino" library for I2S.
You can use HAL or LL at sketch level by enabling the `HAL_I2S_MODULE_ENABLED`.

See https://github.com/stm32duino/wiki/wiki/HAL-configuration

**Comment by Bambofy** [comment]
If i #define HAL_I2S_MODULE_ENABLED in stm32l4xx_hal_conf_default.h would that do anything? i cannot see any ifdefs that include specific header files?

**Comment by fpistm** [comment]
Use the hal_conf.h to define it at sketch  level. Then you will have access to all HAL I2S API.

**Comment by fpistm** [comment]
@Bambofy 
For this kind of question, please use the stm32duino.com forum.

**Comment by Bambofy** [comment]
Hi, I have been looking through the stm32l4 drivers and i can't find the i2s driver? It is included in other versions but not this one?

**Comment by fpistm** [comment]
Simply because there is no I2S on L4...
https://www.st.com/en/microcontrollers-microprocessors/stm32l4-series.html

**Comment by fpistm** [comment]
@Bambofy 
when I replied I did not see you talk about L4.
FYI, all HAL/LL are provided so if you do not find a HAL module this simply means the feature is not available for this serie.
I close this one as I consider it as answered.
