### ISSUE TITLE
[New Variant]Pyboard

### ISSUE THREAD

**Issue by nopnop2002** [stm32duino/Arduino_Core_STM32#906]
**Board description:**
 - Name: [Pyboard]
 - Link to all relevant information:
https://www.elektor.com/micropython-pyboard-v1-1
https://www.alibaba.com/product-detail/STM32-STM32F405RGT6-Core-Board-For-MicroPython_60652366847.html

**Comment by fpistm** [comment]
Hi @nopnop2002 

I've added your request to the request list: #722
