### ISSUE TITLE
Unable to change GPIO state after call to analogRead

### ISSUE THREAD

**Issue by jgromes** [stm32duino/Arduino_Core_STM32#911]
**Describe the bug**
Hi, I ran into the following issue: after calling analogRead on pin PA12, I'm no longer able to change the state of pin PC3. In the below sketch, PC3 should toggle, however, after analogRead on PA12, there is no output on PC3 (checked with scope).

It seems to be specific to those two pins, when trying a few different combinations, it works fine - possibly a pin mapping issue?

**To Reproduce**
```c++
#define OUT      PC3
#define IN       PA12 

void setup() {
  pinMode(OUT, OUTPUT);
  digitalWrite(OUT, LOW);
  
  pinMode(IN, INPUT);
  // remove analogRead to make it work again
  analogRead(IN);
}

void loop() {
  digitalWrite(OUT, LOW);
  delayMicroseconds(5);
  digitalWrite(OUT, HIGH);
  delayMicroseconds(5);
}
```

**Expected behavior**
PC3 pin should be able to change state regardless of analog reading on pin PA12.

**Workaround**
When PA12 is set to output after analogRead, PC3 toggles correctly again.

**Desktop**
 - OS: Windows 7 64bit
 - Arduino IDE version: 1.8.10
 - STM32 core version: head commit
 - Upload method: Mass Storage

**Board**
 - Name: Nucleo L452RE-P

**Comment by ABOSTM** [comment]
Hi @jgromes,
There are several mistakes in your sketch:
* `pinMode(IN, INPUT);`
This line is useless: the `analogRead(IN) `will do the configuration.
Also `INPUT `should have been replaced by `INPUT_ANALOG`.
Whatever this is no the cause of your issue.
* The main issue is that PA12 is not an analog pin, it doesn't support ADC.
You should use either use Ax define (A0, ...) or Pxy but only the one that support ADC.
In your case, PA12 is interpreted as analog and corresponds to A2 (= PC3). This is the reason why `digitalWrite(OUT,...)` is no more working.
