### ISSUE TITLE
SoftwareSerial hardware timer interrupt  not being called?

### ISSUE THREAD

**Issue by lab-mathias-claussen** [stm32duino/Arduino_Core_STM32#919]
STM32F072C8T6 / Elektor LoRa Node 

Seems like #879 the interrupt for the hardware timer is not getting called. We can see that the IO Pins get configured ( PA2 and PA3 ) in this case. 

To Reproduce:

Fit a STM32F072C8T6 on a bluepill and put the following code using version 1.8 of the core on the board:

> /* Includes */
> #include <hal/hal.h>
> #include <SPI.h>
> #include <Wire.h>
> 
> #include <SoftwareSerial.h>
> #include <EEPROM.h>
> 
> SoftwareSerial SerialX(PA3, PA2); //RX, TX
> /**************************************************************************************************
>  *    Function      : print_array
>  *    Description   : will print an array of data as hex
>  *    Input         : uint8_t * data , uint32_t len 
>  *    Output        : none
>  *    Remarks       : none
>  **************************************************************************************************/
> void print_array(uint8_t * data , uint32_t len ){
> 
>   for(uint32_t i=0;i<len;i++){
>            Serial.print("0x");
>            Serial.print(*data++);
>            Serial.print(" ");
>   }
>   Serial.println("");
> } 
> 
> 
> void setup() {
>   Serial.begin(115200);
>   SerialX.begin(9600);
>   Serial.println("Boot");
>    
> }
> 
> void loop() {
>   SerialX.write(0xAA);
>   while(SerialX.available() ){
>     Serial.write(SerialX.read());
>   }
>   Serial.write(0x55);
>   
> }

What will be shown on USART 1 is:

> Boot
> U

And at that Point the code seems to stop at all
![image](https://user-images.githubusercontent.com/41676430/73915502-cd611f80-48bb-11ea-8e17-be55dba393df.png)

PA2 is TX and PA3 is RX for hardware serial output we use PA9 / PA10 

Currently we try to investigate this further but stummbeled also accross some other issues that may lay down int the variant itself. The code works fine on a STM32F103 blue pill

**Comment by stas2z** [comment]
#895

**Comment by fpistm** [comment]
Hi @lab-mathias-claussen 

You can check the issue provided by  @stas2z

Anyway about this:

> Fit a STM32F072C8T6 on a bluepill

What would you mean by this ? You replaced the STM32F103 by a STM32F072C8T6  ?
So this is a custom board?
Which variant you used in this case?

**Comment by lab-mathias-claussen** [comment]
It uses the ELEKTOR_F072C8 variant, an we replaced the STM32F103 by a STM32F072C8T6. This is kind of a custom board for internal development to mimic the ELEKTOR_F072C8 variant. 

![image](https://user-images.githubusercontent.com/41676430/73917541-ee2b7400-48bf-11ea-8ef6-74ebe3418b96.png)

**Comment by lab-mathias-claussen** [comment]
Fixed with current code from Git repository
Thanks
