### ISSUE TITLE
Problem in building Arduino_Core_STM32 based project in Eclipse C/C++ IDE

### ISSUE THREAD

**Issue by engrziarehman** [stm32duino/Arduino_Core_STM32#929]
I installed the fresh eclipse C/C++ IDE 2019.
In "Preferences->arduino" I add the link for stm32 board (https://github.com/stm32duino/BoardManagerFiles/raw/master/stm32/package_stm_index.json).
In "Help"-> Arduino Download Manager, installed STM32 core.
Then i selected bluepill as New Launch Target, All of the stm32 list of MCUs appeared fine.
but when i click build the following error appears (attached).

> Undefined key build.source.path

![eclipse](https://user-images.githubusercontent.com/1841236/74158525-0c84cd00-4c3c-11ea-8715-0084abff683a.JPG)

**Comment by VitorBoss** [comment]
Did you follow those steps?
https://gnu-mcu-eclipse.github.io/plugins/packs-manager/

https://gnu-mcu-eclipse.github.io/tutorials/blinky-arm/

**Comment by engrziarehman** [comment]
@VitorBoss Thankyou for your reply, I have not followed this step, when i installed STM32 core inside download manager, it downloaded all of the pre-requisites. do you still feel i need to follow above steps for arduino environment?.
further i brief, when i select AVR based core, eclipse build fine and locate Arduino.h included file correctly but when i select this Arduino_Core_STM32 you can see in image, eclipse can't even locate `Arduino.h` file,

**Comment by fpistm** [comment]
@engrziarehman 
Unfortunately, we doesn't support another IDE than Arduino.
You can try to open a topic about that on the forum to get help.

**Comment by jamesjian007** [comment]
Thanks. Now make sense.
