### ISSUE TITLE
variant.h

### ISSUE THREAD

**Issue by valoni** [stm32duino/Arduino_Core_STM32#94]
i'm playing with Nucleo STM32F411RET6 

**but when I used Adafruit GX and Oled Library for SSD3306 via I2C i face a problem
with declaration of** 

#define SS                      BOARD_SPI_DEFAULT_SS
#define SS1                     4
#define SS2                     7
#define SS3                     8
#define MOSI                    11
#define MISO                    12
# **#define SCLK                    13**
#define SCK                     SCLK

**than i decide to rename those pins to**
//On-board LED pin number
#define LED_BUILTIN             D13
#define LED_GREEN               LED_BUILTIN

//On-board user button
#define USER_BTN                D23

//SPI definitions
//define 16 channels. As many channel as digital IOs
#define SPI_CHANNELS_NUM        16

//default chip salect pin
#define BOARD_SPI_DEFAULT_SS    D10
#define SS1                     D4
#define SS2                     D7
#define SS3                     D8
#define MOSI                  D11
#define MISO                 D12
define SCLK                    D13

//I2C Definitions
#define SDA                    D14
#define SCL                     D15

#define PIN_SERIAL_RX           D0
#define PIN_SERIAL_TX           D1
#define PIN_SERIAL1_RX          D2
#define PIN_SERIAL1_TX          D8
#define PIN_SERIAL2_RX          D9
#define PIN_SERIAL2_TX          D34

**to avoid this kind of problems with libraries and no more problem  with Adafruit SSD3306 libraries**

**Comment by fpistm** [comment]
Hi @valoni,

This issue will be Fix in next release.
I've already remove SCLK definition.
See: [Remove SCLK definition ](https://github.com/stm32duino/Arduino_Core_STM32/commit/ebe46ff84295ca658bc20ff3f6e1b8b93adeede9)

I've tested with the Adafruit SSD1306 library, it's ok.
