### ISSUE TITLE
bxCAN Library

### ISSUE THREAD

**Issue by nopnop2002** [stm32duino/Arduino_Core_STM32#949]
I would like a bxCAN Library available on Arduino Core.

**Comment by fpistm** [comment]
Hi @nopnop2002 
Duplicated of #259 related to CAN

**Comment by nopnop2002** [comment]
Please try to make support ASAP.

**Comment by fpistm** [comment]
Unfortunately, this will not easy.
It is a community project so anyone can contribute to provide a library.
Or at least an user can use HAL/LL to manage is use case. Several examples are available in the STM32Cube Firmware and can be ported as I don for ADC DMA as an example in the forum.

**Comment by fpistm** [comment]
Here an example of CAN implementation made by @geosmall 
https://www.stm32duino.com/viewtopic.php?f=10&t=99

**Comment by nopnop2002** [comment]
I know Libcanard, but it's not basic.

We need a more basic library.

**Comment by fpistm** [comment]
I know, I share it as an example how to use HAL CAN module.
