### ISSUE TITLE
Error while including the library

### ISSUE THREAD

**Issue by RohiniNadakuditi** [stm32duino/Arduino_Core_STM32#956]
Hi,
I am included the this library in Arduino IDE for stm32f103c8t6 blue pill board.
While including the library getting error : "Specified folder/zip file does not contain a valid library".
Please help me how to solve this problem and I am requesting the library for the watchdog timer for stm32f103c8 board.

**Comment by fpistm** [comment]
Hi @RohiniNadakuditi 
This is not a library. This is a core.
https://www.arduino.cc/en/guide/cores

Please read the README.md.
