### ISSUE TITLE
Error in boards.txt file for Nucleo-L432KC

### ISSUE THREAD

**Issue by Erik7716** [stm32duino/Arduino_Core_STM32#96]
Release: 2017.8.31

The values for the .upload.maximum_size and .upload.maximum_data_size are swapped in the boards.txt file for the NUCLEO_L432KC board on lines 229 and 230.

Current incorrect lines:
Nucleo_32.menu.board_part_num.NUCLEO_L432KC.upload.maximum_size=65536
Nucleo_32.menu.board_part_num.NUCLEO_L432KC.upload.maximum_data_size=262144

This should be:
Nucleo_32.menu.board_part_num.NUCLEO_L432KC.upload.maximum_size=262144
Nucleo_32.menu.board_part_num.NUCLEO_L432KC.upload.maximum_data_size=65536

**Comment by fpistm** [comment]
Thanks @Erik7716
