### ISSUE TITLE
Support for USB Host/Device

### ISSUE THREAD

**Issue by rtek1000** [stm32duino/Arduino_Core_STM32#960]
STM32CubeIDE (STM32CubeMX) already has support for Audio, HID, MSC, CDC, Virtual Port, MTP. Perhaps it will be much faster if you can use these libraries as a base so that this core can support these functions.

I found an example of Ethernet, LAN8720, which makes use of a LWIP library compatible with this core, and I found it very interesting. Perhaps it was based on the STM32CubeMX LWIP library.

> LwIP
> Lightweight TCP/IP stack (LwIP) is a small independent implementation of the TCP/IP protocol suite that has been initially developed by Adam Dunkels and is now continued here.
> Modified to fit Arduino libraries specifications.

https://github.com/stm32duino/LwIP

**Comment by fpistm** [comment]
Hi @rtek1000 

This core already used those middlewares.
The HID and VCP use the STM32_USB_Device_Library : https://github.com/stm32duino/Arduino_Core_STM32/tree/master/system/Middlewares/ST

For the USB Host, there is no dedicated implementation but the STM32_USB_Host_Library is already included.

For Ethernet, the [STM32Ethernet](https://github.com/stm32duino/STM32Ethernet) already provide that and is based on LwIP. As you can see this is the part of STM32duino GitHub organization.

**Comment by rtek1000** [comment]
Thank you for explaining your answer.

I did a project with STM32CubeIDE with Mouse (HID) and Pendrive (MSC). The code automatically generated by the IDE included Middlewares HID and MSC, also included FatFs.

Are Middlewares also included in the Arduino core?

In spite of not having a dedicated implementation, is it possible to perform a functional sketch, or is there still some piece of software missing?

![Middleware](https://user-images.githubusercontent.com/8660811/75668466-21131e80-5c58-11ea-831a-db3332f51cef.png)

**Comment by rtek1000** [comment]
I think I found the answer about the Middleware

![Middleware_Found](https://user-images.githubusercontent.com/8660811/75669008-fa091c80-5c58-11ea-947b-19fcf0330b9e.png)

**Comment by fpistm** [comment]
Yes.
USB host and device libraries are included in the core.
LwIP and FatFs like Arduino libraries.

**Comment by rtek1000** [comment]
I tried to follow the references of the STM32CubeIDE project, but it seems that the Arduino IDE cannot automatically locate the files that are already embedded.

Can I force indexing files manually?

![file not found](https://user-images.githubusercontent.com/8660811/75672459-90d8d780-5c5f-11ea-8c39-15d60e062bfb.png)

**Comment by fpistm** [comment]
Modify the platform.txt or use the platform.local.txt to add it to the include path.
Or you can even use the build_opt.h.

https://github.com/stm32duino/Arduino_Core_STM32/blob/85a7a2819214ea2c61b3071f5e6e3f7f2fbb347c/platform.txt#L12

**Comment by fpistm** [comment]
And please, use the forum for those kind of support request. Issue is not intended for support request.
Thanks in advance.

**Comment by rtek1000** [comment]
Thanks, in fact i had already posted on the forum, but maybe very few people know about these details.

https://forum.arduino.cc/index.php?topic=668183.0

**Comment by fpistm** [comment]
stm32duino.com

**Comment by rtek1000** [comment]
This doesn't seem to be working anymore.

![stm32duino](https://user-images.githubusercontent.com/8660811/75688736-c80ab100-5c7e-11ea-91e5-daf93cf54a7a.png)

**Comment by rtek1000** [comment]
https://github.com/arduino/arduino-cli/issues/600

**Comment by fpistm** [comment]
Seriously @rtek1000 
did you try with https for example?
https://www.stm32duino.com/index.php

**Comment by fpistm** [comment]
For the issue open in the arduino-cli, I guess your config is not correct.
Before opened an issue try to understand why it's not work.
You didn't add the path to the 
`system/Middlewares/ST/STM32_USB_Host_Library/`
Only to the Device...

**Comment by rtek1000** [comment]
> 
> 
> Seriously @rtek1000
> did you try with https for example?
> https://www.stm32duino.com/index.php

In fact I copied "stm32duino.com" and pasted it into the address bar of the firefox browser. Good it seems to be working.

**Comment by rtek1000** [comment]
> 
> 
> For the issue open in the arduino-cli, I guess your config is not correct.
> Before opened an issue try to understand why it's not work.
> You didn't add the path to the
> `system/Middlewares/ST/STM32_USB_Host_Library/`
> Only to the Device...

Sorry, but I didn't set this up. I just found it in the repository and I'm testing it.

**Comment by rtek1000** [comment]
> 
> 
> For the issue open in the arduino-cli, I guess your config is not correct.
> Before opened an issue try to understand why it's not work.
> You didn't add the path to the
> `system/Middlewares/ST/STM32_USB_Host_Library/`
> Only to the Device...

Oh, OK, understood.

`"-I{build.system.path}/Middlewares/ST/STM32_USB_Device_Library/Core/Src"`

`"-I{build.system.path}/Middlewares/ST/STM32_USB_Host_Library/Core/Src"`

But shouldn't that already be in the repository file?

**Comment by fpistm** [comment]
> But shouldn't that already be in the repository file?

No, as I said, currently there is no Host USB support so no need to add it to the Include path.

**Comment by rtek1000** [comment]
Done.

https://www.stm32duino.com/viewtopic.php?f=7&t=197&p=1372#p1372

**Comment by rtek1000** [comment]
Adding the files here, because the forum does not accept the large size.
In case anyone else wants to try to make it work.

STM32F407VG (DiyMore) USB Port FS (CN1 or PA11: DM, PA12: DP; PC9: Drive_VBUS)

Functional Example; STM32CubeIDE (V1.3.0; FW_F4 V1.25.0)
[F407_USB_HOST_MSC_CPP.zip](https://github.com/stm32duino/Arduino_Core_STM32/files/4277689/F407_USB_HOST_MSC_CPP.zip)

Arduino example; Not Functional, but compiles without errors, It must be missing to call some routine.
[USB_Host.zip](https://github.com/stm32duino/Arduino_Core_STM32/files/4277718/USB_Host.zip)

> Sketch uses 15900 bytes (1%) of program storage space. Maximum is 1048576 bytes.

Source: http://evenlund.blogspot.com/2016/10/usb-storage-with-stm32f4-discovery-and_58.html

**Comment by delgadosouza** [comment]
Dear @rtek1000 , did you get the Arduino example to work?

I have a BlackPill STM32F401 and would like to use its USB capabilities to read and write text files to a thumbdrive, nothing else.

**Comment by rtek1000** [comment]
> Dear @rtek1000 , did you get the Arduino example to work?
> 
> I have a BlackPill STM32F401 and would like to use its USB capabilities to read and write text files to a thumbdrive, nothing else.

Unfortunately I don't have it, sorry
