### ISSUE TITLE
Write to SD card quick than 9000Hz?

### ISSUE THREAD

**Issue by Bambofy** [stm32duino/Arduino_Core_STM32#962]
**Is your feature request/improvement related to a problem? Please describe.**
My problem is when using the SD card writing functions i cannot seem to write at a rate of more than 9000hz.

**Describe the solution you'd like**
I would like to write to the SD card at 16000Hz.

**Describe alternatives you've considered**
This library can sample at 16000Hz however it is untested with the STM32 https://github.com/TMRh20/TMRpcm

**Comment by fpistm** [comment]
@Bambofy 

> My problem is when using the SD card writing functions

what did you expect with this description?
Which board you used?
which SD interface you use? is it a SD card over SPI? SDIO? SDMMC ?

And again use the forum for this kind of question/support request!
