### ISSUE TITLE
Please  support  Irremote

### ISSUE THREAD

**Issue by lemontreenm** [stm32duino/Arduino_Core_STM32#970]
I can not find a  usable Arduino Irremote for stm32.  It‘s very important to DIY.

**Comment by fpistm** [comment]
Hi @lemontreenm 
you should post your question on the forum: https://www.stm32duino.com
Maybe someone already use an IRremote library compatible.
Here this is issue for the core, you request a third party library support. This should be open in one of the third party library. For example this one:
https://www.arduinolibraries.info/libraries/i-rremote
