### ISSUE TITLE
Other USB_CONNECT pin

### ISSUE THREAD

**Issue by mrguen** [stm32duino/Arduino_Core_STM32#980]
Hi,

Could you tell me if it would be possible to modify the pin used for USB_CONNECT. The pin used on the STM32F401RC board I am using is PD2 but I would be using this pin that is also SDIO_CMD to communicate with an SD CARD. So I would like to change it.

**Comment by fpistm** [comment]
Issues are not a support forum.

Please, post to https://www.stm32duino/com
