### ISSUE TITLE
black magic probe

### ISSUE THREAD

**Issue by koendv** [stm32duino/Arduino_Core_STM32#986]
Upload firmware using black magic probe does not work

Choose: Tools->Upload Method->Black Magic Probe
then: Sketch->Upload
Error message:
```
{runtime.tools.arm-none-eabi-gcc.path}/bin/arm-none-eabi-gdb -nx -b 230400 -batch -ex set confirm off -ex target extended-remote /dev/ttyACM1 -ex monitor swdp_scan -ex attach 1 -ex load -ex compare-sections -ex kill /tmp/arduino_build_671172/Blink.ino.elf 
java.io.IOException: Cannot run program "{runtime.tools.arm-none-eabi-gcc.path}/bin/arm-none-eabi-gdb": error=2, No such file or directory
```
{runtime.tools.arm-none-eabi-gcc.path} is not defined when the xpack compiler is installed.
To work, the file `.arduino15/packages/STM32/hardware/stm32/1.8.0/platform.txt` needs to be patched:

```
--- platform.txt.ORIG	2020-03-13 09:17:53.108789031 +0100
+++ platform.txt	2020-03-13 09:30:37.415735421 +0100
@@ -176,7 +176,7 @@
 
 # blackmagic upload for generic STM32
 tools.bmp_upload.cmd=arm-none-eabi-gdb
-tools.bmp_upload.path={runtime.tools.arm-none-eabi-gcc.path}/bin/
+tools.bmp_upload.path={compiler.path}
 tools.bmp_upload.upload.speed=230400
 tools.bmp_upload.upload.params.verbose=-batch
 tools.bmp_upload.upload.params.quiet=--batch-silent
```

**Comment by fpistm** [comment]
Hi @koendv 
In fact, this should work as {runtime.tools.arm-none-eabi-gcc.path} is correct, the only issue here, it is that it does not reference the version to use. So if you installed several core wit different arm none eabi gcc toolchains thanks the board manager it will use one of them not specifically the one linked to the core.
I don't know why you get this error, as it should be able to solve this. Maybe this could be linked to the fact you didn't install thanks the boards manager?

Anyway, it sound reasonable to change this to specify exactly which version to use.

**Comment by fpistm** [comment]
I tried to use compiler.path  but it is not known/expand at this step. Don't know why it works for you. 😕 
Tested on Linux.

**Comment by koendv** [comment]
Thank you. Your patch to platform.txt solves this issue; black magic probe upload now works fine.
