### ISSUE TITLE
Build with CMD

### ISSUE THREAD

**Issue by Pararera** [stm32duino/Arduino_Core_STM32#998]
How to build project using CMD((Windows 10) for STM32F103(128kB)?
I need to build project but I can't with Sublime Stino plugin(it says toolchain is not ready), but with Arduino IDE I can build project. What I have to type to start building? Thanks!

**Comment by uzi18** [comment]
You should ask for help on Sublime Stino plugin community, we don't know how to help you

**Comment by Pararera** [comment]
We can't build project from CMD?

**Comment by fpistm** [comment]
Hi @Pararera 
Only the Arduino IDE is supported.
I never even used Sublime IDE nor knew that there is a Stino plugin.
As @uzi18 advised you should open an issue or ask for help on Sublime Stino plugin community.
You can also try to ask support on the https://www.stm32duino.com forum in this section:
[Board index -> Arduino for STM32 -> IDE's](https://www.stm32duino.com/viewforum.php?f=18&sid=db87ac7bb142d4430fe24f194d1d44bf)
